### ISSUE TITLE
Extra / in url when "redirect to file"

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/download-monitor#1007]
There is an extra / in the URL when the user is redirected from a download with "redirect to file" enabled.
![image](https://user-images.githubusercontent.com/19348508/184359831-63d3006f-e8c0-4cbf-a09e-a451392aa9d7.png)
The issue seems to be here https://github.com/WPChill/download-monitor/blob/4.5.96/src/DownloadHandler.php#L516

**Comment by chloebunce-motion** [comment]
Hello - I'm having the same issue, will there be a fix for this soon? Thanks

**Comment by razvanaldea89** [comment]
New redirect based on uploads fixes this problem. https://github.com/WPChill/download-monitor/commit/5f8ef290ec6db589c14e069b8b723f80b60082bf
