### ISSUE TITLE
Error adding a new file

### ISSUE THREAD

**Issue by joska1993** [WPChill/download-monitor#1008]
**Describe the bug**
Error adding a new file. It's not a database problem.

**To Reproduce**
Add a new file to an already created element.

**Expected behavior**
Add new 

**Screenshots**
![image](https://user-images.githubusercontent.com/4182345/184842574-a621d5c7-7ef9-4d52-8ec7-241313801d14.png)

**Extensions installed and activated:**
I only activate "Download Monitor" for free

**Comment by razvanaldea89** [comment]
@joska1993 can you please translate what it says in the error report?

**Comment by joska1993** [comment]
> Contributor

Thanks for your involvement, I propose a solution.

**SOLUTION:** I did a database cleanup with the plugin "WP-Optimize - Clean, Compress, Cache" and everything was solved.

**Comment by razvanaldea89** [comment]
Great, thanks for the info.

Have a wonderful day!
Razvan
