### ISSUE TITLE
Seems like sometimes there is a problem between HTTP2 and content-length headers

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1030]
**Describe the bug**
Commenting lines in this if ( https://github.com/WPChill/download-monitor/blob/4.5.97/src/DownloadHandler.php#L694 ) seems to fix the problem, but we don't know why (yet!).

**Comment by perplexityjeff** [comment]
Commenting out the header lines in the 'IF' statement did indeed fix the issue. The issue from our point of view seems to only occur on larger files. 

The error returns 'ERR_HTTP2_PROTOCOL_ERROR'.

**Comment by perplexityjeff** [comment]
This issue also occurs in 4.6.1

**Comment by razvanaldea89** [comment]
Hello @perplexityjeff ,

Could you be kind and let us know if version 4.7.3 solved your problems? Appears that on some clients with the same issue now it works.

Warmly,
Razvan

**Comment by razvanaldea89** [comment]
Possible cause for this was the warning triggered in the download process, maybe it ended in the output buffer and the browser was ending the download sooner than it should. Most download troubles seem to be fixed with version 4.7.3 of the plugin.

**Comment by perplexityjeff** [comment]
Hi @razvanaldea89, it does seem that the issue has been resolved. I will now monitor it and will update you when or if it occurs again.

**Comment by razvanaldea89** [comment]
Thank you very much for the info and feedback :D

**Comment by razvanaldea89** [comment]
Going to close this, if by any chance this happens again please feel free to re-open it.

Warmly,
Razvan
