### ISSUE TITLE
Canceled payment attempts cause cause incorrect escape chars in a few <form> attr 

### ISSUE THREAD

**Issue by GodModus** [WPChill/download-monitor#1032]
**Describe the bug**
Whenever a client attempts to pay for an order but than cancels it, he/she is redirected back to the checkout page. Nothing seems off at first glance. But a minor error in the &lsaquo;form&rsaquo; attributes `data-order_id` and `data-order_hash` creates a big issue when attempting to pay. Leading DLM to create a new order which causes a big issues (later explained in more details)

**To Reproduce**
1. Add a paid product to your cart
2. Go to checkout page and select a payment method (paypal sandbox?)
3. Let the payment method send a cancel response.
4. This should redirect you back to the checkout page. Note that DLM repopulates the page using the $_POST values. The cart cookies have been erased when payment was initiated.
5. Now view the source code and notice errors in the &lsaquo;form&rsaquo;  element `data-order_id` and `data-order_hash` attributes (see next heading)
6. keep the value of order_id in mind. Now hit the pay now button again. Since the values of the aforementioned attributes contain errors DLM cant fetch the order and prompts to create a new order. This order has a total values of $0. Most payment methods dont allow a value of $0 and thus trigger an error. The payment fails yet again.

What causes this issue is esc_attr( $form_data_str ) on wp-content/plugins/download-monitor/templates/shop/checkout.php  @ line 25. 
$form_data_str =  `data-order_id="89" data-order_hash="f030ff5741bc6567f32fb96d9bd3d7cea46d4b2f"`
esc_attr() escapes the double qoutes, resulting in `data-order_id=&quot;89&quot; data-order_hash=&quot;f030ff5741bc6567f32fb96d9bd3d7cea46d4b2f&quot;`

**Expected behavior**
`<form method="post" action="https://idealplugins.local/dlm-checkout/" id="dlm-form-checkout" data-order_id="88" data-order_hash="4cd77878e4d216be7a9482bc73d2175ad175deaf">`

**Actual behavior (see, escaped double quotes)**
`<form method="post" action="https://idealplugins.local/dlm-checkout/" id="dlm-form-checkout" data-order_id=&quot;88&quot; data-order_hash=&quot;4cd77878e4d216be7a9482bc73d2175ad175deaf&quot;>`

**How to resolve this issue**
1. Either remove the redundant esc_attr() onwp-content/plugins/download-monitor/templates/shop/checkout.php @25 (values were already escaped on wp-content/plugins/download-monitor/src/Shop/Shortcode/Checkout.php @75)
2. Or remove the double quotes encapsulating the %s in `'form_data_str' => sprintf( 'data-order_id="%s" data-order_hash="%s"', esc_attr( $order->get_id() ), esc_attr( $order->get_hash() ) ),` on wp-content/plugins/download-monitor/src/Shop/Shortcode/Checkout.php @75

**Comment by cristianraiber** [comment]
nice catch 👏

**Comment by cristianraiber** [comment]
@GodModus - if you don't already have a dev job, send me an email through the contact form on download-monitor.com - I'd love to chat

**Comment by razvanaldea89** [comment]
Think we'll leave the esc_attr along with the double quotes and use `htmlspecialchars_decode( esc_attr( $form_data_str ), ENT_QUOTES );` so we can keep the escaping on echo ( wpcs ) and keep the double quotes ( I think that some plugins that check the HTML of the page will trigger error for attributes without double quotes - see in page source )
