### ISSUE TITLE
Delete files when deleting Downloads

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#1034]
**Is your feature request related to a problem? Please describe.**
Is it possible to delete a file and remove it from the media library when removing an old version from a download? 
https://wordpress.org/support/topic/delete-files-when-removing-older-versions/

**Comment by mplusb** [comment]
https://secure.helpscout.net/conversation/2041546082/50777?folderId=4638445

**Comment by razvanaldea89** [comment]
We should delete files from all versions when a Download is deleted.

**Comment by TeoAlex** [comment]
I don't think we should delete the files on download delete. in my opinion, there are numerous reasons why i might want to delete a download but keep the files.

- This might be the only place i have the files stored, i need the files but not the download.
- The download is a duplicate, and i need to fix that by deleteing 1.
- I just want to reset the counters/ locks for a download and it's easyer to just delete it and create a new one with the exact file.
- We could make it so we only delete files in dlm_uploads but what if there are multiple downloads using the same file?
- ...
