### ISSUE TITLE
Media Library within the plugin not showing media uploaded through plugin

### ISSUE THREAD

**Issue by micksw** [WPChill/download-monitor#1047]
**Describe the bug**
When creating a download post, the media files that have recently been uploaded within the DLM plugin does not show up. The media that has been uploaded directly in the media library in the WP backend side menu, is shown.

This has only been tested with PDF file types so far. 

**To Reproduce**
1. Go to the Download Monitor plugin
2. Create a new download post
3. Upload a dummy .pdf file but do not select that file.
4. Use the 'Media Library' button in the post to select the previously uploaded pdf file.
5. Error: This media file is not shown in this media library. No error message is shown.

**Expected behavior**
The previously uploaded file is shown in the media library in the plugin and can be selected by the user.

**Screenshots**
No screenshots provided.

**Extensions installed and activated:**
- No extensions installed.

**Version**
Tested with the latest version.

**Comment by razvanaldea89** [comment]
![image](https://user-images.githubusercontent.com/44024114/194511185-5adf318d-f855-4060-adce-a7cc698b2164.png)

![image](https://user-images.githubusercontent.com/44024114/194511252-fa356ab3-ab55-43db-b9b0-17c35c368e20.png)
