### ISSUE TITLE
Page has limited entries

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#1053]
**Describe the bug**
I need at least 25 or better yet 50 per page. Now it has only 10
https://secure.helpscout.net/conversation/2023163037/50158?folderId=4656047

**Comment by razvanaldea89** [comment]
![image](https://user-images.githubusercontent.com/44024114/194509913-1306b9a5-b9f6-4ce1-828f-c6693bc0b2d3.png)
