### ISSUE TITLE
no one can finish the download

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#1058]
**Describe the bug**
I updated the plugin to the latest version and now the downloads don't work, they start but never finish. 
https://grupocorredoira.com/producto/intcarplaynbtv2/

https://secure.helpscout.net/conversation/2024573589/50202?folderId=4656047

**Comment by beatricelucaci** [comment]
+1 https://secure.helpscout.net/conversation/2025512911/0/?folderId=4638443

**Comment by beatricelucaci** [comment]
+1 https://secure.helpscout.net/conversation/2021745744/50113?folderId=4656047
<img width="1432" alt="Screenshot 2022-10-04 at 11 35 39" src="https://user-images.githubusercontent.com/84579642/193774178-ebbad20f-c18a-474d-8963-dd0796cbc6d7.png">

**Comment by razvanaldea89** [comment]
Seems to be fixed. Went on client website and tried the downloads, all of the downloads I tried ( about 10-15 ) seemed to work fine. Going to close this.
