### ISSUE TITLE
Incompatibility with nginx

### ISSUE THREAD

**Issue by haschmide** [WPChill/download-monitor#1068]
**Describe the bug**
It seems download monitor is broken with nginx hosted wordpress.
Setup:

**To Reproduce**
Category bound by tag static page in wp:
[downloads category="mycat"]

So the plugin is generating its links by itself.
JS Code of plugin checks for property "content-disposition" in reply. This is only autogenerated by Apache, not by nginx.
All downloads are broken.

**Expected behavior**
Download just works

**Screenshots**

**Extensions installed and activated:**
- [ ] Advanced Access Manager
- [ ] Amazon S3
- [ ] Buttons
- [ ] Captcha
- [ ] CSV Exporter
- [ ] CSV Importer
- [ ] Downloading Page
- [ ] Email lock
- [ ] Email Notifications
- [ ] Google Drive
- [ ] Gravity Forms
- [ ] Mailchimp
- [ ] Ninja Forms
- [ ] Page Addon
- [ ] Terms & Conditions
- [ ] Twitter Lock

**Additional context**

**Comment by cristianraiber** [comment]
link to site where we could test this? which version of nginx r u using? whoch version of DLM / WP / PHP?

**Comment by haschmide** [comment]
Link to site with problem: https://haschmi.de (cannot promise that this will be testable for long, might need to replace with another plugin)
nginx/1.18.0 (Ubuntu)
Ubuntu 22.04 LTS
PHP 8.1.2 (cli) (built: Jun 13 2022 13:52:54) (NTS)
WP 6.0.2
DLM 4.6.3 Lite

**Comment by razvanaldea89** [comment]
Hey @haschmide ,

Have you modified the plugin or are you blocking headers set from the plugin? Seems like none of our headers are getting through.

**Comment by haschmide** [comment]
I crosschecked nginx config and found one thing.
$is_args$args was missing as params to index.php

Files can be downloaded now but one (First on page to download) will still cause an JS error.

**Comment by haschmide** [comment]
Those mentioned are PDF and actually missing at the moment.
I was referring to the first download: https://www.haschmi.de/download/intelligent-surface-lite-otrs-6-0/
The JS error there should translate to: Failed to load resource: Loading of the frame was interrupted

**Comment by cristianraiber** [comment]
Clicking on that link above works fine on Safari, MacOS

Here's the contents of the ZIP: Intelligent Surface Lite-6.0.6.opm

**Comment by haschmide** [comment]
Hmm Clicking the auto generated link from the category listing gives me the mentioned error on macOS Safari. The file downloads without problem though.

**Comment by razvanaldea89** [comment]
Downloading that file triggers an odd behavior that is not present in the others: refreshing the window. And seems that, depending on browser, something different is downloaded : on safari there is a .opm file and on the rest a .zip file.

**Comment by cristianraiber** [comment]
@razvanaldea89 - Safari, by default, unzips archives. Just Google "Safari turn off unzipping".

**Comment by haschmide** [comment]
At least on my side this is disabled but the JS error still occurs (so zip is downloaded but still shows Failed to load resource

**Comment by razvanaldea89** [comment]
Closing this as it seems everything is working. Could bot get the JS error @haschmide mentioned, but 4.6.4 has some fixes regarding the redirect to file functionality. If problem still occurs opening another ticket for specific problem would better.
