### ISSUE TITLE
Remove the caching for reports

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/download-monitor#1070]
Should we remove the Reports 12h cache?

Someone reported that removing the cache every time you want to view the reports for the day is inconvenient. 

Furthermore some people don't know that they can remove only the cache from the browser and they are removing the saved log-ins, 2-factor auths and cookies.

On the other hand, cache helps a lot with the speed of reports page loading, more so on site's with hundreds of downloads.

An other ideea is to add a setting (default to on) that enables/disables the caching.

@cristianraiber @giucu91 @razvanaldea89 ?

**Comment by razvanaldea89** [comment]
We could add a button that can delete the cache and refresh the page so that the user sees the new reports.
