### ISSUE TITLE
Adding a download via Insert Download > Quick-add download don't save file path correctly.

### ISSUE THREAD

**Issue by benhuson** [WPChill/download-monitor#1071]
**Describe the bug**
When adding a download in admin via Downloads > Add New, when I upload a file it initially adds it into the File URL field as an http URL. When I save/publish the Download (post) it updates this URL to be a server file path eg. `{server_file_path}/wpcontent/uploads/dlm_uploads/...`

When adding a download via Insert Download > Quick-add download, then after check the file path that has been saved, it is stored as an `http` URL, not a server file path.

Having the URL (rather than file path) does not work in our hosting configuration.

**To Reproduce**
1. Go to edit a post/page
2. Click on 'Insert Download' button above editor.
3. Click on 'Quick-add Download' tab.
4. Upload a file.
5. Go to 'Downloads' in the amain admin menu.
6. Click into the new download that has been created.
7. Expand the file panel in the 'Downloadable Files' box.
8. The download has been saved as a file URL, not a server path.

**Expected behavior**
The file should be saved as a file path like when you publish the download via 'Downloads > Add New'.

**Additional context**
Hosted on AWS.

**Comment by razvanaldea89** [comment]
Hey @benhuson ,

Thanks for reporting this. Fix will be included in version 4.6.5 that will be launched today.

Warmly,
Razvan
