### ISSUE TITLE
 filter duplicated download of the same file from the same IP

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#1074]
**Is your feature request related to a problem? Please describe.**
I would like to make a feature suggestion. Add ability to filter duplicated download of the same file from the same IP. the reason is... Situation: user has downloaded a file a few days ago but don't remember where it is and download it again, that's 2 downloads of the same file by the same IP. the percentage of people who does that it's not a lot but it can sum up to big differences over the long run. So for example we could see 500 downloads and think ¨500 people downloaded this file, it's doing well¨.. but actually it was 460, by the year the difference can be huge on single file downloads from IP to all file downloads. I see the plugin shows downloads from specific IP's but has no way to filter single download per file. Literally one person or bot could download the same file 100 times and on Download Monitor stats would show all of them and we as content creators would suppose it was 100 people (or close to it). The goal with this suggestion is just to have a more reliable analytics. 

https://secure.helpscout.net/conversation/2032276153/50445/

**Comment by cristianraiber** [comment]
pro feature - show unique downloads in enhanced metrics

**Comment by cristianraiber** [comment]
unique = unique ips

**Comment by razvanaldea89** [comment]
Ummm......we have this option

![image](https://user-images.githubusercontent.com/44024114/194836818-a128cd13-ae25-49df-9340-d767501bc642.png)

**Comment by razvanaldea89** [comment]
@beatricelucaci
