### ISSUE TITLE
new update issue with email lock + email notification

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#1075]
**Describe the bug**
if you add el_email in your fields for email notification email it will not display the email used to unlock the download.

**To Reproduce**
1. install email lock + email notification
2. go to settings > Emails > enter there el_email
3. test > see email notification is missing the email used to unlock the download.

**Extensions installed and activated:**
- [ ] Advanced Access Manager
- [ ] Amazon S3
- [ ] Buttons
- [ ] Captcha
- [ ] CSV Exporter
- [ ] CSV Importer
- [ ] Downloading Page
- [x] Email lock
- [x] Email Notifications
- [ ] Google Drive
- [ ] Gravity Forms
- [ ] Mailchimp
- [ ] Ninja Forms
- [ ] Page Addon
- [ ] Terms & Conditions
- [ ] Twitter Lock

**Comment by mplusb** [comment]
<img width="924" alt="Screenshot 2022-10-10 at 11 30 36" src="https://user-images.githubusercontent.com/26008574/194826467-55c6a391-1480-4ab2-980c-cc338f5b4b6b.png">

**Comment by amof-fjell** [comment]
Hi

I have already done what you describe. But in the mail I recieve, the el_email field is empty.

**Comment by amof-fjell** [comment]
Email lock is working, and when I enter a download I can see the registrated email addresses. But the email adress is not written in the email i recieve from notification. Even if I use el_email.
The mail I recieve only contain IP, address and document name. The el_email is blank

**Comment by razvanaldea89** [comment]
An update will be released today containing a fix for this ( DLM Email Lock v4.3.3 will be required also for this to work ). Problem was that the XHR functionality was not sending ( and DLM Email Lock was not adding headers to the XHR ) proper headers/post data to be verified by DLM Email Lock

**Comment by amof-fjell** [comment]
Thanks for your answer, Looking forward to recieve the update,
