### ISSUE TITLE
chinese file name displayed weirdly

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#1085]
**Describe the bug**
 I switched back to the 4.5.99 version display. When downloading the file, the Chinese name of the file name is displayed normally. 
<img width="818" alt="Screenshot 2022-10-14 at 09 26 31" src="https://user-images.githubusercontent.com/26008574/195777255-cde175f8-50d6-4784-99e0-efcd38a65f63.png">

**To Reproduce**
1. add this name to a file: 阅心安
2. download
3. See error

https://secure.helpscout.net/conversation/2035844077/50563?folderId=4638445

**Comment by razvanaldea89** [comment]
Similar to https://github.com/WPChill/download-monitor/issues/1069
