### ISSUE TITLE
Wrong url in anchor titles on Top Download widget

### ISSUE THREAD

**Issue by ggortan** [WPChill/download-monitor#1087]
**Describe the bug**
Using version 4.7.0
On top downloads widget the download titles is redirecting to
http://localhost/dev/wp-admin/post.php?post=1000&action=edit

**To Reproduce**
Try to click on any download title in "Top Downloads" widget in wordpress dashboard

**Expected behavior**
Redirection to download edit page

**Extensions installed and activated:**
none

**Comment by razvanaldea89** [comment]
Hey @ggortan ,

Thanks for picking up on this, don't know how we have missed that.

Warmly,
Razvan
