### ISSUE TITLE
Download count numbers recounted based only on log entries after db upgrade

### ISSUE THREAD

**Issue by ggortan** [WPChill/download-monitor#1088]
**Describe the bug**
Using version 4.7.0
After updating the download count was messed up and recounted based on existing download log records besides the _download_count meta key in postmeta table.
 Since the previous versions gave the ability to delete log files (and was nice touch to have to clear some record from the db) the download reports was never a good way to measure download counts by download times and the "real download" counter was the metadata on the post.
The system changed and created a new table dlm_downloads to track download times records but the data was badly migrated

**To Reproduce**
update from version 4.6.x to 4.7.0 and run the database upgrade

**Expected behavior**
download count remaining the same as before

**Extensions installed and activated:**
none

**Additional context**
The old download count data remains in the postmeta table and can be manually or scripted migrated to the new dlm_downloads table.

**Comment by razvanaldea89** [comment]
Hey @ggortan ,

On version 4.6.x we were relying on the download logs to do the counting and have removed the ability to delete the logs from the dashboard/plugin logs, with more accurate and complex download counts and reports.

For performance issues, on version 4.7.0 and above we added another table, dlm_downloads, that will keep track of the download counts of the Download and it's Versions and left the logs to be responsible for the Reports section of the plugin.

Values from the post meta can still be taken into consideration if you hook this filter ( `dlm_count_meta_downloads` ) found [here](https://github.com/WPChill/download-monitor/blob/4.7.1/includes/backwards-compatibility/class-dlm-backwards-compatibility.php#L285) and [here](https://github.com/WPChill/download-monitor/blob/4.7.1/includes/backwards-compatibility/class-dlm-backwards-compatibility.php#L363) by returning `true`. 

Warmly,
Razvan

**Comment by razvanaldea89** [comment]
Going to close this. We'll bring back by default the `post meta` counts and we'll re-enable the possibility to modify the counts by hand, so the total download count will be : custom table + post meta in version 4.7.3 of the plugin.

As a notice, the post meta won't be increased/incremented with every successful download, just the custom table.
