### ISSUE TITLE
  Long waiting time to start download

### ISSUE THREAD

**Issue by ggortan** [WPChill/download-monitor#1089]
**Describe the bug**
Using version 4.7.0
After the update the system to retrieve the download appears to have changed, there is now loading dots after pressing the button and the buttons gets disabled. I've notice a huge increase in waiting time after pressing the download button and the start of the download, appears the be size related because large files take longer to start downloading.

**To Reproduce**
click the download button or link the download takes way more time to start

**Expected behavior**
almost immediate download start

**Extensions installed and activated:**
none

**Comment by razvanaldea89** [comment]
Hey @ggortan ,

Since version 4.6.0 we are relying on XMLHttpRequest to get the contents of the file, that is why the download won't start ( the browser won't display that the file is being downloaded ) immediately, the contents being saved into a buffer and then served to the user. Doing this allows us to save and give the users more complex data about the downloads. 

Hope this helps!
Warmly,
Razvan

**Comment by razvanaldea89** [comment]
@ggortan could you please give a link to your problematic Download? It may be [this issue](https://github.com/WPChill/download-monitor/issues/1094) here, but would like to take a look to see if that is the case.

Warmly,
Razvan

**Comment by ggortan** [comment]
Of course, my website is in Brazilian Portuguese with custom download monitor template, if you need access to template PHP files let me know.

Try to download the first file in "Downloads hosted on Base G" section of this article. The first MGV file has about 1Gb.

https://baseg.com.br/1947/mgv7/

**Comment by razvanaldea89** [comment]
Yep, seems like the file size is not sent with the headers so the script doesn't know how much is has to download, thus only showing the 2 dots spinning together. If the file size would have been sent it would have shown a percentage of file buffered, and when it would hit 100% the would download completely. Tested on your Download with around 2s for each download, both direct and with XMLHttpRequest. 
Also, what I noticed on your website, is that the AJAX actions are given 403 ( those are used to log the download ). Did you disabled AJAX for non-logged users? 

Warmly,
Razvan

**Comment by ggortan** [comment]
These large files I have uploaded using ftp and added to DM using URL, I don't know if this has impact on getting the file size.

About the ajax requests on wp-admin.php I've got the same 403, maybe Wordfence or some firewall is blocking the requests. Need to investigate.

**Comment by razvanaldea89** [comment]
Size fetching should not be a problem regardless of the way the files have been uploaded.

Regarding the ajax request, if it gives 403 the result will be that the download won't be counted, so the download counter won't increment. Could you find a way to allow those requests?

**Comment by ggortan** [comment]
I've updated the custom template file that I was using and the ajax request was fixed.

**Comment by razvanaldea89** [comment]
Awesome :D so the logging works now, is that correct? The download count increases?

**Comment by ggortan** [comment]
Yes it's counting correct now with no console error. Just a php error about cookies that I've already seen reported on WordPress .org support forum of the plugin.

Thanks for your time.
