### ISSUE TITLE
Global use XHR, not only links with .download-link or .downlod-button

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1098]
**Describe the bug**
If search is used for example and links don't have the corresponding classes that will trigger the XHR download process the download will go with the classic process. We should globally activate the XHR, maybe with some URL query args to suggest that XHR needs to be done.

**To Reproduce**
1. Go and search for a Download
2. Click the link and download, you'll see it's the classic download process

**Expected behavior**
Should trigger the XHR process

@TeoAlex @giucu91 @cristianraiber any thoughts or improvements/suggestions/other ways to handle this?

**Comment by razvanaldea89** [comment]
This one is in close relation with https://github.com/WPChill/download-monitor/issues/1099, as we need XHR download to log location in searches and other custom queries.

**Comment by razvanaldea89** [comment]
Maybe filter the content with the hook `the_content` and add a parameter to the link so that we know it's a DLM's link

**Comment by TeoAlex** [comment]
Adding query args to the URLs will make them longer and uglyer.
Filtering with the hook `the_content` i think will be a huuge load for big pages and this has to be done on pages that don't have DLM shortcodes too.
