### ISSUE TITLE
Reconsider Download's post meta _download_count role into total download count 

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1105]
**Describe the bug**
Recreate the total download count based on meta and logs/new dlm_downloads table.

**Comment by ggortan** [comment]
I manually updated the new downloads table with the correct count. Will the update to version 4.7.3 recount the old metadata? Will this double my download count?

**Comment by ggortan** [comment]
Indeed the old post-meta counts where added into consideration. I have set all the key_value to 0 for _download_count meta_key because I previously added the old download count to the new table manually

**Comment by razvanaldea89** [comment]
Hello @ggortan ,

You are right, it does double them. We have build a plugin to take care of the migration of download counts ( w.org/plugins/download-monitor-migrate-download-counts ) so that in the end it will display the correct number, but seems you've already taken care of that :D 

Have a wonderful day!
Razvan
