### ISSUE TITLE
increase the number of points of the plot

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#1115]
**Is your feature request related to a problem? Please describe.**
On the report page: is there any way to increase the number of samples of the plot? If I well remember in the previous version the plot had a finer resolution.
I was referring to the plot representing the download trend over a given period of time. I noticed that there are a limited number of points in the plot, each of which is associated with a subrange of the considered time frame. In the previous version I think this plot was more detailed (it was made of many more points, in other words). Is it possible to increase the number of points?

More detailed graphic 

https://secure.helpscout.net/conversation/2047882948/50961?folderId=4656047

**Comment by cristianraiber** [comment]
We've never had this in the past.

**Comment by razvanaldea89** [comment]
@cristianraiber think the user is referring to version 4.6.0 and earlier where we did not implement the interest points in:
 - daily for < 7 days
 - double days for < 30 days
 - weekly for < 2 months
 and so on.
 
With this implementation we avoid the possibility of overpopulating the chart and decreasing reports performance.

**Comment by cristianraiber** [comment]
@razvanaldea89 - can we close this?

**Comment by razvanaldea89** [comment]
Sure we can
