### ISSUE TITLE
cURL problem

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1129]
**Describe the bug**
Seems there are some problems with the way we check for the robots file, but not sure if it's because of localhost or not. @TeoAlex  please give a look at this when you have time

**To Reproduce**
1.  Install Query Monitor and Download Monitor
2. Go to settings and the error should be displayed by Query Monitor. Think you have to enable SSL

**Screenshots**
![image](https://user-images.githubusercontent.com/44024114/201746505-03076814-0ac4-43e4-b8b9-0f5f4f050f4b.png)

**Extensions installed and activated:**
- [ ] Advanced Access Manager
- [ ] Amazon S3
- [ ] Buttons
- [ ] Captcha
- [ ] CSV Exporter
- [ ] CSV Importer
- [ ] Downloading Page
- [ ] Email lock
- [ ] Email Notifications
- [ ] Google Drive
- [ ] Gravity Forms
- [ ] Mailchimp
- [ ] Ninja Forms
- [ ] Page Addon
- [ ] Terms & Conditions
- [ ] Twitter Lock

**Additional context**

**Comment by TeoAlex** [comment]
Seems to be a self signed SSL on localhosts problem. Works on http locals and https with authorized certificates.
