### ISSUE TITLE
Maybe add button action description in a tooltip 

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1132]
**Describe the bug**
https://wordpress.org/support/topic/dlm-protect-file/#post-16205488

@cristianraiber @giucu91 @TeoAlex the user has a point, it's a long text and on small screens it's a bit annoying. Maybe we can add it to a tool-tip or maybe @incredibeary can come with an idea.

**Comment by mplusb** [comment]
Or just move it UNDER the image settings, like that, it will be less annoying ^^ - by the user

**Comment by razvanaldea89** [comment]
If still a problem, as we don't know exactly what priorities do other plugins have we'll rethink the solution.
