### ISSUE TITLE
Files with empty space don't redirect correctly

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1134]
**Describe the bug**
If a file has white space in its name then the redirect to it will go wrong, as in encodes the empty space with `+` and will give 404 not found.

**To Reproduce**
1. Go to Download and add a file with empty space in it
2. Copy the download link and paste it in browser ( non-XHR needed )
3. See error

**Expected behavior**
Should go to corresponding file.

**Comment by beatricelucaci** [comment]
https://secure.helpscout.net/conversation/2062691550/51500/ more info here
