### ISSUE TITLE
Should we limit the size and or align Shortcode & Download Link quick copy buttons in admin table?

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/download-monitor#1152]
Original:
![image](https://user-images.githubusercontent.com/19348508/207005549-d45895a4-8be4-4e0d-a27a-03bc2f481ab6.png)

1. limit the column's width. 7em here:
![image](https://user-images.githubusercontent.com/19348508/207004287-f31f8911-8af7-4288-b845-33f8a486ee0a.png)

2.  1.+ vertycal align: middle
![image](https://user-images.githubusercontent.com/19348508/207004787-fa1b4fa2-30bb-420b-b069-ac1eb8c85e8e.png)

3.  1.+ 2. + center alignment
![image](https://user-images.githubusercontent.com/19348508/207004910-b1c0d5b5-0667-45bf-a100-d450cf7da5e2.png)

@cristianraiber @giucu91 @razvanaldea89 ?

**Comment by incredibeary** [comment]
Eu votez cu varianta 3.

**Comment by razvanaldea89** [comment]
The original in my opinion, let WordPress do its things.

**Comment by cristianraiber** [comment]
v3

**Comment by razvanaldea89** [comment]
If it will be decided to go with v3 why not center all the items? In the image the buttons are lower than the text.

![image](https://user-images.githubusercontent.com/44024114/207101968-b392f50e-1a66-4cdd-b5f6-563b212d67be.png)

**Comment by cristianraiber** [comment]
Vertically center all the thingsss
