### ISSUE TITLE
 'Insert Download' button available to users that do not have access to downloads

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#1164]
**Describe the bug**

if 'manage_downloads' is disabled for a user, they still see the 'Insert Download' button - BUT they can only select an existing entry. If they select Quick-add download and try to upload a new document they get a message saying 'Please wait...' and it just hangs, no error message!

Please fix! I think this is actually a bug ... the Insert Download button shouldn't be available if users don't have the capability to add Downloads from the menu.

<img width="1070" alt="Screenshot 2022-12-22 at 11 05 21" src="https://user-images.githubusercontent.com/26008574/209098423-f7e41457-fe4e-4e98-b29b-6f89101ab434.png">

**To Reproduce**
1. install classic editor
2. use an user that does not have access to downloads (editor for example)
3. edit a page > click the insert download button > quick add download
4. See issue

**Additional context**
https://secure.helpscout.net/conversation/2104417981/52933?folderId=4638445

**Comment by cristianraiber** [comment]
Note: we should deprecate the Classic Editor. https://www.bluehost.com/blog/wordpress-extending-classic-editor-support-until-2022/#:~:text=WordPress%20has%20decided%20to%20continue%20support%20for%20its%20Classic%20Editor%20plugin%20into%202022.%20This%20extension%20means%20an%20additional%20year%20of%20official%20support%20for%20the%20plugin.
