### ISSUE TITLE
 “Top downloads” panel not easy to read

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#1167]
**Describe the bug**
Two issues with the “Top downloads” panel on the dashboard:

In case the title of the download is long, the presentation is shifted. it would be easier to read if the title went over several lines without interfering with the order number or the number of downloads (i.e. use a 3-column table-like layout).

These problems appeared with version 4.6.

**To Reproduce**
1. add downloads with large titles and different download count sizes
2. See error

https://wordpress.org/support/topic/top-downloads-panel-not-easy-to-read/

**Extensions installed and activated:**
- [ ] Advanced Access Manager
- [ ] Amazon S3
- [ ] Buttons
- [ ] Captcha
- [ ] CSV Exporter
- [ ] CSV Importer
- [ ] Downloading Page
- [ ] Email lock
- [ ] Email Notifications
- [ ] Google Drive
- [ ] Gravity Forms
- [ ] Mailchimp
- [ ] Ninja Forms
- [ ] Page Addon
- [ ] Terms & Conditions
- [ ] Twitter Lock

**Additional context**

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/209810107-e9c3deb0-0b3a-454d-b5a0-1d4dcfddc2f1.png)

**Comment by cristianraiber** [comment]
tagging @incredibeary - we need a better design for this

**Comment by mplusb** [comment]
+ issue with the background color not displaying correctly

For the background problem, I did the test locally by disabling all other extensions and using the default WordPress theme.
    It does not change anything because the problem is not related to a conflict but to the size of the title: it does not occur when the title of the download is smaller than the desired colored area (with a margin of approximately 20px in addition).

**Comment by razvanaldea89** [comment]
Similar / Duplicate #1170

**Comment by razvanaldea89** [comment]
Seems to still happen on smaller screens.

**Comment by incredibeary** [comment]
![Top Downloads new dsgn](https://user-images.githubusercontent.com/112502248/218676565-568c92c9-5687-478a-880b-ef8d3ea8c1a4.png)
