### ISSUE TITLE
Add a x-dlm-filename header containing the file name so that it won't be trimmed out

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1183]
**Describe the bug**
Some servers/plugins modify/trim out the content-disposition header and we end up with files that do not have names or JS errors when trying to download the files. Adding a custom header and managing the file name based on that will stop the bug from happening.

**Comment by 6th-avenue** [comment]
Hi Razvan!
Thanks for getting this bug in.
For some more background information; my client wanted the download (a PDF file) to get shown to the end-user within the browser. So with help of the DLM filter $headers = 'dlm_download_headers', the approach was to set the Content-Disposition to 'inline'.
We now realized that basically also cuts-out the original filename.
I will run some tests to see if I just change 'attachment' into 'inline' and leaving the filename intact, if the browser still recognizes this header setup and the DLM js script won't fail.
I agree that added your own header will completely bypass this caveat completely. 

I hope you have time to get this in.

Thanks,
Ruud

**Comment by 6th-avenue** [comment]
Hi Razvan,

My test with the combined 'inline' and filename approach did not work. 
I also tried adding the dlm-file-name header, which I saw used in some places of the code, but that did not help either.
Hope you can fix this bug/feature.
Thanks!

**Comment by razvanaldea89** [comment]
Thank you for the feedback Ruud. Most probably in the next update or two this will be implemented.

Have a wonderful day!
Razvan
