### ISSUE TITLE
option to remove loading icon on button template

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#1193]
<img width="940" alt="Screenshot 2023-01-19 at 11 10 50" src="https://user-images.githubusercontent.com/26008574/213401649-b9d7714b-a079-4b41-b377-0e5b9e0b507f.png">

user wants an option to remove loading icon.
especially for DLM pages and custom templates for download links and buttons.Please find a solution to remove this feature. Especially if not wanted. Or at least provide documentation to hide it via CSS (Even though I had to do it myself).  

https://secure.helpscout.net/conversation/2127106727/53595?folderId=4638445

**Comment by razvanaldea89** [comment]
Similar with #1213 . Going to close this, progress indicator will be removed with filter.
