### ISSUE TITLE
Add decimals to formatted file size

### ISSUE THREAD

**Issue by ggortan** [WPChill/download-monitor#1204]
**Describe the solution you'd like**
Add decimals to formatted file size for a more real size notion like in cases where the formatted file size returns 1 GB can be 1,01 GB or 1,99GB .

**Describe alternatives you've considered**
Return the value with decimals.

**Additional context**
![image](https://user-images.githubusercontent.com/7429130/215937387-3a94a9f4-b4ea-456a-bdf0-29e8569cca77.png)

**Comment by cristianraiber** [comment]
cc @razvanaldea89 - can we add this to our next release?
