### ISSUE TITLE
Develop DLM's REST API endpoints

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1215]
**Is your feature request related to a problem? Please describe.**
We should develop REST API endpoints with which users can automatically create/update Downloads & Versions

https://wordpress.org/support/topic/batch-create-downloads-from-script/

**Comment by gwegner** [comment]
Thank you!

**Comment by IlanVivanco** [comment]
I have created a plugin in the past to sort this out. It's just a matter of creating the WP endpoints and using the DLM methods already available.

**Comment by IlanVivanco** [comment]
I have created a plugin in the past to sort this out. It's just a matter of creating the WP endpoints and using a few DLM methods already available.

**Comment by cristianraiber** [comment]
@IlanVivanco - is this plugin public?

**Comment by IlanVivanco** [comment]
Nope, but I can review it —and remove anything sensitive— and publish it for you to fork it.

**Comment by cristianraiber** [comment]
@IlanVivanco - yes, please :) That would help

**Comment by beatricelucaci** [comment]
+1 https://support.wpchill.com/conversation/8735?folder_id=95

**Comment by razvanaldea89** [comment]
https://github.com/IlanVivanco/download-monitor-rest

**Comment by razvanaldea89** [comment]
For the API Keys functionality and menu entry, we should add an option to enable it, so that regular users of DLM won't have an extra menu item that complicates things if they do not need it.

**Comment by razvanaldea89** [comment]
API Keys page should not be a menu page, but a section in Settings > Misc, that is hidden until the user enables it with a filter.
