### ISSUE TITLE
Undefined property error disrupting dashboard view

### ISSUE THREAD

**Issue by snapey** [WPChill/download-monitor#1250]
**Describe the bug**
On loading the admin dashboard, the screen presents 5 lines of;

Warning: Undefined property: stdClass::$product_id in {site name here}/public_html/wp-content/plugins/download-monitor/src/Admin/Extensions.php on line 233

followed by 3 lines of Warning: `Cannot modify header information `

**To Reproduce**
Messages appear on dashboard

**Expected behavior**
No warning messages

**Extensions installed and activated:**
- [ ] Advanced Access Manager
- [ ] Amazon S3
- [ ] Buttons
- [ ] Captcha
- [ ] CSV Exporter
- [ ] CSV Importer
- [ ] Downloading Page
- [ ] Email lock
- [ ] Email Notifications
- [ ] Google Drive
- [ ] Gravity Forms
- [ ] Mailchimp
- [ ] Ninja Forms
- [ ] Page Addon
- [ ] Terms & Conditions
- [ ] Twitter Lock

**Additional context**

Plugin is at version 4.7.78
Wordpress 6.2
PHP 8.0.25

### wp-core ###

version: 6.2
site_language: en_GB
user_language: en_GB
timezone: Europe/London
permalink: /%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 25
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/sites/{site name here}/public_html
wordpress_size: 361.45 MB (379010759 bytes)
uploads_path: /home/sites/{site name here}/public_html/wp-content/uploads
uploads_size: 1.01 GB (1085756168 bytes)
themes_path: /home/sites/{site name here}/public_html/wp-content/themes
themes_size: 4.81 MB (5040817 bytes)
plugins_path: /home/sites/{site name here}/public_html/wp-content/plugins
plugins_size: 85.29 MB (89432591 bytes)
database_size: 94.74 MB (99343994 bytes)
total_size: 1.54 GB (1658584329 bytes)

### wp-active-theme ###

name: Pena (pena)
version: 1.1.9
author: Anariel Design
author_website: https://www.anarieldesign.com/
parent_theme: none
theme_features: core-block-patterns, woocommerce, widgets-block-editor, automatic-feed-links, post-thumbnails, custom-logo, title-tag, editor-style, menus, html5, custom-background, wp-block-styles, align-wide, editor-color-palette, custom-header, jetpack-responsive-videos, widgets
theme_path: /home/sites/{site name here}/public_html/wp-content/themes/pena
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty-Three: version: 1.1, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (15) ###

All in One SEO: version: 4.3.4.1, author: All in One SEO Team, Auto-updates disabled
Contact Form 7: version: 5.7.5.1, author: Takayuki Miyoshi, Auto-updates disabled
Download Monitor: version: 4.7.78, author: WPChill, Auto-updates disabled
GT3 Photo & Video Gallery - Lite: version: 2.7.7.16, author: GT3 Photo Gallery, Auto-updates disabled
Login No Captcha reCAPTCHA (Google): version: 1.7.1, author: Robert Peake and Contributors, Auto-updates disabled
Page Builder by SiteOrigin: version: 2.20.6, author: SiteOrigin, Auto-updates disabled
Pena Custom Widgets for SiteOrigin Page Builder Plugin: version: 1.0, author: Anariel Design, Auto-updates disabled
ReCaptcha v2 for Contact Form 7: version: 1.4.3, author: IQComputing, Auto-updates disabled
Responsive WordPress Slider - Soliloquy Lite: version: 2.7.2, author: Soliloquy Team, Auto-updates disabled
Simple Membership Google recaptcha: version: v1.9, author: smp7, wp.insider, Auto-updates disabled
Simple WordPress Membership: version: 4.3.1, author: smp7, wp.insider, Auto-updates disabled
SiteOrigin Widgets Bundle: version: 1.47.0, author: SiteOrigin (latest version: 1.47.1), Auto-updates disabled
TablePress: version: 2.1, author: Tobias Bäthge, Auto-updates disabled
The Events Calendar: version: 6.0.11, author: The Events Calendar, Auto-updates disabled
Widget Visibility Without Jetpack: version: 1.2, author: Joan Boluda, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 2M
max_effective_size: 2 MB
max_file_uploads: 20
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 4.18.0-425.13.1.el8_7.x86_64 x86_64
httpd_software: Apache
php_version: 8.0.25 64bit
php_sapi: cgi-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 512M
max_input_time: -1
upload_max_filesize: 2M
php_post_max_size: 8M
curl_version: 7.61.1 OpenSSL/1.1.1k
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.1.48-MariaDB
client_version: mysqlnd 8.0.25
max_allowed_packet: 67108864
max_connections: 1024

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/sites/{site name here}/public_html/wp-content
WP_PLUGIN_DIR: /home/sites/{site name here}/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 512M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### aioseo (1) ###

noindexed: Search Page

**Comment by razvanaldea89** [comment]
Please go to dashboard > Downloads > Extensions and click the "Reload extensions" button and should be fixed.

Warmly,
Razvan
