### ISSUE TITLE
downloaded file name in response headers

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#1253]
**Describe the bug**
Hi, I think I found a bug in version 4.7.78 on Chrome. Basically, in file dlm-xhr.js when you look for downloaded file name in response headers, there is a fallback function (line 208 and on in uncompressed file) that reads header "content-disposition" and splits by "filename=" to get filename I have a wordpress website where, only in Chrome, the "content-disposition" header looks different, like: ...filename*=UTF-8''my-file-name.xls; instead of ...filename=my-file-name.xls;

 I'd like you to investigate further this problem and maybe include this fix on next release I fixed this way: 

if( 'undefined' == typeof file_name ){ file_name = responseHeaders['content-disposition'].split("filename*=UTF-8''")[1]; buttonObj.find('.dlm-xhr-loading-gif').remove(); } (after the "split" instruction to get file_name)

**Extensions installed and activated:**
- [ ] Advanced Access Manager
- [ ] Amazon S3
- [ ] Buttons
- [ ] Captcha
- [ ] CSV Exporter
- [ ] CSV Importer
- [ ] Downloading Page
- [ ] Email lock
- [ ] Email Notifications
- [ ] Google Drive
- [ ] Gravity Forms
- [ ] Mailchimp
- [ ] Ninja Forms
- [ ] Page Addon
- [ ] Terms & Conditions
- [ ] Twitter Lock

**Additional context**
https://secure.helpscout.net/conversation/2219064489/56431?folderId=4638445

**Comment by razvanaldea89** [comment]
https://github.com/WPChill/download-monitor/issues/1260
