### ISSUE TITLE
Option to disable file browser in wp-config.php

### ISSUE THREAD

**Issue by acesuares** [WPChill/download-monitor#1259]
Referring to https://github.com/WPChill/download-monitor/issues/469 
Disabling the file browser in settings is nice but for a multisite it would be maybe better to disable file browsing in wp_config.

A similar (but hard to find) option is implemented in another download plugin, see https://www.wpdownloadmanager.com/support/topic/how-to-disable-asset-manager/

At the moment, comment out the line 269 in src/Admin/WritePanels.php

**Comment by TeoAlex** [comment]
added support for `DLM_DISABLE_FILE_BROWSER` global variable. This can be used to suppress "Disable file browser" setting.

adding `define('DLM_DISABLE_FILE_BROWSER', true );` in wp-config.php will disable the file browser.

**Comment by razvanaldea89** [comment]
Global variable is renamed to `DLM_FILE_BROWSER`

**Comment by acesuares** [comment]
Hi there, I tried, with version 4.9.3, seems to do nothing.

```
# https://github.com/WPChill/download-monitor/issues/1259
define('DLM_DISABLE_FILE_BROWSER', true );
```
Also tried DLM_FILE_BROWSER but the 'browse file' button is still there.

**Comment by razvanaldea89** [comment]
Works as expected. Quick info: to turn the browser off you need to set it to false, like so
`define( 'DLM_FILE_BROWSER', false );`

**Comment by acesuares** [comment]
Thanks for the quick answer! Do I have the wrong version maybe (4.9.3). I have the define in the config file and the button is still there. See screenshot.
![Screenshot from 2024-01-15 06-46-24](https://github.com/WPChill/download-monitor/assets/2784/a2838949-220f-437b-9419-5c3849c82b7c)

**Comment by razvanaldea89** [comment]
Could you please show me how you defined the constant in the wp-config.php file?

**Comment by acesuares** [comment]
Sure! 
![Screenshot from 2024-01-15 07-30-22](https://github.com/WPChill/download-monitor/assets/2784/b102e5a7-f4d0-49df-8514-b4f05276378b)

**Comment by razvanaldea89** [comment]
OK, I've managed to replicate the issue. Seems like if it's a new Download, before you publish it, it shows the explore button. After you publish the Download the button disappears. Could you please confirm this scenario? Will look into this and will try to add the fix in the 4.9.6 update.

**Comment by acesuares** [comment]
Files with an ~ at the end, like wp-config.php~ can be uploaded via the file browser.
![Screenshot from 2024-01-15 08-35-13](https://github.com/WPChill/download-monitor/assets/2784/1745f285-f62b-4068-b6e6-d479e49cb2df)

**Comment by acesuares** [comment]
Also, when changing the 'other path' in settings to /etc, it's easy to upload /etc/sysctl.conf  via custom url, as an example
Maybe consider this as a security issue? Please advice.

**Comment by razvanaldea89** [comment]
We restrict files with the .php extension. Also, you can add your own extensions that can be restricted using the following filter:
https://github.com/WPChill/download-monitor/blob/master/src/FileManager.php#L381

This way you can have more control on which types of files are allowed to be downloaded. 

Also, the following files are restricted by default: wp-config.php, .htaccess & php.ini. You can also add more files using the following filter:
https://github.com/WPChill/download-monitor/blob/master/src/FileManager.php#L412

Yes, you can add all the files with whatever extension you want if they are not .php or not in the custom array defined by you and they are defined in the allowed paths. By default, the allowed paths are the WordPress installation path and the wp-content folder path. Whatever is outside these directories won't be allowed to be downloaded.

Most users don't need to alter the "Other downloads" path, but some environments symlink or move the wp-content directory, or users upload files in certain directories. Pantheon for example moves the user uploaded files in a `/files` directory, which is separated from the WordPress, and the "Other downloads" path requires to point to that location. Sure, if you put /etc in that option you'll be allowed to add files from that directory, but maybe you have a responsibility also on what can be downloaded ?

But I agree, we need to disallow access to certain directories that are absolutely not needed for what Download Monitor does, for example the etc directory you mentioned.

Hope this answers your questions :D

Warmly,
Razvan

**Comment by acesuares** [comment]
Yes, sure thereis a responsibility, but I see someone stealing an account and using DLM to have access to system files, or, especially in a multisite, to other peoples files. I think the path should be $BLOGSDIR (or whatever it's called) so the multisite user can not get out of it's own file storage and cannot go to others. Also, the other download part, definately would need to be disabled in multisite. Just my thoughts. What do you think. At this moment it's quite a risk, you can access any directory on the server.

**Comment by razvanaldea89** [comment]
Sure, but upon stealing the account the person who stole the account already can do whatever they want with it, that is why I mentioned the user responsibility.

Regarding the "Other downloads path", I agree with you, in a multisite installation should be disabled or related only to the directories that are dependent to their site, we'll need to take a look at it.

Going to close this issue and we'll continue the discussion in the other issues.

**Comment by razvanaldea89** [comment]
We are stepping in extremes here. In your opinion, if someone steals the account and doesn't find DLM, that person will say: "Oh no! No DLM! Well, I'm going to leave without doing anything.", which I honestly don't think so. I don't mean to sound rude or disrespectful, but if someone goes the effort to steal an account surely that person has the means to do harm without DLM.

As I said before, I 100% agree with you that we should limit access to sensitive directories and prevent, on multisite, access to others' files.

**Comment by acesuares** [comment]
In 4.9.11 when disabling the file browser, now the 'browse' button is not there when adding a new document. Thank you!
However, choosing /etc/ as special path, it's still possible to upload files from /etc/.

**Comment by acesuares** [comment]
Great! Thanks! Very useful plugin, otherwise!
