### ISSUE TITLE
Add possibility to remove dlm-version meta

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1267]
https://wordpress.org/support/topic/remove-dlm-version-meta-tag/

**Comment by razvanaldea89** [comment]
@TeoAlex think this one was already implemented. Please have a look.

**Comment by TeoAlex** [comment]
Allready implemented. Use `add_filter( 'dlm_hide_meta_version', '__return_true' );` to hide dlm-version meta
