### ISSUE TITLE
Add filter to remove dlm-version from meta

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1269]
**Is your feature request related to a problem? Please describe.**
Add a filter to remove the meta dlm-version set in the header.

**Comment by ianpegg** [comment]
For anyone who wants to use this feature, the filter name is: dlm_hide_meta_version and [the code can be found in download-monitor.php](https://github.com/WPChill/download-monitor/commit/e02c905dd249937e04969c8376ee45ebd98ba323)
