### ISSUE TITLE
Set request/response Cache-Control headers

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1272]
**Is your feature request related to a problem? Please describe.**
We should set request/response Cache-Control headers in order to minify the error possibility when trying to download a file from a server/website that uses cache.

**Comment by razvanaldea89** [comment]
@TeoAlex think this one was already implemented. Please look in the DownloadHandler.php and dlm-xhr.js files.

**Comment by TeoAlex** [comment]
Added here https://github.com/WPChill/download-monitor/commit/0c80b6ea515eb23e74555420268ce865e5506d96
