### ISSUE TITLE
LiteSpeed server doesn't do the X-Accel-Redirect / X-Sendfile option

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1282]
**Describe the bug**
Downloading big files stops at server limitation ( if server has limitation for max file request ) if special header is not defined, so by using the special header `X-LiteSpeed-Location` it will bypass the limit and server the entire file. This will conflict with XHR download.

**Comment by razvanaldea89** [comment]
Add a notice/warning that activating that option will disable the XHR

**Comment by QuantSparkTechnology** [comment]
It's my understanding that now the download count doesn't update the count. I've downgraded to Version 4.8.4 and it's counting okay again (animation is also back). Just to let you know. Using LightSpeed as well.

**Comment by razvanaldea89** [comment]
You are completely right, we are going to address this in our next update which will next week, most probably on Monday.

**Comment by QuantSparkTechnology** [comment]
Thank You!
