### ISSUE TITLE
Check custom tables of columns and alter them if non-existing

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1288]
**Describe the bug**
We need to check if the custom tables have all the columns needed, else when trying to add logs to them it will trigger an error and entries won't be added.

**To Reproduce**
1. Delete a column from download_log table and download a file
2. See reports if entry was added

**Comment by TeoAlex** [comment]
dbDelta() according to [this documentation](https://codex.wordpress.org/Creating_Tables_with_Plugins#Creating_or_Updating_the_Table) checks and creates/updates the tables and so adding "IF NOT EXISTS" actually breaks the verification part.
