### ISSUE TITLE
sql problem with very big databases

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#1291]
**Describe the bug**

We Using your Plugin from last two years. resently we update our php 7.4 to 8.0. now your plugin make query in sql. then Server get load and site getting crash. We use full dedicated server (128ram Hexa Core - Advance 3 ) in ovh with Custom Setup.

We found the issue with the site, There was a bug fix in the version 4.7.4 that caused us the issue. As we checked, bug fix #1126 has inner joins to query with subqueries, The reason being the meta database being large generates a derived table with no index clogging the server, as the query takes time to execute. If you can optimize and fix the same it would be great.

The user has 20000 downloads, the database is big  and he has a lot of things in the postmeta  

https://secure.helpscout.net/conversation/2277475713/57934?folderId=4656047

**Comment by razvanaldea89** [comment]
This should be solved starting with version 5.0.0. Going to close this.
