### ISSUE TITLE
improve reports page

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#1313]
**Is your feature request related to a problem? Please describe.**
slow load

**Describe the solution you'd like**
Hey, Just wanted to pass along something along for your consideration. Looks like the user report (/wp-admin/edit.php?post_type=dlm_download&page=download-monitor-reports) is loading a select menu with every user on our site, which as of right now is 25,182. This is not only making the report super, super slow, but also a UX nightmare when we need to find a user. You can see it's taking about 3 seconds for each request, and the report will not render until the process is done. I would recommend implementing some sort of search as you type field that retrieves users based on the input. It's pretty much unusable as-is. 
(screenshot in ticket below)
https://secure.helpscout.net/conversation/2315429412/58703/

**Comment by cristianraiber** [comment]
cc @razvanaldea89
