### ISSUE TITLE
Add possibility to disable the No Access Modal on mobile

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1333]
**Is your feature request related to a problem? Please describe.**
We should add a filter to allow the No Access Modal functionality to be disabled on Mobile. We should make a helper method or something in order for it to be reused in extensions also.

**Comment by TeoAlex** [comment]
We allready have a filter to disable No Access Modal. 
Use the following code in your theme's functions.php file to disable Access Modal only for mobile.

`add_filter( 'do_dlm_xhr_access_modal', 'dlm_access_modal_disable_mobile' );

function dlm_access_modal_disable_mobile( $access_modal ){
	if( ! $access_modal || wp_is_mobile() ){
		return false;
	}
	return $access_modal;
}`
