### ISSUE TITLE
Add tailwind css

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1335]

**Comment by TeoAlex** [comment]
https://github.com/WPChill/download-monitor/commit/3d90d636dfebf47c66095a011885dc1081a58b33
https://github.com/WPChill/download-monitor/commit/f0e96103fd97766b834e766b4e1a0a2493862e1e
https://github.com/WPChill/download-monitor/commit/794960df17e2694becfb67021c0fa8a2973c366f
https://github.com/WPChill/download-monitor/commit/58b4a4f7aea363c91a3a909832dfd6fc17bff92b
https://github.com/WPChill/download-monitor/commit/b274f6a2f733c49a4b4b78f91dbcf71f7eaf3b11
