### ISSUE TITLE
General settings section update

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/download-monitor#1346]
- [x] include in search mutat in Adavanced -> Pages Setup
- [x] eliminat x-accel
- [x] eliminat allow proxy override
- [x] eliminat prevent hotlinking (ascunsa doar setarea, pe moment sa vedem daca se plange careva c-a disparut; nu-mi e 100% clar in ce use case asta ar fi utila/necesara)
- [ ] eliminat template-urile (nu le mai afisam acel select in frontend); trebuie gandita aici o varianta prin care, pe viitor, sa le dam posibilitatea sa-si customizeze design-ul ala dar prin Gberg

**Comment by razvanaldea89** [comment]
![image](https://github.com/WPChill/download-monitor/assets/44024114/786ffdb4-e9fb-424b-93cb-f0534f12e553)

Endpoint & Endpoint value should be set in General. Also, the "Include in search" should be set here as it's a more general setting than an advanced one.

**Comment by giucu91** [comment]
@TeoAlex  @razvanaldea89 what is the reason why we eliminate the template settings ?

**Comment by razvanaldea89** [comment]
Probably to get rid of some settings from these areas as the template can be selected with the Gutenberg block or a shortcode param.

**Comment by razvanaldea89** [comment]
Templates won't be eliminated, what we'll do is a functionality similar with what WooCommerce does with its templates and add notices if the templates used are experied/need update.

**Comment by cristianraiber** [comment]
- Include in search nu s-a mutat

**Comment by razvanaldea89** [comment]
Nu s-a mutat pe baza unei discutii avute cu tine

**Comment by cristianraiber** [comment]
Looks good based on code
