### ISSUE TITLE
Shop settings section update

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/download-monitor#1347]
- [x] Settings (redenumit in General)
- [x] Disable cart -> langa toggle-ul de on/off, am label "Disable"; n-are ce sa caute aceste label acolo\
- [x] Pages ar trebui merge-uit cu "General"
- [x] Payment Overview -> redenumit in "Payment Gateways"

**Comment by razvanaldea89** [comment]
New configuration:
![image](https://github.com/WPChill/download-monitor/assets/44024114/5fa62573-947e-4329-bdf6-af686f0cd0d3)

![image](https://github.com/WPChill/download-monitor/assets/44024114/d228e210-a726-4068-827b-e126a8172041)

**Comment by TeoAlex** [comment]
Also:

- [ ] Check and add [dlm_cart] shortcode on selected Cart page if it doesn not exist.
- [ ] Check and add [dlm_checkout] shortcode on selected Checkout page if it doesn not exist.

**Comment by razvanaldea89** [comment]
Pre-loading shortcodes on pages should be done by attaching to the `dlm_preload_shortcodes` filter hook and defining option and shortcode to be placed.

**Comment by cristianraiber** [comment]
![CleanShot 2024-01-12 at 14 31 33](https://github.com/WPChill/download-monitor/assets/7841556/dc60c493-b40f-44f2-84ae-6454497eaaa3)


---

Invoice prefix ar trebui mutat in Shop Settings

**Comment by cristianraiber** [comment]
Looks good.
