### ISSUE TITLE
Advanced settings section update

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/download-monitor#1348]
- [x] Pages Setup (redenumit in Pages)
- [x] No Access page -> atunci cand se alege o pagina, se verifica si daca exista shortcode-ul in content-ului, daca nu exista, se adauga automat
- [x] Search -> Page Addon Page -> la fel, se pune shortcode-ul automat. Daca toggle-ul e pe OFF, aceasta setare trebuie sa fie greyed out sau ascunsa. 
- [x] Hashes -> dispare

Reports 

- [x] 	- ignore admin count -> ON by default; fara setare ... e pur si simplu ON by default
- [x] 	- count unique IPs only -> apare doar daca Store full IP address e ales
- [x] 	- user agent logging -> on by default; fara setare ... e pur si simplu ON by default

 Misc

- [x] - clear all transients -> gone (exista plugin pt. transienti)
- [x] - recreate upgrade -> gone; s-a facut migrarea de mult

**Comment by razvanaldea89** [comment]
@cristianraiber @giucu91 should we remove hashes completely or leave them as is and enable them from filters?

**Comment by cristianraiber** [comment]
You can re-enable them from your plugin. Remove the UI from the main plugin for now.

**Comment by razvanaldea89** [comment]
@cristianraiber regarding the `Search -> Page Addon Page -> la fel, se pune shortcode-ul automat. Daca toggle-ul e pe OFF, aceasta setare trebuie sa fie greyed out sau ascunsa.` modification, I don't think that we should hide the setting if the "Include in search" toggle is on OFF, as this is a different search.

**Comment by cristianraiber** [comment]
ok
