### ISSUE TITLE
If on localhost or staging, we shouldn't take into account the 60s window for unique downloads

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#1350]
on "live" urls, this 60s window should be set by default, with a filter to change it if anyone ever asks about it.

**Comment by razvanaldea89** [comment]
@cristianraiber @giucu91 should we make backwards compatibility functionality or will this be as is by default and if people complain we shall give them the required PHP snippet?

**Comment by cristianraiber** [comment]
option 2

**Comment by razvanaldea89** [comment]
OK, I'll leave the PHP snippet here:

- turn on the 60 seconds window:
`add_filter( 'dlm_no_duplicate_download', '__return_true', 15 );`
- turn off the 60 seconds window:
`add_filter( 'dlm_no_duplicate_download', '__return_false', 15 );`

**Comment by cristianraiber** [comment]
Looks good from code
