### ISSUE TITLE
featured image displayed next to each download in the admin downloads list

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#1351]
**Describe the solution you'd like**
I have purchased the full version of Download monitor but I cant seem to find a way of displaying the featured image on each download in the admin list - Its just so we can tell which downloads have featured images.

https://support.wpchill.com/conversation/5655?folder_id=93

**Comment by giucu91** [comment]
Add the image in the admin list and the option to add or removed it from the screen options: 

<img width="1423" alt="image" src="https://github.com/WPChill/download-monitor/assets/7580330/1db5a331-9cf3-47fc-95fb-0163ddaa53dc">

for the downloads that don't have a picture we should put a imnage placeholder like woo
<img width="1445" alt="image" src="https://github.com/WPChill/download-monitor/assets/7580330/c94a4450-f81f-4f42-9add-31e7dde6082f">
