### ISSUE TITLE
a hook to prevent "Insert Download" appearing in wysiwyg editor

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#1356]
Hello. I would like to request that a hook be added into your plugin to prevent the "Insert Download" button from appearing with the wysiwyg editor. I've solved this with a little CSS for now but the ability to prevent the button from being added would be great please! Thank you :)

https://support.wpchill.com/conversation/6152?folder_id=93

**Comment by TeoAlex** [comment]
Copy and Paste the following code in the ( child ) theme's functions.php file to hide the "Insert Download" button in classic editor.
`// Hides DLM's "Insert Download" button in Classic Editor ( wysiwyg editor ).
add_filter( 'dlm_hide_insert_download_classic_editor', '__return_true' );`
