### ISSUE TITLE
Remove nonce from WP set REST Endpoint 

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1383]
**Describe the bug**
Remove the nonce from the WP set REST Endpoint and let it be handled by WP itself, as in certain situations may cause Bad Gateways ( https://github.com/WPChill/download-monitor/blob/master/src/Admin/Reports/class-dlm-reports.php#L167 ). Could not reproduce on my end but tested on client's and wiping out the nonce was the solution. ( https://support.wpchill.com/conversation/8504?folder_id=153 )

**To Reproduce**

**Expected behavior**

**Screenshots**

**Extensions installed and activated:**
- [ ] Advanced Access Manager
- [ ] Amazon S3
- [ ] Buttons
- [ ] Captcha
- [ ] CSV Exporter
- [ ] CSV Importer
- [ ] Downloading Page
- [ ] Email lock
- [ ] Email Notifications
- [ ] Google Drive
- [ ] Gravity Forms
- [ ] Mailchimp
- [ ] Ninja Forms
- [ ] Page Addon
- [ ] Terms & Conditions
- [ ] Twitter Lock

**Additional context**

**Comment by cristianraiber** [comment]
Looks good from the code
