### ISSUE TITLE
Global DLM ecosystem single cookie

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1384]
**Is your feature request related to a problem? Please describe.**
We should replace the high number of cookies set by Download Monitor and its extension with a single global cookie that can be added to the whitelist/cache-busting list of hosting providers and that it holds and based on it store in the DB the required data. For example Pantheon ( https://docs.pantheon.io/cookies#cache-busting-cookies ) automatically ads cookies that start with `wp-` to the cache-busting list. A similar issue is this https://github.com/WPChill/download-monitor/issues/813, having problems with WPEngine

**Comment by razvanaldea89** [comment]
We should prefix the cookie with the `wp-` string

**Comment by cristinnaiulia** [comment]
Am testat cu mai multe extensii de lock (Ninja, Gravity Forms, Email) si merg cookie-urile, dar prefixul a ramas la fel.

![Screenshot 2024-04-30 132435](https://github.com/WPChill/download-monitor/assets/63049546/8fee7aa3-5249-4b74-9711-01e9cd48078b)

**Comment by cristinnaiulia** [comment]
![Screenshot 2024-05-23 125745](https://github.com/WPChill/download-monitor/assets/63049546/404f3411-2b4e-4c59-a8d7-d65f76cd79be)
