### ISSUE TITLE
Add a "Debug Download" meta box same as Modula

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1387]
**Is your feature request related to a problem? Please describe.**
Add a "Debug Download" meta box same as Modula so that when there are problems the user can export a CSV file with the Download's properties in order for our support team to take a look and see if there are problems with the configuration.

**Comment by TeoAlex** [comment]
[Status](https://dev.tamewp.com/wp-admin/site-health.php?tab)
[Info](https://dev.tamewp.com/wp-admin/site-health.php?tab=debug)
Fatal error: Uncaught Error: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class DLM_Debug does not have a method "dlm_debug_information"
in /home/tamewpco/dev.tamewp.com/wp-includes/class-wp-hook.php on line 324

**Comment by cristinnaiulia** [comment]
"Debug Download" meta box was added and it's working properly.
