### ISSUE TITLE
Add status tab

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1389]
**Is your feature request related to a problem? Please describe.**
Add status tab where information about Download Monitor's templates are held. Also, move fields from Miscellaneous to the new tab.

**Comment by cristianraiber** [comment]
![CleanShot 2024-01-12 at 12 18 23](https://github.com/WPChill/download-monitor/assets/7841556/fc4665f4-c469-458d-ac41-65614356ed38)

**Comment by cristianraiber** [comment]
Message when no custom templates exist needs to be reflected on this page. It should show a message with a checkmark - something along the lines of:

`None of Download Monitor's output templates are being overridden by your theme.`

**Comment by razvanaldea89** [comment]
![image](https://github.com/WPChill/download-monitor/assets/44024114/14897e71-c0e5-42fc-8d20-9e060d36697f)

**Comment by razvanaldea89** [comment]
Add edit link to edit the templates in the theme editor

**Comment by razvanaldea89** [comment]
![image](https://github.com/WPChill/download-monitor/assets/44024114/1fff4288-33b9-4ce5-8c10-bb033bf0a08b)

**Comment by cristianraiber** [comment]
Looks good.
