### ISSUE TITLE
PHP 8.2 compatibility

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#1392]
Currently, DLM does not work with PHP 8.2

https://support.wpchill.com/conversation/9252?folder_id=91

**Comment by cristianraiber** [comment]
Should add checks to Health Check

**Comment by razvanaldea89** [comment]
![image](https://github.com/WPChill/download-monitor/assets/44024114/8ce095b6-dbe4-4886-b0c6-0e80ee5174c4)
![image](https://github.com/WPChill/download-monitor/assets/44024114/fc47be73-5519-4faa-ad77-4780cb07b214)

**Comment by cristianraiber** [comment]
Move modules into Health Check (default; core) WP section

![image](https://github.com/WPChill/download-monitor/assets/7841556/910bf1d2-a84c-4571-be3f-8793be2d768f)
