### ISSUE TITLE
Admin Download edit view changes

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1398]
- Hide the Short description metabox if the active custom template doesn't have the short description functionality in it ( do it from the Screen Options ).
- Remove the Paid only checkbox if the Download has been attached to a product. Still show a visual indicator that the Download has a lock mechanism that only paying customers can download its files.
- Move the "Amazon S3 and Google Drive" upsells out from the metabox and into their own metabox, and let the Versions metabox more freely
![CleanShot 2024-01-12 at 12 49 30](https://github.com/WPChill/download-monitor/assets/44024114/69bcafb1-4cee-4373-b279-96da0a4c70e0)

**Comment by TeoAlex** [comment]
The "Amazon S3 and Google Drive" upsells are in their own metabox
![image](https://github.com/WPChill/download-monitor/assets/19348508/beb0180a-461a-42fe-ada3-a095fdc08f8e)

**Comment by cristinnaiulia** [comment]
- short description functionality was disable by default, you can enable it from screen options
- paid only checkbox was removed if the Download has been attached to a product
![Screenshot 2024-04-29 084600](https://github.com/WPChill/download-monitor/assets/63049546/db353146-d8d4-49cb-81be-5ba4dd9afb90)
- the "Amazon S3 and Google Drive" upsells are in their own metabox
