### ISSUE TITLE
Disallow access to directories that are absolutely not needed by DLM

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1401]
**Describe the bug**
Disallow access to directories that are absolutely not needed by DLM, for example the etc directory.

**Comment by acesuares** [comment]
Also, in Multisite, don't go to the root of the installation, but to the 'root' of the specific blog, if that's possible.
And it would be great to be able to all together disable the other path on multisite.

**Comment by razvanaldea89** [comment]
A filter has been added where users can add folder names which will be disallowed for file selections or download.

Filter: `dlm_restricted_admin_folders`, has a default value of empty array.

The other restrictions will be done by Approved Download Paths, which from version 5.0.0 will be multiple and will be defined by users ( defaults to the uploads path and WordPress installation path ).
