### ISSUE TITLE
have the ‘Members only’ checkbox automatically tick for any file that’s protected from the media library

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#1424]
**Is your feature request related to a problem? Please describe.**
Are you able to assist with a way to have the ‘Members only’ checkbox automatically tick for any file that’s protected from the media library?

Is there an option for this with the ‘Redirect to file’ as well?

https://support.wpchill.com/conversation/10588?folder_id=95

**Comment by razvanaldea89** [comment]
Bulk editing should be used for this.
