### ISSUE TITLE
Performance issue with large postmeta tables

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1425]

**Comment by cristinnaiulia** [comment]
I added many downloads and ran performance tests, all seems ok.

![Screenshot 2024-05-02 071642](https://github.com/WPChill/download-monitor/assets/63049546/e331bf11-6a29-48a0-bbd5-8c455f55467d)

![Screenshot 2024-05-02 071730](https://github.com/WPChill/download-monitor/assets/63049546/0209c701-0e79-4c81-808e-a78b086c6117)
