### ISSUE TITLE
Filename filetype problem

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1426]
**Describe the bug**
https://wordpress.org/support/topic/since-4-9-3-filename-template-not-showing-icon/#post-17403186

**Comment by cristinnaiulia** [comment]
![Screenshot 2024-04-29 095832](https://github.com/WPChill/download-monitor/assets/63049546/d8ddf13b-7bc7-49cf-a2a7-6b3f054ea5e7)
