### ISSUE TITLE
Date Range goes over the Export button - bug on small display 

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#1427]
**Describe the bug**
my problem with Date Range goes over the Export button appearing on a 1536 px width screen
but on 1920px it's OK. 
https://support.wpchill.com/conversation/7109?folder_id=95

**Comment by razvanaldea89** [comment]
![image](https://github.com/WPChill/download-monitor/assets/44024114/8ba508a5-2d03-4ce3-ba64-aebbd7ca51b0)
