### ISSUE TITLE
Downloads path - do something similar to what WooCommerce has

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1447]
**Is your feature request related to a problem? Please describe.**
The Other Downloads Path should be replaced with something very similar to what WooCommerce has ( install WooCommerce and go to this URL: admin.php?page=wc-settings&tab=products&section=download_urls ).

For backwards compatibility, what is already defined as other downloads path should be added as a new path in the new functionality.

**Comment by razvanaldea89** [comment]
When a file is uploaded and the path is not within the allowed paths, we should add a new allowed path with the path of the file directory location.

**Comment by razvanaldea89** [comment]
Upsells should not exist on this page.

**Comment by cristinnaiulia** [comment]
I cannot add a new path

https://github.com/WPChill/download-monitor/assets/63049546/aca87566-e316-4a83-8a34-42aad6b8af0a

**Comment by cristinnaiulia** [comment]
I cannot save a new path. I get this error: 

![Screenshot 2024-05-14 103039](https://github.com/WPChill/download-monitor/assets/63049546/221e9b54-fa7b-44c6-8437-7e7a2dccdafb)

https://github.com/WPChill/download-monitor/assets/63049546/8c2f3faa-1b1b-4a56-9902-d0ccce1e96a4

**Comment by cristinnaiulia** [comment]
I can add a path, but the enable settings doesn't work properly. 

https://github.com/WPChill/download-monitor/assets/63049546/f40c5428-6956-4e05-a061-1e75a55b60c8

**Comment by andrei-l-cristea** [comment]
s-a intamplat ceva in ultimul update, activ si disabled nu mai au culori
<img width="842" alt="Screenshot 2024-07-10 at 10 00 05" src="https://github.com/WPChill/download-monitor/assets/53428716/32c5f664-cb7f-49df-bdfa-76fc7d186021">
