### ISSUE TITLE
Multiple downloads with the "Button" template on the same page

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1449]
**Describe the bug**
If we have multiple downloads with the "Button" template on the same page, the first button will be shown corrupted. Seems like the content is autop or something and it breaks the layout.

**To Reproduce**
1. Go to page and add multiple downloads with the "Button" template
2. See error

**Expected behavior**
The download button should appear normal.

**Screenshots**
![image](https://github.com/WPChill/download-monitor/assets/44024114/c1149cfb-d753-47c0-b937-bbce6dc75927)

**Extensions installed and activated:**
- [ ] Advanced Access Manager
- [ ] Amazon S3
- [ ] Buttons
- [ ] Captcha
- [ ] CSV Exporter
- [ ] CSV Importer
- [ ] Downloading Page
- [ ] Email lock
- [ ] Email Notifications
- [ ] Google Drive
- [ ] Gravity Forms
- [ ] Mailchimp
- [ ] Ninja Forms
- [ ] Page Addon
- [ ] Terms & Conditions
- [ ] Twitter Lock

**Additional context**

**Comment by razvanaldea89** [comment]
In order to test this you'll need to add in a page multiple shortcodes of Downloads, like so:
![image](https://github.com/WPChill/download-monitor/assets/44024114/b80df982-9c72-405b-8f22-0051dd6faec5)

**Comment by cristinnaiulia** [comment]
It's working now.

![Screenshot 2024-05-14 104634](https://github.com/WPChill/download-monitor/assets/63049546/c8f6be03-52e4-4554-aff9-44cec900fc32)
![Screenshot 2024-05-14 104625](https://github.com/WPChill/download-monitor/assets/63049546/ab0d78bb-2624-49c1-b5fc-c560dcf68e66)

**Comment by razvanaldea89** [comment]
Regarding spaces, should be based on theme styling and user placement.
