### ISSUE TITLE
Add the file type & location column to the admin list

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1450]
**Is your feature request related to a problem? Please describe.**
We should add columns that show the location of the file ( remote or locally hosted ) and the file type. Sorting by file type should also be possible.

**Comment by cristinnaiulia** [comment]
File type and location was added, but you can't sort by file type.
![Screenshot 2024-04-29 085950](https://github.com/WPChill/download-monitor/assets/63049546/710a9d51-2dd8-4ab7-bc42-254db292ed62)

**Comment by razvanaldea89** [comment]
In the case of non-existing files, files that have been deleted, or Downloads that have been imported, the label says that the files are remote, which is not correct.

**Comment by razvanaldea89** [comment]
Will have to check why does it say that the file is "Remote" if the existing file has a relative path to the wp-content/uploads/ folder but has been deleted.

**Comment by cristinnaiulia** [comment]
Now it says "unknown" when the file was deleted.

![Screenshot 2024-05-16 111049](https://github.com/WPChill/download-monitor/assets/63049546/b331bc8f-c3f2-416e-817a-8d3e1ccbec5c)
