### ISSUE TITLE
Button "Copy shortcode" from admin doesn't work 

### ISSUE THREAD

**Issue by cristinnaiulia** [WPChill/download-monitor#1452]
Button "Copy shortcode" from admin doesn't copy any shortcode.

![Screenshot 2024-04-29 093329](https://github.com/WPChill/download-monitor/assets/63049546/fcc7199c-af54-4f4d-b185-ed363add820f)

Versions:
DLM 5.0.0 and 4.9.13

**Comment by cristianraiber** [comment]
Also, aici e un alt font family pe "copy shortcode" fata de ce-i in restul plugin-ului

**Comment by cristinnaiulia** [comment]
I checked again, it still doesn't work on Chrome.

**Comment by cristinnaiulia** [comment]
Also, download link doesn't work on Chrome. It works on Firefox.

**Comment by beatricelucaci** [comment]
It works properly on my end on Chrome (shortcode & link). Tested with 4.9.13

**Comment by TeoAlex** [comment]
It works on my end with Chrome, Firefox, Edge

**Comment by razvanaldea89** [comment]
Going to close this and if users complain, will open again.
