### ISSUE TITLE
incompatibility with WPML - file not found error 

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#1453]
**Describe the bug**
 am using WPML for the translation. I am receiving a file not found when I try to download the English version of a download in Spanish.

https://support.wpchill.com/conversation/14091?folder_id=95

**Comment by razvanaldea89** [comment]
Added a filter that disables the previously added fix. Do not know exactly what has changed to WordPress, as the WPML version is the same, that causes the previous fix not to work anymore.

Filter in hand: `dlm_wpml_home_url_filter`

How to use: disable the fix by adding `add_filter( 'dlm_wpml_home_url_filter', '__return_false' )` in your child theme's functions.php file.
