### ISSUE TITLE
Pop-up blocked in some browsers

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1467]
**Describe the bug**
https://wordpress.org/support/topic/pdf-files-get-pop-up-block-in-firefox-and-safari/

**Comment by razvanaldea89** [comment]
We can handle this by adding a data-redirect attribute to the link and checking here https://github.com/WPChill/download-monitor/blob/master/assets/js/dlm-xhr.js#L56 if the attribute exists and is true and if the target is blank, and if everything is true then we discontinue the XHR and continue with the default behaviour of clicking a link. This can be done on links that come from shortcodes. We need to find a solution that works for links that are simply copied & pasted. We could check if it has a target _blank, but that is not necessarily a redirect to file option.

@cristeacosmin  @TeoAlex  @cristianraiber any suggestions?

**Comment by TeoAlex** [comment]
If it's working it's ok but i think this workaround complicates the allready overcomplicated DLM download functionality.
It's more of a browser setting issue than a DLM issue.

**Comment by cristianraiber** [comment]
Prea complicata abordarea; ar trebui vazut cum fac plugin-urile dedicate de pop-ups ...

**Comment by razvanaldea89** [comment]
Nu putem compara cu plugin-urile de pop-ups, ele pun continut in pagina si au anumiti triggeri care dau display block la pop-up. Noi deschidem pagina noua, nu pop-up, iar Firefox percepe ca o actiune nedorita de user, de acolo si problema.

**Comment by cristianraiber** [comment]
Nu cred ca poti lupta cu default behaviour in browsers ...

**Comment by razvanaldea89** [comment]
Nu, dar putem aplica metoda descrisa de mine ( functioneaza 100% pe link-uri din shortcode-uri - am si dat commit ), si atunci merge pe default behaviour.

**Comment by cristianraiber** [comment]
cc @cristeacosmin

**Comment by cristeacosmin** [comment]
if it works, it works - pentru moment hai sa nu mai pierdem timpul cu asta dar sa deschidem un issue in care sa ne dam seama cum altii mai destepti ca noi fac download. @andrei-l-cristea
