### ISSUE TITLE
Tooltips description display

### ISSUE THREAD

**Issue by andrei-l-cristea** [WPChill/download-monitor#1477]
Settings > Miscellaneous > tooltips de la 'download endpoint', 'endpoint value' au spatii goale si arata asa:
<img width="636" alt="Screenshot 2024-07-08 at 12 43 14" src="https://github.com/WPChill/download-monitor/assets/53428716/59635c3c-5326-45ba-ae20-429d9ee1ed3b">

**Comment by cristinnaiulia** [comment]
Inca este spatiu in tooltips: 
![Screenshot 2024-07-09 134839](https://github.com/WPChill/download-monitor/assets/63049546/1b3c2f0b-4537-4e50-bd33-709a3073354c)

![Screenshot 2024-07-09 135127](https://github.com/WPChill/download-monitor/assets/63049546/c4990715-0884-4403-92de-92844caf76dc)

**Comment by razvanaldea89** [comment]
<img width="959" alt="image" src="https://github.com/WPChill/download-monitor/assets/44024114/394bddea-d379-41a5-90df-1e53e9175b7a">

<img width="814" alt="image" src="https://github.com/WPChill/download-monitor/assets/44024114/63434488-267d-4bd6-84f1-b759ddd66281">

Mai poate testa cineva va rog?

**Comment by razvanaldea89** [comment]
Poate varianta asta merge mai bine, oricum acel <code> nu se vede in tooltip. In noua varianta am pus strong, si un font-weight pe restul textului de 300:
<img width="590" alt="image" src="https://github.com/WPChill/download-monitor/assets/44024114/d2f37f6f-dc12-4baf-b84e-5c922efac7b2">
<img width="583" alt="image" src="https://github.com/WPChill/download-monitor/assets/44024114/e4a915e7-4918-49af-906d-63e92a79b470">
