### ISSUE TITLE
Claritate la optiunea de Add new path

### ISSUE THREAD

**Issue by andrei-l-cristea** [WPChill/download-monitor#1481]
Cand adaugi un download care nu e in "Approved download paths" iti apare un mesaj sa adaugi o exceptie, doar ca in text este pus:
This will add the download path to the "Other downloads path" list.
... ar trebui sa fie tot "Approved downloads path" pentru consistenta.

Cand am incercat sa reproduc warning-ul asta (am sters path-ul din approved download paths), nu am mai reusit sa trigaruiesc prompt-ul de add download path, imi salva download-ul chiar daca path-ul nu era in approved download paths.

**Comment by razvanaldea89** [comment]
I think it would be better to change the text and add an extra "Enable path" functionality, in the case that the path already exists in the Allowed Paths but is not enabled. thoughts @andrei-l-cristea @cristeacosmin @TeoAlex ?

![image](https://github.com/WPChill/download-monitor/assets/44024114/79e0cf10-f4ef-4ad8-a7fd-64055a26b236)

**Comment by andrei-l-cristea** [comment]
da, este ok sa tratam si cazul cand e disabled path-ul, eu sunt un pic mai curios cum se trateaza partea a doua cand un path e sters, dupa ce am sters un path nu am mai primit acel prompt desi fisierul pe care il adaugam nu era in allowed paths

**Comment by razvanaldea89** [comment]
ar trebui sa primesti acel prompt daca dai refresh la pagina sau reintri in Download Edit. nu am reusit sa reproduc eroarea: adaugat path, sters path, intrat din nou in Download Edit, aparut prompt

**Comment by cristinnaiulia** [comment]
Daca dau disable la path si merg si adaug un nou download cu path-ul care este disabled, imi apare sa adaug un nou path, nu pot sa dau enable. Iar in approved path, imi apar 2 path-uri la fel, unul disable si unul enable.

1. dau disable la path 
![Screenshot 2024-07-09 132803](https://github.com/WPChill/download-monitor/assets/63049546/bd4729fd-e3ff-4688-9a34-05cb076fd78e)

2. merg sa adaug un nou download cu acealsi path
![Screenshot 2024-07-09 132808](https://github.com/WPChill/download-monitor/assets/63049546/8c5b1c5a-f693-49b0-8991-6ac8a33465cc)

3. vezi approved paths:
![Screenshot 2024-07-09 132826](https://github.com/WPChill/download-monitor/assets/63049546/b2484e56-a345-455c-bca8-88c948bfab5d)

**Comment by andrei-l-cristea** [comment]
scenariul pe care l-am discutat si pe slack, daca ai un path deja introdus si incerci sa il adaugi din nou, nu iti trigaruieste nici o eroare, iti zice doar settings saved. Sunt 2 cazuri de tratat:
1. path-ul e deja introdus si activ => iti da eroare ca deja e pus
2. path-ul e deja introdus si disabled => iti da eroare ca deja e pus si optiune de enabled / iti da eroare ca e deja pus si iti zice sa ii dai enable

**Comment by cristeacosmin** [comment]
1 ca n-are rost sa complicam treaba cu 2 acum. mai bine sa grabim update-ul

**Comment by razvanaldea89** [comment]
@cristeacosmin @andrei-l-cristea @TeoAlex e problema si cu 1, ca nu prea am cum sa ajung fara sa complic destul. se salveaza optiunile, iar WP-ul face un redirect din options.php. nu am acces la acel redirect, sau nu pot sa ii pun argumente in URL astfel incat sa stiu daca s-a modificat ceva intr-adevar, daca s-a adaugat path sau nu.

**Comment by cristeacosmin** [comment]
ai putea sa salvezi o notificare cu transient, in outputul de settings verifici daca exista vreun transient pentru notice-uri si iti faci treaba mai departe .. transientul poate fi sters dupa primul notice display

**Comment by razvanaldea89** [comment]
da, asta e partea cu complicatul
