### ISSUE TITLE
License tab

### ISSUE THREAD

**Issue by cristeacosmin** [WPChill/download-monitor#1484]
La single extensions tab ar trebui sa am campuri de completat? ca mie-mi apare gol in sectiunea respectiva
![image](https://github.com/WPChill/download-monitor/assets/10389279/8a03f4b7-44d9-4c16-8e27-39afa97b69d2)

**Comment by razvanaldea89** [comment]
Iti apare atunci cand ai extensii instalate si active.
![image](https://github.com/WPChill/download-monitor/assets/44024114/5fc1c2af-3110-481b-b92a-1d9afb3822d8)

**Comment by cristeacosmin** [comment]
pai atunci sa ascundem textu/descrierea daca nu sunt extensii instalate si active pentru consistenta

**Comment by razvanaldea89** [comment]
sunt oameni care au licente singulare, daca dezactiveaza cumva extensia imi e ca se panicheaza si vin la support ca nu mai au unde sa isi adauge licenta, desi ar trebui sa mearga si doar acolo la main license.

**Comment by cristeacosmin** [comment]
pai titlul/descrierea aia nu se pot ascunde fara sa afectezi functionalitatea?
