### ISSUE TITLE
API keys table needs some spacing

### ISSUE THREAD

**Issue by cristinnaiulia** [WPChill/download-monitor#1489]
![Screenshot 2024-07-16 080142](https://github.com/user-attachments/assets/b734d834-017d-4a02-a5d7-7736cce495ec)

![Screenshot 2024-07-16 080044](https://github.com/user-attachments/assets/bb475a80-74fa-4dfa-a0f7-163775a4ba42)

**Comment by razvanaldea89** [comment]
![image](https://github.com/user-attachments/assets/b108e991-9ae4-41bd-9dbe-7464bbddf9f4)
