### ISSUE TITLE
Database tables are not created on initial update

### ISSUE THREAD

**Issue by andrei-l-cristea** [WPChill/download-monitor#1500]
When I updated from the current version to Download Monitor 5.0.0, the following database tables were not created: dlm_cookies and dlm_cookiemeta. Thus, the different locks available were not working correctly. Once I deactivated and reactivated the Download Monitor plugin, this was resolved.

**Comment by razvanaldea89** [comment]
The transient for the check is deleted by reloading the extensions from the Extensions page, so if the table have been deleted after the transient was placed you'll need to reload the extensions.
