### ISSUE TITLE
Warning when trying to insert download in product (Shop feature)

### ISSUE THREAD

**Issue by andrei-l-cristea** [WPChill/download-monitor#1504]
When enabling the shop feature and trying to add a product, if I click the Insert download option I see the following warning:
<img width="793" alt="Screenshot 2024-08-07 at 09 19 59" src="https://github.com/user-attachments/assets/8fb22f5c-49bb-4100-a8d2-e9f078a1372d">

**Comment by andrei-l-cristea** [comment]
When I try to Quick add a download and upload a file, the name of the download is not correct:
<img width="793" alt="Screenshot 2024-08-07 at 09 22 25" src="https://github.com/user-attachments/assets/d5f30857-4844-4284-a62d-4e713a6bc11d">

**Comment by razvanaldea89** [comment]
The warning is coming from WordPress itself sadly.

**Comment by cristinnaiulia** [comment]
I don't have the warning with dlm 5.0.10.
The name of a quick download seems fine now:

![Screenshot 2024-09-24 092200](https://github.com/user-attachments/assets/6dc8176e-129e-4da0-b290-bc8bcbd8e7fe)

![Screenshot 2024-09-24 092210](https://github.com/user-attachments/assets/6b82b369-9955-4092-aac5-fb6881d51cc6)
