### ISSUE TITLE
Download Monitor Shop, product details

### ISSUE THREAD

**Issue by andrei-l-cristea** [WPChill/download-monitor#1505]
The description of the product is not shown when using the shortcode, only when accessing the permalink.

When you set an Excerpt for the file the front-end displays an extra blank button:
<img width="1503" alt="Screenshot 2024-08-07 at 10 48 03" src="https://github.com/user-attachments/assets/c6a18045-e44e-47b3-802c-de441a08ce2f">

**Comment by razvanaldea89** [comment]
The shortcode only outputs the buy button.

**Comment by cristinnaiulia** [comment]
![Screenshot 2024-08-07 130816](https://github.com/user-attachments/assets/3d2cffa6-7163-43e7-8a85-f05f8e329b16)
