### ISSUE TITLE
UUID column in download_log can not be null

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1506]
**Describe the bug**
This can be checked for example using Amazon S3 and opening download link using right click -> open in new tab.

In the Reports you can see where the error resides: You'll have downloads at point 1 but no downloads at point 2

![image](https://github.com/user-attachments/assets/cfe04085-2406-460f-a318-06d72e2e8ee5)

**Comment by cristinnaiulia** [comment]
Reports are looking good:

![Screenshot 2024-08-09 091841](https://github.com/user-attachments/assets/9e38fe31-bd66-48aa-911e-6d072b6c5e1f)

But, the count doesn't work only if you download it by open it in a new tab: 

https://github.com/user-attachments/assets/80d2bb01-33fb-4f4e-b991-8b9b630ebe42
