### ISSUE TITLE
Fatal Error caused by incompatible Container class

### ISSUE THREAD

**Issue by codepuncher** [WPChill/download-monitor#1512]
**Describe the bug**

**To Reproduce**
1. Install `illuminate/container` v8
2. Install `download-monitor` v5
3. Activate the plugin
4. Load any page

**Expected behavior**
No errors

**Screenshots**
```log
2024/08/22 07:03:42 [error] 12006#12006: *773074 FastCGI sent in stderr: "PHP message: PHP Fatal error: Declaration of Illuminate\Container\Container::has($id) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool in /path/to/vendor/illuminate/container/Container.php on line 194" while reading response header from upstream, client: 45.76.44.221, server: www.example.org.uk, request: "HEAD / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.1-fpm-example.sock:", host: "www.example.org.uk:19391"
```

**Extensions installed and activated:**
- [ ] Advanced Access Manager
- [ ] Amazon S3
- [ ] Buttons
- [ ] Captcha
- [ ] CSV Exporter
- [ ] CSV Importer
- [ ] Downloading Page
- [ ] Email lock
- [ ] Email Notifications
- [ ] Google Drive
- [ ] Gravity Forms
- [ ] Mailchimp
- [ ] Ninja Forms
- [ ] Page Addon

**Additional context**

Because your plugin bundles `pimple/container` and we have `illuminate/container` on our site, they are conflicting.
I see that you have Mozart for prefixing your dependencies but it doesn't seem to be working!
Please can this be fixed urgently as it is causing fatal error all over the site.

**Comment by razvanaldea89** [comment]
Please flush the permalinks and let me know if the problem still occurs with the 404s

**Comment by razvanaldea89** [comment]
Hi @codepuncher , could you please update to the 5.0.3 version and let me know if you are still experiencing problems?

**Comment by codepuncher** [comment]
Hi @razvanaldea89 latest version solves the original issue. But, now, downloads are 404.

**Comment by codepuncher** [comment]
Hi @razvanaldea89, no that didn't help.

We have another customer now also experiencing this same issue.
![image](https://github.com/user-attachments/assets/1f94f07a-58e9-440e-a6d3-bb03b260e1fc)
we use the same file structure on our websites

These are symlinks. Does that change anything? We are using [Bedrock](https://github.com/roots/bedrock) and [Trellis](https://github.com/roots/trellis)

**Comment by razvanaldea89** [comment]
Hi @codepuncher ,

Are you experiencing 404 or 403? The allowed paths should return 403 Access Denied if the file is not in the allowed paths. Could you add the Bedrock file paths to the Allowed Paths? 

Warmly,
Razvan

**Comment by codepuncher** [comment]
Hi @razvanaldea89 I have done that already as per my screenshot above and flushed permalinks but not working.

**Comment by razvanaldea89** [comment]
Is it possible to give us a link to a test download page containing downloads? You can use our contact form [here](https://download-monitor.com/contact/) if you do not want to give that info here.

**Comment by codepuncher** [comment]
Hi @razvanaldea89,

That might have been red-herring; most downloads are working fine now actually.
The ones that are not have strange file paths in the meta like `dlm_2024` instead of `dlm_uploads/2024`.

I'll fix these myself and happy to close this issue.

Thanks for the help.

**Comment by razvanaldea89** [comment]
Good news about the ones that are working, weird news about the dlm_2024 ones. Were them the same before the update? We did not make modifications that could affect the meta.

**Comment by codepuncher** [comment]
Not sure if they were like that originally but not worried now; all is working.

Thanks again!

**Comment by razvanaldea89** [comment]
Awesome :D 
Have a great day!

**Comment by codepuncher** [comment]
and you!
