### ISSUE TITLE
It cannot be used after version 5.0

### ISSUE THREAD

**Issue by phonograph123** [WPChill/download-monitor#1522]
![QQ20240825155159](https://github.com/user-attachments/assets/ad0565b5-ec36-4596-9eb8-f28498e2b1c0)
**Describe the bug**

Starting from August 22, 2024, when updating the software to 5.0, downloads often fail and are not recorded in user reports. I rolled back only the version download-monitor.4.9.14 and it worked fine.

**Comment by cristianraiber** [comment]
cc @razvanaldea89

**Comment by razvanaldea89** [comment]
Hello @phonograph123 ,

Thank you for taking the time to inform us about the problem. We've managed to replicate it and a fix will be available in the next update.

Warmly,
Razvan
