### ISSUE TITLE
Error type E_ERROR occurred on line 270 

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#1534]
**Describe the bug**
On the new registration page, it says
"A serious error has occurred on this site."
WordPress version5.9.3
theme: Simplicity2 child (version 20161002)
plugin: Download Monitor (version 5.0.9)
PHP version7.4.33

Error message received by email from WordPress.
===============
Error type E_ERROR occurred in file /home/users/0/lolipop.jp-dp59092518/web/sewing/wp-content/plugins/download-monitor/src/Admin/WritePanels.php on line 270. Error message: Uncaught Error: Call to a member function get_versions() on null in /home/users/0/lolipop.jp-dp59092518/web/sewing/wp-content/plugins/download-monitor/src/Admin/WritePanels.php:270
Stack trace:
#0 /home/users/0/lolipop.jp-dp59092518/web/sewing/wp -admin/includes/template.php(1395): DLM_Admin_Writepanels->download_files(Object(WP_Post), Array)
#1 /home/users/0/lolipop.jp-dp59092518/web/sewing/wp-admin/edit-form-advanced.php(688): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP _Post))
#2 /home/users/0/lolipop.jp-dp59092518/web/sewing/wp-admin/post-new.php(75): require('/home/users/0/l...')
#3 {main}
  thrown
https://support.wpchill.com/conversation/18280?folder_id=95

**Comment by razvanaldea89** [comment]
Could not replicate the issue, so added an extra check for the download object to not be null.
