### ISSUE TITLE
inconsistent file paths after update

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#1536]
**Describe the bug**
I am writing about the Download Monitor plugin, which I have been using for many years. During the last update, the file location system was changed and I will admit that in my opinion it makes little sense. I will explain.

When I started using DM, my path to the file looked like this:
domain.com/files/file.zip

For some reason, after some time the plugin started to shorten this path to:
files/file.zip

After the last update, after duplicating the download and entering a new address, the path was extended to something like this:
/home/{server-username}/domains/domain.com/public_html/files/file.zip

Forgive me, but in my opinion this is completely pointless.

Not only have we received three different ways of specifying the address path over the years - because the old ones have not been updated - they are still entered as I provided them above. This new value is also extremely vulnerable to any changes. It is enough for someone to move to a new server with a slightly different path to the files, and all the files will stop working. For large services with a large number of files, this can be a problem, especially since old downloads with the old path will probably work. I think you should think about it and withdraw the last solutions from it.

And if it is necessary and future-proof for some reason, you should add an option to update the paths of all previous files, so that they are provided in a uniform and consistent way.

https://support.wpchill.com/conversation/18496?folder_id=95

**Comment by razvanaldea89** [comment]
+1 can point to links with UTM when redirected https://wordpress.org/support/topic/certain-utm-tracking-paramaters-at-end-of-custom-url-seem-to-break-download

**Comment by razvanaldea89** [comment]
Indeed, taking into view the server migration, it will pose a problem. This can remain in URL for for those who select files from Media Library, or upload them, and in path for for those who select the files using the Browse button.

**Comment by razvanaldea89** [comment]
@TeoAlex @cristeacosmin @cristianraiber @andrei-l-cristea any thoughts?
