### ISSUE TITLE
Other downloads path on multisite doesn't show up

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1538]
**Describe the bug**
Comments can be found here : https://github.com/WPChill/download-monitor/issues/1403

Short: it appears that sometimes the Other Downloads paths, from editing network websites, doesn't appear.

**Comment by acesuares** [comment]
Apart from not appearing, the entry in setting/options is empty (no download path at all) and the files can not be downloaded (Access Denied). Downgrading to < 5.0 is the only option.

**Comment by acesuares** [comment]
Also, the 'normal' path for uploads, in case of a multi-site something like .../.../{BLOG_ID}/files/uploads is not used. The 'normal' path should not have to be specified in other download paths... i think?

**Comment by acesuares** [comment]
Just to tell that after using the DLM downloads path by 'adding new', it indeed gives the wrong path. See pic
![Screenshot from 2024-09-10 09-15-46](https://github.com/user-attachments/assets/7aecb237-9c42-4441-9e6e-15c089ff37d3)

After deleting that path and putting in the good path (the value in uplaod_path in settings) it works!

Thanks a lot for working on this.

**Comment by razvanaldea89** [comment]
Hello @acesuares ,

Managed to reproduce the situation where the DLM Downloads Paths tabs are not displayed in the Sites editing view and we'll issue a fix for this.

**Comment by razvanaldea89** [comment]
Seems like this needs a little more time. Could you please confirm that Download Monitor was not active on the main site of the multisite installation?

**Comment by acesuares** [comment]
Hi.
1. if DLM is not Network Active, then no DLM Download Path tabs.
2. If DLM is Network Active, then there are DLM Download path tabs.

**Comment by acesuares** [comment]
We also have now two sites that need a refresh of permalinks, not sure if it is related with DLM Network Active or not.

**Comment by razvanaldea89** [comment]
But, if you activate DLM on the main site, do the DLM Downloads Path tabs appear?

**Comment by razvanaldea89** [comment]
Can you do the following for me please? 

In the multisite configuration, first disable DLM Network Wide. Then, proceed to the main site of the multisite installation and activate DLM solely there (activations from secondary sites can remain as they are). Following these steps, check if the DLM Downloads Path is visible under Network > Sites > Edit.

**Comment by acesuares** [comment]
Yes, after activating the plugin on the  main site (not tjhe network,. but the main site) now we can see the Tab !!!!

**Comment by razvanaldea89** [comment]
The allowed paths for multisites have changed, and each site will have its own tab in the dashboard > Downloads > Settings area. The difference is that only the network admin, or a user that has the `manage_network` capability, can see the tab and do the proper modifications.

**Comment by cristinnaiulia** [comment]
DLM 5.0.9:

![Screenshot 2024-09-24 100159](https://github.com/user-attachments/assets/f37e28e6-67f6-4196-89dd-35c0cc1e8953)

Steps to reproduce:
1. Have a multisite environment
2. Add new sites
3. Activate Download Monitor only on sites (not network)
4. Go to settings -> Advanced -> See if the Approved Download Paths is there

DLM 5.0.10:

![Screenshot 2024-09-24 100358](https://github.com/user-attachments/assets/6589fac4-80ed-4c20-8bf6-15bbb4eb5058)
