### ISSUE TITLE
After network activate, all sites have no access page - sometimes this seems to crash site

### ISSUE THREAD

**Issue by acesuares** [WPChill/download-monitor#1540]
**Describe the bug**
After network activate, there is a page created in all sites 'No Access'. (Also in sites that don't use DLM!)
In one of our blogs this page was also shown in the home page because all pages where shown on the home page. This is of course not nice, because that site doesn't even use DLM
In that site, wp-admin gave a critical error

**To Reproduce**
We could not reproduce it at the moment, but all sites do have the no access page.
Also there was an error in the log:

[10-Sep-2024 14:45:13 UTC] PHP Fatal error:  Uncaught Error: Call to a member function add_endpoint() on null in /usr/share/wordpress/wp-includes/rewrite.php:337

**Extensions installed and activated:**
None

**Comment by acesuares** [comment]
Hmm apparently not on all sites. We have it confirmed on 2 sites (of 100) but also we have 2 sites confirmed without that special page. I can confirm that the pages are created today at the time of network activating DLM

**Comment by acesuares** [comment]
Sorry, it DOES occur on all sites. The sites where it DOES NOT occur are the sites that had the pluign activated (before the plugin was network activated).

This is an error when going to wp-admin (critical error, can't enter the site).

[10-Sep-2024 15:10:57 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_page_permastruct() on null in /usr/share/wordpress/wp-includes/link-template.php:435

**Comment by acesuares** [comment]
So this happens:

After first going to wp-admin:
[10-Sep-2024 15:13:40 UTC] PHP Fatal error:  Uncaught Error: Call to a member function add_endpoint() on null in /usr/share/wordpress/wp-includes/rewrite.php:337

Every time after that:
[10-Sep-2024 15:13:42 UTC] PHP Fatal error:  Uncaught Error: Call to a member function add_endpoint() on null in /usr/share/wordpress/wp-includes/rewrite.php:337

**Comment by acesuares** [comment]
So there is a number of sites we cannot login via wp-admin. But some other sites don't have that problem (but they do have that created page). BTW the page shows up in some lists, for instance when we said 'show all pages but not this page and that page'. The no access was added and then it of course showed up. Maybe a good idea to create that page as draft if it has to be created.

**Comment by razvanaldea89** [comment]
Thank you for the very detailed info, we'll have a look at it and issue a fix. I'll try to reproduce what you are experiencing, because I tried yesterday without activating the plugin network wide, only on websites, but the tabs in the Network Sites were still showing.

**Comment by razvanaldea89** [comment]
Managed to trigger the DB errors you are experiencing, but the fatal error I can't reproduce. Could you please let me know what steps did you take, so I can try and replicate them?

**Comment by acesuares** [comment]
Hi, great that you could trigger the DB error. I can not reproduce (and don't' want to :-) the error. The only info I can give is that the critical error messages are here https://github.com/WPChill/download-monitor/issues/1540#issuecomment-2341220507 and they only occurred on the websites which had the DB error.

**Comment by acesuares** [comment]
> Thank you for the very detailed info, we'll have a look at it and issue a fix. I'll try to reproduce what you are experiencing, because I tried yesterday without activating the plugin network wide, only on websites, but the tabs in the Network Sites were still showing.

This is indeed interesting. If I do not Network Activate DLM, the tabs are not showing.

On a second multisite, it's the exact same.
However, on the second multisite, where we have also installed PRO, there is NO such 'dlm_download_path' in the settings! And the downloads are working fine....

**Comment by cristinnaiulia** [comment]
I couldn't replicate all the problems. With DLM 5.0.10, I don't have any database errors, and no access pages are being created.
