### ISSUE TITLE
T&C tries to add missing CSS files

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1543]
**Describe the bug**
<img width="897" alt="image" src="https://github.com/user-attachments/assets/0d9b2a08-cb34-42fd-8dc7-c34858427482">

**Comment by cristinnaiulia** [comment]
Steps to reproduce this issue:
1. Go to settings and enable modal
2. Create a Download locked it with Terms and Conditions
3. Copy download shortcode on a page
4. Open Console
5. Click on the download
6. See errors in console:
![Screenshot 2024-09-13 095208](https://github.com/user-attachments/assets/17b8f6ee-a40e-44af-ba81-355ac8d4a65b)
