### ISSUE TITLE
In https://download-monitor.com/kb/csv-importer/ the link to the example CSV file is missing

### ISSUE THREAD

**Issue by acesuares** [WPChill/download-monitor#1544]
**Describe the bug**
In https://download-monitor.com/kb/csv-importer/ the link to the example CSV file is missing

**To Reproduce**
1. Go to https://download-monitor.com/kb/csv-importer/
2. Click on HERE (https://drive.google.com/file/d/1gfWl9_0h4GDoy9TgkxAKDmLJny0J9Cc6/view?usp=sharing)
3. Profit!

**Expected behavior**
An example CSV file.

**Extensions installed and activated:**
- [ ] CSV Importer (but that is not relevant)

**Comment by acesuares** [comment]
this bug was reported On Thu, Apr 6, 2023 at 19:50:48 EEST

**Comment by razvanaldea89** [comment]
Has been fixed :D
