### ISSUE TITLE
Multisite problematic route 

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1549]
**Describe the bug**
[A clear and concise description of what the bug is.](https://wordpress.org/support/topic/dlm-downloads-paths-in-multisite/)

**Comment by nnimoyoefoki** [comment]
maybe this will help
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)

**Comment by razvanaldea89** [comment]
Hello @nnimoyoefoki ,

Could you please let me know what is the purpose of the file you gave?

**Comment by razvanaldea89** [comment]
How to test:
- enable multi site
- install DLM
- activate DLM
- go to main site, create a download, add file from Media Library, try to download.
