### ISSUE TITLE
Critical error if paths are missing & access denied on files

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1558]
**Describe the bug**
https://wordpress.org/support/topic/critical-error-after-editing-approved-download-paths

https://wordpress.org/support/topic/issues-after-upgrading-to-5-0-10

**Comment by razvanaldea89** [comment]
Seems like you need to delete the paths in order to achieve the critical error. 

As for the access denied, it was a problem with the default allowed paths on multisite, was adding 2 times the string `sites` and the site id to the allowed path.

**Comment by cristinnaiulia** [comment]
I could replicate the access denied problem: 
![Screenshot 2024-09-26 110809](https://github.com/user-attachments/assets/0d93dbc1-f057-42fa-a2e1-9e3a4e3b1bb8)

The critical errors I couldn't replicate on my end.
