### ISSUE TITLE
Allow network admins on multisite to quick add download path

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#1559]
**Describe the bug**
Allow network admins on multisite to quick add download path from the Download edit screen.

**Comment by cristinnaiulia** [comment]
Steps to reproduce: 
1. Be logged with network admin
2. Add a new download with a new path
3. See the notification:

![Screenshot 2024-09-26 110844](https://github.com/user-attachments/assets/4fb9c7fe-b345-4295-9907-4ad8d68291e0)
