### ISSUE TITLE
Quick edit for terms and conditions is not working

### ISSUE THREAD

**Issue by cristinnaiulia** [WPChill/download-monitor#1565]
When I try to check the terms and conditions setting from quick edit, the settings is not saved.

**Comment by razvanaldea89** [comment]
@cristinnaiulia can you try again please? Seems to work fine.

**Comment by cristinnaiulia** [comment]
I tried again with DLM Version 5.0.12 and it's not working on my end.

**Comment by razvanaldea89** [comment]
@cristinnaiulia please test again with the fix.
