### ISSUE TITLE
Path conflicts in approved download paths

### ISSUE THREAD

**Issue by christiaanstijnen** [WPChill/download-monitor#1566]
**Describe the bug**
In the situation where the common path name from a file path and a approved download path is also used in a different folder name in the path, the code conflicts.

**To Reproduce**

1. Create 3 allowed download paths note the order of appearance: `srv/http/shared/uploads/dlm_uploads`, `srv/http/shared/uploads`, `srv/http/shared`.
2. Add a download with a path starting with `/uploads/dlm_uploads` ie: `/uploads/dlm_uploads/2024/10/08/test.pdf` the location of the file should be `/srv/http/shared/uploads/dlm_uploads/2024/10/08/test.pdf`
3. try to download the file. The file will not be found.
4. if you would change the order of the allowed paths to: `srv/http/shared`, `srv/http/shared/uploads`, `srv/http/shared/uploads/dlm_uploads`. all is fine.

**Expected behavior**
I would expect the order of the approved download paths should not affect the matching of file paths.

**Extensions installed and activated:**
no extensions required

**Comment by razvanaldea89** [comment]
There is a problem with the replacement of common directories, it replaces the "uploads" from "dlm_uploads" and results in something like `/dlm_2024/10/08/test.pdf`, which is not correct.
