### ISSUE TITLE
Compatibility with 6.7.1

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#1607]
**Describe the bug**
latest WP 6.7.1 triggers a notice for the Download Monitor plugin.

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the download-monitor domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /public_html/wp-includes/functions.php on line 611

Plugin adjustments are required according to this documentation:
https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/

https://wordpress.org/support/topic/compatibility-with-6-7-1/

**Comment by picman** [comment]
_src/DLM.php_

```php
public function __construct() {
		global $wpdb;

		$cron_jobs = DLM_CRON_Jobs::get_instance();

		// Setup Services
		$this->services = new DLM_Services();
		// Setup the download monitor upsells
		DLM_Upsells::get_instance();

		// Load plugin text domain.
		$this->load_textdomain();   /* <-- This line causes the problem */
```
