### ISSUE TITLE
Idea: Changelog notes

### ISSUE THREAD

**Issue by hacknug** [WPChill/download-monitor#178]
One of the main things I like about DM is the version feature. I think it would be great if we could add changelog notes to every version to let the admin and/or the users what changed in that version.

It could help the users to decide if they should download it (we all know users don't like to update) and the admin to keep everything in the same place.

**Comment by tardis221** [comment]
Just wondering if there has been any forward movement on this feature request?!

**Comment by cristianraiber** [comment]
Welp, I might be a bit late here but ... we've acquired ownership rights to DM from @barrykooij. 

The tl;dr version is - we'll start implementing this starting with our next update/release. It's something we've been already practicing with our existing lineup of plugins so it's up our alley.
