### ISSUE TITLE
Ease of Use

### ISSUE THREAD

**Issue by apintocr** [WPChill/download-monitor#245]
Hello,
Your plugin is great, it is probably the best Download Manager out there for developers (all the others are way too much bloated for no real added functionality).

However I find it would be usefull to have a shortcode "maker" in the editor, at the very least includ a shortcode reference "cheat sheet".

I know I can go to the wiki, but if I install this on a less techy client it I need to give them the instructions.

Thank you for your work :)

**Comment by barrykooij** [comment]
Love the suggestion, added it to the 1.7.0 milestone.

**Comment by apintocr** [comment]
Great you loved it! :)

**Comment by barrykooij** [comment]
Moving this one to a later release because I'm not sure how to make this fit into UI.

**Comment by cristianraiber** [comment]
The Wiki idea is good, the shortcode builder doesn't really make sense anymore in the world of Gutenberg. Closing this for now.
