### ISSUE TITLE
Json api

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [WPChill/download-monitor#248]
Hi just wondering any plans on adding WP REST API support i.e create custom api. https://github.com/WP-API/WP-API

**Comment by barrykooij** [comment]
Sounds interesting but not for coming version.

**Comment by giucu91** [comment]
Hello @Ashraf-Ali-aa,

What do you want to get from WP REST API ?

**Comment by cristianraiber** [comment]
Marking this as closed because of inactivity.
