### ISSUE TITLE
Option 'members only' in quick edit of download not set

### ISSUE THREAD

**Issue by DonQuicky** [WPChill/download-monitor#441]
When using the quick edit function in the list of downloads the option 'members only' remains empty while the option is set in normal edit mode.

Seems like a bug to me.

**Quick edit mode**
![option-not-set-quick-edit-mode](https://user-images.githubusercontent.com/1911772/34045228-41346840-e1a8-11e7-870e-35abe8c6551c.png)

**Normal edit mode**
![option-set-normal-edit-mode](https://user-images.githubusercontent.com/1911772/34045229-41528668-e1a8-11e7-9156-752eda8c69ff.png)

**Comment by barrykooij** [comment]
Hey,

Sorry for not replying sooner, I missed this ticket. This indeed looks like a bug in quick edit. Will look into this.

Kind Regards,

Barry Kooij

**Comment by barrykooij** [comment]
Pushing this back as it's not in need of hot fix right now. Trying to push out 4.0.1 as fast as I can to fix more urgent issues.

**Comment by barrykooij** [comment]
Sorry for pushing this back one more release. 4.2 will be a release focussed on something completely different so I feel like this will not be a good fit for that release.
