### ISSUE TITLE
IE11 downloading issues

### ISSUE THREAD

**Issue by barrykooij** [WPChill/download-monitor#467]
User report

In the 1.x version of the plugin, here is what I changed to get it to work. I would comment out one line and replace it with the code below. There was some issue in IE with the Accept-Ranges headers on the $version->filesize variable.

```
File: download-monitor/includes/class-dlm-download-handler.php

/*if ( $version->filesize ) { $headers['Content-Length'] = $version->filesize; $headers['Accept-Ranges'] = 'bytes'; }*/

$filesize = filesize($file_path); if ($filesize) { $headers['Content-Length'] = $filesize; $headers['Accept-Ranges'] = 'bytes'; }
```

**Comment by barrykooij** [comment]
Pushing this back for now as I'm unable to get IE11 working now that Edge is the new recommended browser. I definitely want to fix this in an upcoming patch but I don't want the 4.0.1 release to be delayed because of this.

**Comment by jmslbam** [comment]
@barrykooij Have you ever tried one of these? https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
