### ISSUE TITLE
Use SVG images for file icons

### ISSUE THREAD

**Issue by paulovsky** [WPChill/download-monitor#484]
It would be great to replace the old icons with something more modern and also make it accessible.

**Comment by paulovsky** [comment]
@barrykooij this might be useful

https://gist.github.com/paulovsky/2e71957a0f31adbeadc40a893a2ef87e

I'm not sure if it will work, requires some testing.

**Comment by cristianraiber** [comment]
This has been already implemented in the upcoming version of DLM Buttons Extension.
