### ISSUE TITLE
Display Category/Tag ID in admin column

### ISSUE THREAD

**Issue by hchouhan** [WPChill/download-monitor#576]
https://wordpress.org/support/topic/category-ids-4/#post-11243841

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/154252468-49c873b8-d601-408a-b935-7d1a6e2a28f0.png)

![image](https://user-images.githubusercontent.com/7841556/154252508-0e50a5d6-49c9-446e-8708-3745cd938cce.png)


user wants to easier see the ID of the category/tag

**Comment by razvanaldea89** [comment]
![image](https://user-images.githubusercontent.com/44024114/223975246-4a3d60a4-673e-4150-bca7-f7b61a6091ef.png)

We should add the ID of the category/tag in brackets like `dlm_category(#1)`
