### ISSUE TITLE
Japanese file name problem

### ISSUE THREAD

**Issue by tamori** [WPChill/download-monitor#587]
Hello.

I will report bug and how to fix.
I hope this report is everyone's useful.

I found bug. details are below.

1) I uploaded the file make Japanese file name from media page.(code UTF8)
2) I created page and paste download short code.
3) I tried to download the file from chrome. It's good.
4) I tried to download the file from Edge. It's bad.(broken file name)

I was try to change code and cleared this problem.

src/DownloadHandler.php

LINE:639
old:
　`$headers['Content-Disposition']       = "attachment; filename=\"{$file_name}\";";`
fixed:
`　$headers['Content-Disposition']       = 'attachment; filename*=UTF-8\'\''.rawurlencode($file_name);`

thanks.

**Comment by cristianraiber** [comment]
@razvanaldea89 - could we please test and see if this is still a problem?

**Comment by cristianraiber** [comment]
@razvanaldea89 - is this still an issue?

**Comment by razvanaldea89** [comment]
Issue fixed, can be closed
