### ISSUE TITLE
Add "secure" attribute on wp_dlm_downloading cookie

### ISSUE THREAD

**Issue by BernardZijlstra** [WPChill/download-monitor#592]
For security reasons it would be a nice feature if there is an option on the settings menu to enable the secure attribute on the wp_dlm_downloading cookie. During a pentest we found out the wp_dlm_downloading cookie had a HttpOnly attribute was missing the Secure attribute.

Some light reading:

<https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies>
<https://resources.infosecinstitute.com/securing-cookies-httponly-secure-flags/>

Cheers for this nice plugin.

**Comment by cristianraiber** [comment]
@BernardZijlstra - while that's true, as per this document: https://www.download-monitor.com/kb/download-monitor-cookie-usage/ 

We never store any personal or sensitive information in our cookies. Even if there was a middle-in-the-man type of attack, the most you'd be able to get out of that cookie would be a random string that's encrypted anyway and decrypted only on the server.

I don't disagree though that we could add a filter that allows users to add/modify cookie attributes on their own. 

Related to : #603
