### ISSUE TITLE
Add filter to cookie time

### ISSUE THREAD

**Issue by barrykooij** [WPChill/download-monitor#603]
https://github.com/download-monitor/download-monitor/blob/eacb283f45e4e883bb6ab43ae7bb9c9c53e600fb/src/CookieManager.php#L56

**Comment by cristianraiber** [comment]
This has been implemented in 4.5.4: https://github.com/WPChill/download-monitor/commit/914efad2ee312eb9ab188d381ab729c5836a1d50#diff-a21c482c47499dc962c4bcac5f0a2d385eccff153961bc2638f280a7ffc304b6R54
