### ISSUE TITLE
Gutenberg clips of template selectbox

### ISSUE THREAD

**Issue by barrykooij** [WPChill/download-monitor#604]
![image](https://user-images.githubusercontent.com/2846594/61699926-185e7f80-ad3c-11e9-9d6d-fe1be95633fd.png)

**Comment by hughc** [comment]
Just tripped over this myself- was trying to use a custom template and could only see the first 4 options in the dropdown. Took a read of the source code before i realised all options from `DLM_Template_Handler->get_available_templates()` were actually in the select box, but it was being cropped off, making selecting items by anything except the cursor keys impossible. 

Unsure how it can be easily fixed - setting the `height: 100%' of the containing  `<div class="components-panel">` addresses it, but that's outside the plugin's domain.

**Comment by hughc** [comment]
related issue here:

https://github.com/WordPress/gutenberg/issues/5535

**Comment by cristianraiber** [comment]
This has been addressed in Gutenberg.
