### ISSUE TITLE
Shortcode downloads disregards argument offset

### ISSUE THREAD

**Issue by miniwi2019** [WPChill/download-monitor#606]
When applying offset to the shortcode downloads of a category of files, it won't offset but shows all items.

`[downloads offset=1 category=items-2019 template=mba-file paginate=true per_page=4 before=<p>ITEM: after=</p>]
`
It was expected that shortcake loops the list of downloads of category _item-2019_ starting at the second item. 

Issue occurs since download monitor was installed in 2016

**Comment by razvanaldea89** [comment]
@TeoAlex  please look into this when we approach release v4.5.8

**Comment by TeoAlex** [comment]
Must include the "per_page" attribute and no "paginate" attribute or paginate=false;
We need to update the documentation aswell.
