### ISSUE TITLE
download-monitor + polylang = error 404

### ISSUE THREAD

**Issue by f2065** [WPChill/download-monitor#607]
Polylang's operating mode is “The language is set from the directory name in pretty permalinks”.
If in the Polylang settings to uncheck "Hide URL language information for default language" - then downloads from Download monitor do not work, error 404.
I tried changing the path in the settings of download monitor - instead of “download” do “en/download”, but this does not help.
I tried to save the permalinks settings again (according to the instructions from the FAQ) - this also does not help.

**Comment by razvanaldea89** [comment]
This is fixed now
