### ISSUE TITLE
Members only - download options not working with Super Admin

### ISSUE THREAD

**Issue by tomepajk** [WPChill/download-monitor#611]
When plugin installed on multisite, Super-Admins are unable to download the files set as Members only.

**Comment by razvanaldea89** [comment]
Can't replicate, @TeoAlex can't replicate either. @tomepajk could you give some details? 

Going to remove this from 4.5.7 update and close this next week if no response given.

**Comment by razvanaldea89** [comment]
Going to close this. If OP comes back with details will reopen it
