### ISSUE TITLE
5GB Limit

### ISSUE THREAD

**Issue by itformusic** [WPChill/download-monitor#628]
I know I tested it before and was able to download larger files, but right now with version 4.4.3, all downloads are stopping after 5.03GB of data.  It also doesn't show the total size of what is being downloaded (it shows the total as unknown).  The files are hosted on an public Amazon S3 bucket and are added via url.

**Comment by cristianraiber** [comment]
@andyluak - can you please test this w/ XHR and a file bigger than 5GB?

**Comment by itformusic** [comment]
I just tested a a 17GB file in version 4.5.2 and it seemed fine.

**Comment by cristianraiber** [comment]
That's great!
