### ISSUE TITLE
Conflict with CartFlows plugin, dashboard menu disappears

### ISSUE THREAD

**Issue by contemplate** [WPChill/download-monitor#631]
We recently enabled the Cartflows plugin ( https://wordpress.org/plugins/cartflows/ ) as well as the Pro version ( https://cartflows.com/ ) and noticed the Downloads menu item in the WordPress Dashboard disappears.

Not sure which plugin is at fault here so creating a ticket for both.

**Comment by andyluak** [comment]
Not hiding anymore . 
<img width="162" alt="image" src="https://user-images.githubusercontent.com/49715292/156138473-e2991c4f-08be-47ab-8559-221a313b4db2.png">
