### ISSUE TITLE
Issue with PayPal live in the shop

### ISSUE THREAD

**Issue by hchouhan** [WPChill/download-monitor#636]
Sandbox test works but when PayPal is set to live, there is an error.

**Comment by hchouhan** [comment]
https://wordpress.org/support/topic/payment-gateway-error-3/

**Comment by mplusb** [comment]
+1 https://secure.helpscout.net/conversation/1780190490/44343?folderId=4638445

**Comment by razvanaldea89** [comment]
PayPal payment going to work starting with Download Monitor version 4.5.5
