### ISSUE TITLE
Import and search index

### ISSUE THREAD

**Issue by unprintedch** [WPChill/download-monitor#637]
If i use the export / import extension the files don't  show up in search result when polylang or search wp is activated.
It probably has to see with th fact that no associate media is created during the process.

Do somebody experinced the same issue?

**Comment by cristianraiber** [comment]
@unprintedch - I'm not sure I understand. Can you please elaborate?

**Comment by unprintedch** [comment]
Let it go, look at the date! I don't even remember.
Thanks anyway!
