### ISSUE TITLE
Chunked Downloads Not Working

### ISSUE THREAD

**Issue by hchouhan** [WPChill/download-monitor#638]
In the latest version of the plugin, in the DownloadHandler.php file, the function readfile_chunked at line 667 has three parameters: $file, $retbytes = true, and $range = false. However, it is called at line 554 in the same file with: this->readfile_chunked( $file_path, $range). The $range variable in the call is being assigned to the $retbytes parameter instead. This can be fixed by changign the call to: this->readfile_chunked( $file_path, true, $range) instead.

**Comment by hchouhan** [comment]
https://wordpress.org/support/topic/chunked-downloads-not-working/

**Comment by hchouhan** [comment]
https://wordpress.org/support/topic/download-chunked-file-not-working/

**Comment by cristianraiber** [comment]
Related to #645 - this should be fixed thanks to XHR, right @andyluak ?

**Comment by cristianraiber** [comment]
cc @razvanaldea89

**Comment by razvanaldea89** [comment]
Yes, can be closed
