### ISSUE TITLE
invalid taxonomy dlm_download_category: Possible issue with PHP 7.4 and/or Siteorigin PageBuilder

### ISSUE THREAD

**Issue by wiese4** [WPChill/download-monitor#642]
I use a custom widget for Siteorigin page builder to display downloads. The editors can choose from all download categories via dropdown which is dynamically filled on widget creation. A while ago that worked just fine but since I upgraded to PHP 7.4 when the widget is initialized there's an error when using get_terms( array('taxonomy' =>'dlm_download_category', 'hide_empty' => false )); saying it's an invalid taxonomy. The taxonomy itself doesn't seem to be the problem, I can access the download categories page alright, so it might just be "too early" to access the taxonomy in the widget. But it did work a while ago so that's the strange part.

**Comment by razvanaldea89** [comment]
@TeoAlex please test this.

**Comment by andyluak** [comment]
@wiese4 could you please provide more details regarding the setup ? what widget are you using exactly and provide some screenshots also so we can replicate .

**Comment by razvanaldea89** [comment]
Seems OP doesn't answer and we can't replicate the issue, neither me nor @andyluak & @TeoAlex
