### ISSUE TITLE
timeout while exporting CSV of logs

### ISSUE THREAD

**Issue by rdzman** [WPChill/download-monitor#643]
On my site, hosted on a shared hosting plan on HostGator, I have about 30,000 items in my download logs, and when I try to "Export CSV" on the Logs page, I get the following error ...

*Fatal error: Maximum execution time of 30 seconds exceeded in /home4/rdzman/public_html/wp-content/plugins/download-monitor/src/Logs/LogExportCSV.php on line 139*

I have SSH access to the server, so I was wondering if there is a simple way to export the logs to a CSV file from the command-line?

Or better yet, a way to change the settings for my HostGator server to prevent the timeout of the web-request in the first place?

Any help is greatly appreciated. Thanks!

**Comment by rdzman** [comment]
Still haven't found a solution to this ... any ideas?

**Comment by rdzman** [comment]
Any pointers, please?

**Comment by cristianraiber** [comment]
This should be easily fixed by raising the PHP timeout limit to 60s. Ask your hosting to do this for you, normally, you don't have access to it.

**Comment by cristianraiber** [comment]
Happy to hear it worked.
