### ISSUE TITLE
Multipart-download issue in Nginx

### ISSUE THREAD

**Issue by hchouhan** [WPChill/download-monitor#645]
https://wordpress.org/support/topic/download-monitor-stopped-working-due-to-multipart-download-code/

**Comment by hchouhan** [comment]
https://wordpress.org/support/topic/chunked-downloads-not-working/

**Comment by cristianraiber** [comment]
https://wordpress.org/support/topic/chunked-downloads-not-working/#post-13520077

**Comment by cristianraiber** [comment]
@andyluak - this should be fixed thanks to XHR, correct?

**Comment by cristianraiber** [comment]
cc @razvanaldea89 - is this fixed?

**Comment by razvanaldea89** [comment]
Don't have problems in nginx anymore
