### ISSUE TITLE
DLM_Admin_Fields_Field esc_attr instead of esc_attr_e

### ISSUE THREAD

**Issue by barrykooij** [WPChill/download-monitor#656]
Bug found in 'abstract class DLM_Admin_Fields_Field ' // esc_attr_e( $placeholder ) should be esc_attr( $placeholder ). Usage of esc_attr_e() causes a html markup error with 'placeholder' attribute by echoing the value before the attribute name itself. public function e_placeholder() { $placeholder = $this->get_placeholder(); echo ( ! empty( $placeholder ) ) ? 'placeholder="' . esc_attr_e( $placeholder ) . '"' : ''; }

**Comment by cristianraiber** [comment]
@TeoAlex - please double-check that this is still an issue.

**Comment by TeoAlex** [comment]
Was fixed in a previous commit https://github.com/WPChill/download-monitor/commit/21394ded7266b64c0724b171b4b8e674c6510938
