### ISSUE TITLE
add a 4th parameter 'args' to 'dlm_get_template_part' hook

### ISSUE THREAD

**Issue by barrykooij** [WPChill/download-monitor#657]
Improvement suggestion. class DLM_Template_Handler->get_template_part(...) contains 2 hooks: // Allow 3rd party plugin filter template file from their plugin $template = apply_filters( 'dlm_get_template_part', $template, $slug, $name ); // Allow 3rd party plugin filter template arguments from their plugin $args = apply_filters( 'dlm_get_template_part_args', $args, $template, $slug, $name ); 

My suggestion is to add a 4th parameter 'args' to 'dlm_get_template_part' hook. Why? Simple due to the lack of context for callbacks registered to the hook. Here is my scenario: When loading the checkout page the following script is executed: $pgm = \Never5\DownloadMonitor\Shop\Services\Services::get()->service( 'payment_gateway' ); $payment_gateways = $pgm->get_enabled_gateways(); $default_gateway = download_monitor()->service( 'settings' )->get_option( 'default_gateway' ); if ( ! empty( $payment_gateways ) ) { ?>

**Comment by razvanaldea89** [comment]
Going to close this as it has been done in #922
