### ISSUE TITLE
Exclude multiple tags using exclude_tag shortcode attribute  doesn't work

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#660]
Should add `$tag_not_in = ! empty( $exclude_tag ) ? explode( ',', $exclude_tag ) : '';` in Shortcodes.php at line 304 and `'terms'    => $tag_not_in,` in same file at line 409

**Comment by cristianraiber** [comment]
@razvanaldea89 - is this still an issue?

**Comment by razvanaldea89** [comment]
Still an issue
