### ISSUE TITLE
Update JS lib dependencies

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#669]
- [ ] JS lib for reports: https://github.com/frappe/charts/releases/
- [ ] JS lib for Selects: https://github.com/select2/select2/releases (not sure why we're using Select2 instead of browser generated selects)
- [ ] Chosen JS: https://github.com/harvesthq/chosen/releases (we are currently using: 0.9.12)

**Comment by cristianraiber** [comment]
cc @razvanaldea89 - please take a look at this when u can.

**Comment by razvanaldea89** [comment]
Chosen and frappe are not used anymore.

Select2 is used on Shop Products, to select and search Downloads

![image](https://user-images.githubusercontent.com/44024114/199265163-e369eb2a-74c2-481b-a6d1-23ab6f93540b.png)
