### ISSUE TITLE
Browse for file should use WordPress Media Management

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#670]
![image](https://user-images.githubusercontent.com/7841556/113570216-90f29600-961c-11eb-8318-bfce5dc04fad.png)

---

This type of file manager shouldn't be used since it can lead to all sorts of issue, such as:
- security issues: #17 
- no way to restrict access, based on user roles
- no way to protect downloads against direct downloads unless provided with an extra .htaccess / nginx set of rules. 

Going forward, I think we should axe this and change it to use WordPress's media library uploader functionality. What we could do, for existing users who'd like to keep using this, is create a plugin that's hosted on w.org that brings back this functionality - with the note that it will no longer be officially supported and that it will be retired, in 12 months tops.

**Comment by sokratesagogo** [comment]
+1 Most of my customers expect this button to open the Media Library browser

**Comment by cristianraiber** [comment]
Here's a new idea here: 

![image](https://user-images.githubusercontent.com/7841556/154243397-3d26c203-2b95-44c4-822e-eb3ae4e0fe0f.png)
