### ISSUE TITLE
Issue with Downloads and translations plugins that use different domains

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#672]
Downloads won't download ( tested width Download Monitor Ninja Forms and WPML  )

**Comment by cristianraiber** [comment]
@razvanaldea89 - is this issue still happening?

**Comment by razvanaldea89** [comment]
Yes, can't seem to translate the pages, and when they do they lose Download Monitor's settings

**Comment by razvanaldea89** [comment]
Going to be some code placed in functions.php of the theme's child or a mini plugin 

https://gist.github.com/razvanaldea89/bc9604c0df341d179ad76c14e927ec69

**Comment by razvanaldea89** [comment]
@TeoAlex please create a mini plugin for wp.org with the code found in the gist. The plugin should have a setting where the user can enter the domain from which the requests are send

**Comment by razvanaldea89** [comment]
Mini-plugin launched - Download Monitor CORS
