### ISSUE TITLE
Add a select all and empty logs for Download Logs

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#673]
![image](https://user-images.githubusercontent.com/44024114/114876934-7af88880-9e07-11eb-93cd-fd3bab16f643.png)

**Comment by razvanaldea89** [comment]
Also, think we should add a "no-log" option if users don't want to have download logs

**Comment by cristianraiber** [comment]
@razvanaldea89 - could be useful IF we integrate with GA as well. So you wouldn't want to have the same stats recorded twice.

**Comment by razvanaldea89** [comment]
The "No log" option already exists, if you go to Settings->Logging and uncheck the "Download log" setting.

![image](https://user-images.githubusercontent.com/44024114/132670544-344913cd-b5b2-41bd-8cb2-e1031f7f1d4e.png)

**Comment by cristianraiber** [comment]
@razvanaldea89 - without logging enabled, you won't have any reports to generate. If we disable logging, we should let the user know that reporting is going to be affected as well.

Alternatively, disabling logging BUT moving reporting into GA is a potential solution.

**Comment by cristianraiber** [comment]
@razvanaldea89 - this shouldn't be a problem anymore, right?

**Comment by razvanaldea89** [comment]
Yes, deleting the logs is not possible anymore. If people complain it's a possibility to delete logs by date or all, but to keep reports as precise as possible we should not delete them.
