### ISSUE TITLE
Make warnings, like those for license, dismissible 

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#680]

**Comment by razvanaldea89** [comment]
As an update, seems this is happening only in 4.4.5 branch

**Comment by razvanaldea89** [comment]
As an update, only if on Extensions page it can't be dismissed

**Comment by cristianraiber** [comment]
Should be already fixed in 4.6.0 - please merge in 4.5.4 as well

**Comment by TeoAlex** [comment]
The warnings are not set in DLM lite but in each plugin. Commits to plugins have been made to reflect the desired change.
