### ISSUE TITLE
Popup if no permission 

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#686]
https://wordpress.org/support/topic/redirect-user-if-no-permission/

**Comment by cristianraiber** [comment]
@razvanaldea89 - I think we could set a filter here so that, by setting, it, the URL (or action?) could be changed.

**Comment by razvanaldea89** [comment]
@cristianraiber  A filter is present, `dlm_access_denied_redirect`, that the user can use to redirect to somewhere else if the visitor doesn't have access to the file. But what we can do now with XHR is open a Modal or display directly in the link that the user doesn't has access. In the modal I think it is possible to get the contents of the no-access page ( so the contents of the [dlm_no_access] shortcode ) and allow user registration or such to be held in the mentioned modal.

**Comment by cristianraiber** [comment]
> @cristianraiber A filter is present, `dlm_access_denied_redirect`, that the user can use to redirect to somewhere else if the visitor doesn't have access to the file. But what we can do now with XHR is open a Modal or display directly in the link that the user doesn't has access. In the modal I think it is possible to get the contents of the no-access page ( so the contents of the [dlm_no_access] shortcode ) and allow user registration or such to be held in the mentioned modal.

That sounds pretty awesome @razvanaldea89

**Comment by razvanaldea89** [comment]
5b2a249a

**Comment by razvanaldea89** [comment]
Code seems OK, needs some design improvement and can be launched.
