### ISSUE TITLE
Set cookies "secure" flag based on the servers configuration 

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#687]
https://wordpress.org/support/topic/insecure-cookie/

**Comment by cristianraiber** [comment]
@razvanaldea89 - I think we've already address this, here?  https://github.com/WPChill/download-monitor/commit/914efad2ee312eb9ab188d381ab729c5836a1d50

**Comment by razvanaldea89** [comment]
We only set the flag to false, we need to set the secure flag based on server configuration.
