### ISSUE TITLE
check if /download exist and inform user

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#692]
See: https://wordpress.org/support/topic/avoid-killed-my-site/ for more information

**Comment by giucu91** [comment]
At activation we can check if a page/post or something else exist with `download` slug exist and inform the user to change the page or the download monitor endpoint.

**Comment by cristianraiber** [comment]
@razvanaldea89 - have we addressed this?

**Comment by razvanaldea89** [comment]
I think this has been done, but I'll re-check it

**Comment by razvanaldea89** [comment]
Already implemented.
![image](https://user-images.githubusercontent.com/44024114/199526556-6e157f10-c707-4231-a447-b3194944b372.png)
