### ISSUE TITLE
 Microsoft Edge – couldn’t download-network issue

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#712]
I am having an Issue, Only on Microsoft Edge. When I download a Specific PDF File that is 30mb I get the “couldn’t download – network issue” Error.
I am using WP 5.7 with Download Monitor 4.4.4.

Work’s Fine on all other Browsers.

At First several other pdf’s did not work with the same issue, but less in size. However I have checked again today and now it is only this one File
https://wordpress.org/support/topic/microsoft-edge-couldnt-download-network-issue/

**Comment by cristianraiber** [comment]
Marking this as closed as it's an old issue and no one else has reported this problem in the meantime.
