### ISSUE TITLE
Gutenberg block issue with WP 5.8 and PHP8

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#715]
![image](https://user-images.githubusercontent.com/44024114/125931200-239b7da3-d408-42c1-bb6b-13365f364996.png)

As a note, all extensions are installed

**Comment by andyluak** [comment]
![image](https://user-images.githubusercontent.com/49715292/126476821-abe557c7-cb9e-43af-a101-eeaf350519e3.png)
![image](https://user-images.githubusercontent.com/49715292/126476846-9ddca710-e267-4387-b217-5d716a1e799c.png)

**Comment by razvanaldea89** [comment]
Seems ok now, tested on live webserver and everything works OK.
