### ISSUE TITLE
Reports page seems to not work in PHP8

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#716]
![image](https://user-images.githubusercontent.com/44024114/125933191-a67e91d0-410d-409b-b84d-fe908b3f57b2.png)

**Comment by andyluak** [comment]
![image](https://user-images.githubusercontent.com/49715292/126475681-01c1db91-80a1-45f7-a64c-c7304cb93411.png)
Works for me 
![image](https://user-images.githubusercontent.com/49715292/126475735-d0fd17e8-7d40-488e-8189-25f5df747b43.png)

**Comment by razvanaldea89** [comment]
Seems to be OK now
