### ISSUE TITLE
Download Monitor "Conflict with Woo Commerce"

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#718]
Downloads are accessible as a normal download however they are not working when served in a WooComm digital product download.
https://secure.helpscout.net/conversation/1576396555/39645?folderId=4656047

**Comment by mplusb** [comment]
I have Download monitor and Amazon extension installed - I am getting an error of "Download does not exist. 

    Download Monitor 4.4.4
    Download Monitor - Amazon S3 4.0.2

The only major change in other plugins in the past few days was:

WooCommerce 5.4.1 to 5.4.2
WooCommerce 5.4.2 to 5.5.1 (SecurityPatch Update)

I have run some additional testing this morning with the following results:
I can download files (hosted on s3 and saved through DM) - no issue at all. 

However.....any files accessible using the WooCommerce download links, do not work. I save the DM link into the WooComm Product page as a digital download after purchase.

**Comment by razvanaldea89** [comment]
WooCommerce needs to redirect to file in order for the Download Monitor to properly work with it. Go to Woocommerce->Settings->Products->Downloadable products. At `File download method` please select `Redirect only`. This should do the trick and Download Monitor should continue to work with WooCommerce

**Comment by cristianraiber** [comment]
@razvanaldea89 @andyluak - can you please re-test this and make sure it also works w/ XHR?
