### ISSUE TITLE
php8 errors

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#720]
Deprecated: Required parameter $download follows optional parameter $type in wp-content/plugins/download-monitor/includes/deprecated.php on line 21

Deprecated: Required parameter $version follows optional parameter $type in wp-content/plugins/download-monitor/includes/deprecated.php on line 21

Deprecated: Required parameter $download follows optional parameter $type in wp-content/plugins/download-monitor/src/DownloadHandler.php on line 336

Deprecated: Required parameter $version follows optional parameter $type in wp-content/plugins/download-monitor/src/DownloadHandler.php on line 336

**Comment by andyluak** [comment]
duplicate of https://github.com/WPChill/download-monitor/issues/682 - fixed
