### ISSUE TITLE
Additional fields/information for log download

### ISSUE THREAD

**Issue by sonjadeissenboeck** [WPChill/download-monitor#724]
Hi all, 

we would really appreciate the option to have the version number/name displayed in the download log. So far, only the ID is downloaded, but once downloaded we cannot map the ID to the name or number of the version anymore. 
Any ideas when/how this is possible?
Thanks!

**Comment by cristianraiber** [comment]
@razvanaldea89 - do we have this in CORE (lite) or is it part of the Enhanced Metrics extension?

**Comment by razvanaldea89** [comment]
Already present in lite with the new reports. going to close this
