### ISSUE TITLE
logs and downloads

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#727]
thanks for the great plugin! We are facing a problem though: The count for the downloads differs in different views. Directly under "Download" there is a higher count as in the "Download Reports" section. The count in the "Logs" section seams to be the same as in the "Download Reports" section. I also added a screenshot. Can you please help? We need to sort out, what the correct numbers are. 

-- the reason there are not the same numbers on Logs and Downloads is because Logs is counting only one download per user.
In downloads are counting all downloads. If a user downloads the same download twice it's being counted in Downloads, but not reports.

**Comment by mplusb** [comment]
https://secure.helpscout.net/conversation/1540372439/38668

**Comment by cristianraiber** [comment]
After DLM 4.6.x this does not happen anymore.
