### ISSUE TITLE
Group browsers by desktop/mobile

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#734]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/7841556/133995363-23dbedd0-2e86-4098-9b67-c93c3bb11043.png">

**Comment by cristianraiber** [comment]
We should have like 2 sub-tabs here ...

**Comment by razvanaldea89** [comment]
@cristianraiber  Think we need more than 2... there are bots, TV browsers, gaming consoles browser, all of them getting logged and ending in reports.

**Comment by cristianraiber** [comment]
> @cristianraiber Think we need more than 2... there are bots, TV browsers, gaming consoles browser, all of them getting logged and ending in reports.

I think we could add a 3rd tab, called "Others"  where we could list these.
