### ISSUE TITLE
Update datepicker library

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#736]
Current:
![image](https://user-images.githubusercontent.com/7841556/133995986-32b888b5-8caf-45ce-a863-fee5c5837264.png)

----

Ideal: 
<img width="433" alt="image" src="https://user-images.githubusercontent.com/7841556/133995972-4799ee06-c88e-480d-8acd-5d29cf6fc8a1.png">

<img width="441" alt="image" src="https://user-images.githubusercontent.com/7841556/133996045-49eab947-b2db-4261-8cc1-6874ea0250dc.png">

**Comment by cristianraiber** [comment]
The screenshots for the ideal version are coming from the plugin: EDD Metrics: https://wordpress.org/plugins/edd-metrics/

**Comment by razvanaldea89** [comment]
![image](https://user-images.githubusercontent.com/44024114/167602590-670e5f18-ae88-453a-b6a0-961b83f38b68.png)
![image](https://user-images.githubusercontent.com/44024114/167602653-19cd5de2-fed6-4f32-9a59-f1cdb8a6bfb1.png)
