### ISSUE TITLE
Hotlinking not working with Brave

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#739]
Recently several users warned us downloads were not working using Brave navigator (Windows10 and Linux version).
We discovered that the “Prevent hotlinking” option was the culprit.

Preventing hotlinking is the best feature of this plugin (and a requirement) so we prefer asking our users to switch to another browser.

https://wordpress.org/support/topic/hotlinking-not-working-with-brave/

**Comment by cristianraiber** [comment]
@andyluak - we need to make sure that "hotlinking" option still works w/ XHR

**Comment by andyluak** [comment]
Tested this and it still works .

**Comment by mplusb** [comment]
user reported this still does not work with brave.
I tested with firefox/chrome/brave, it does not work with any browser for me.

**Comment by TeoAlex** [comment]
Tested again with Brave browser(  [Version 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit)] ) and it's working.
