### ISSUE TITLE
PDF files corrupt after update

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#752]
PDF files corrupt after update

I've just restore a backup with version 4.4.4 of DLM in order to solve the high priority issue.

That's why you didn't find errors any more, but I can say that every download made with the updated version of the plug-in was set as "redirect to remote file" instead of "completed". Furthermore I try to follow the steps illustrated in your installation guide and I didn't find in my back-end the section of "select downloading page".

I really don't know what is the core problem, but I think you should check a better compatibility with previous version of your plug-in.

**Comment by razvanaldea89** [comment]
Think this was fixed

**Comment by razvanaldea89** [comment]
@andyluak could you please test this?

**Comment by razvanaldea89** [comment]
Can't replicate either.

**Comment by andyluak** [comment]
Can't replicate either
