### ISSUE TITLE
Download category

### ISSUE THREAD

**Issue by romanneverov** [WPChill/download-monitor#753]
After update to 4.4.9 on Downloads page I cant choose Download category anymore. Take a look at screenshot.
WP 5.8.1
![screenshot](https://user-images.githubusercontent.com/26056005/139662210-115bedfc-bb7d-4441-95fb-4b4002f71b8e.JPG)

**Comment by mplusb** [comment]
+3

**Comment by giucu91** [comment]
Hello @romanneverov 

Please update to 4.4.10.

Thank you for reporting.
