### ISSUE TITLE
bug 4.4.7 and up

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#754]
cannot save download, message:
<img width="826" alt="Screenshot 2021-11-01 at 15 37 24" src="https://user-images.githubusercontent.com/26008574/139680403-35d868c1-00d3-4cee-b1e4-874c9a72e157.png">
  
with 4.4.4 - 4.4.6 works fine

**Comment by razvanaldea89** [comment]
@mplusb do you remember if the shop was enabled? Could you please try now with version 4.4.13?

**Comment by giucu91** [comment]
fixed in 4.4.13
