### ISSUE TITLE
error: Forbidden You don't have permission to access this resource.

### ISSUE THREAD

**Issue by manfredgr** [WPChill/download-monitor#759]
Every download gives this error. Even when I'm logged in as admin. Don't know what is going wrong.

Forbidden

You don't have permission to access this resource.

**Comment by giucu91** [comment]
Hello @manfredgr , can you tell us what plugins do you have installed ? Also for downloads you have check "redirect only" ?

**Comment by razvanaldea89** [comment]
This should be fixed now ( versions 4.4.13 )
