### ISSUE TITLE
Add "branding bar" on ALL DLM related pages

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#760]
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/7841556/140532572-01d7cb8d-d67f-4dd6-b373-7e5d65d7c375.png">

---

**Comment by cristianraiber** [comment]
Like we did for Modula - 
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/7841556/140532637-d27a9806-3161-467a-8b0a-6669e2585e5c.png">

**Comment by giucu91** [comment]
this was added.
