### ISSUE TITLE
Test and Delete the uninstall.php file from root

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#761]
Uninstall process is now being manipulated by `DLM_Uninstall` class located in includes/admin/uninstall/class-dlm-uninstall.php

**Comment by TeoAlex** [comment]
The following are not being deleted on Uninstall:

DB tables:
wp_dlm_order
wp_dlm_order_customer
wp_dlm_order_item
wp_dlm_order_transaction
wp_dlm_session

options ( wp_options )
download_monitor_wisdom_last_track_time
download-monitor_wisdom_tracking
download-monitor-rate-time
widget_dlm_widget_downloads

Post types (wp_posts)
dlm_product
dlm_download
dlm_download

Meta values for dlm_ post types (wp_postmeta)
ALL

Terms (wp_terms)
ALL

Terms Taxonomies (wp_term_taxonomy)
dlm_download_tag
dlm_download_category

**Comment by giucu91** [comment]
outstanding: delete posts types and taxonomies.

**Comment by razvanaldea89** [comment]
Now the uninstall should delete taxonomies, terms, dlm_product, dlm_download, dlm_download_version, options, transients and tables
