### ISSUE TITLE
delete the price of $39 in the upsells 

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#762]
"  When I install the Download Monitor plugin it shows me an extension called "Mailchimp Lock" for 39 USD. Where I can buy only this extension. " - this is what an user asked
The extensions cannot be purchased separately anymore so the price of $39 should not appear in the upsells and also it should not be mentioned the fact that they can be purchased separately

**Comment by cristianraiber** [comment]
@beatricelucaci - already fixed in DLM 4.4.12
