### ISSUE TITLE
Sort Alphanumeric title

### ISSUE THREAD

**Issue by andyluak** [WPChill/download-monitor#773]
Given a list of download with this title : 1, 11, 2, 21, 26, 3, 36. 

Expected result : 1 2 3 11 21 26 36
Result : 1 11 2 21 26 3 36 . 

https://stackoverflow.com/questions/8557172/mysql-order-by-sorting-alphanumeric-correctly

**Comment by cristianraiber** [comment]
@razvanaldea89 - is this issue still happening?

**Comment by razvanaldea89** [comment]
Currently the title is only ordered alphabetically

**Comment by razvanaldea89** [comment]
Going to close this, should let WordPress handle this. @cristianraiber @giucu91 please reopen ticket if you'd like the plugin to handle this.

As a hint we should use `uksort` and `strnatcmp` in the retrieve function found in WordPressDownloadsRepository.php to sort the Downloads in a natural way.
