### ISSUE TITLE
Partition the Download Monitor menu into groups

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#776]
Similar to this

![image](https://user-images.githubusercontent.com/44024114/142371575-e96e80c0-6c42-42b8-a450-a27da6d620a0.png)

**Comment by razvanaldea89** [comment]
Before:

![image](https://user-images.githubusercontent.com/44024114/162142555-bb7f8a7b-5e6e-43ba-a7f1-a03ab3d5eae2.png)

After:

![image](https://user-images.githubusercontent.com/44024114/162142620-a923fcde-9d01-4fb5-b860-a2ce271844d3.png)

**Comment by razvanaldea89** [comment]
@cristianraiber @giucu91 Any thoughts/suggestions on the new look?

**Comment by cristianraiber** [comment]
it looks OK imho

**Comment by razvanaldea89** [comment]
@TeoAlex there is a problem regarding this design, when you hover the menu entry the line on the left looks very big in comparison with the other menu entries.
![image](https://user-images.githubusercontent.com/44024114/163587378-fa9094c3-3441-44d7-b92c-e1067ca783ca.png)


Remade the CSS, now a little bit more compact  but the line is same height on all the menu entries.
![image](https://user-images.githubusercontent.com/44024114/163587543-6af9a5a5-e959-4858-8c31-c3fe2746f79b.png)

**Comment by razvanaldea89** [comment]
@cristianraiber @giucu91 any thoughts?

**Comment by cristianraiber** [comment]
👍
