### ISSUE TITLE
Downloads in table layout (document library)

### ISSUE THREAD

**Issue by BostanicaElena** [WPChill/download-monitor#779]
It would be useful to have the option in Download Monitor to create a list of available downloads, in a table layout. You can see an example in the very beginning of this video: https://www.youtube.com/watch?v=U-5-K-nkxv4
The closest thing we have to this is the [download_page] shortcode, which creates a page with downloads grouped by category: https://www.download-monitor.com/extensions/page-addon/

**Comment by giucu91** [comment]
This will be implemented in page addon.
