### ISSUE TITLE
Improve file downloads - move away from server forced downloads

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#781]
I found XHR (XMLHTTPRequest) as a solution for this. It also offers progress download,, which means we'll be able to know when a download has reached 100% and ONLY then count it as "downloaded"

XHR tutorials I found:
- https://usefulangle.com/post/68/javascript-ajax-download-file
- https://javascript.info/xmlhttprequest
- https://www.html5rocks.com/tutorials/file/xhr2/

**Comment by razvanaldea89** [comment]
Redirect to file doesn't seem to work well
