### ISSUE TITLE
Load frontend resources (CSS/JS) only where DLM is actually being used

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#782]
Currently, DLM's CSS files are being loaded even though the plugin's not being used

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/142993541-3ed7ce57-790c-4e52-b934-73ea24dc708b.png)

**Comment by cristianraiber** [comment]
Site where I saw this happening: [calendar.google.com](https://ethiojobs.zacmaa.net/employe/blog/)

**Comment by TeoAlex** [comment]
https://github.com/WPChill/download-monitor/commit/022577c4f06d6f881423f4f1aea085a767845c3d
