### ISSUE TITLE
bug shop - cannot see order details

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#788]
- after an order was created you cannot open it to see its details/edit it. When you try to open one of the order you see this message: "download-monitor-orders cannot be loaded."

Backend

-create a new Download ->PASS

-create a new Product -> PASS

-create a new Button - PASS

Place the new Button into a new Page -> PASS

Frontend

-goTo the new Page and Press the new Product Button ->

-press the Button to order the Product -> PASS

-reach the Checkout Page -> PASS

-filling out the fields -> PASS

-proceed the order over the Test Gateway -> PASS

-Receive a Mail with the Order Details ->PASS

Backend

-go to DOWNLOAD, ORDER all test Orders are logged ->PASS

-click on and record to open the order detail -> FAIL
a messgae appears "download-monitor-orders cannot be loaded."

**Comment by weblint** [comment]
Retest -> PASS
