### ISSUE TITLE
Improve file browser

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#793]
- in some situations, it can cause security issues

see more here: https://secure.helpscout.net/conversation/1710666833/42705/

I think we should rely only on the WP Media uploader

cc @giucu91 @razvanaldea89 @andyluak

**Comment by TeoAlex** [comment]
The File Browser allready didn't show 'php', 'html', 'htm', 'tmp' file types in the view. 
Added a check that prevents the download of existing  'php', 'html', 'htm' and 'tmp' type files.

**Comment by razvanaldea89** [comment]
Checks for file type and file location have already been pushed.
