### ISSUE TITLE
The payment module can only be used in PayPal Sandbox mode

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#796]
The payment module can only be used in PayPal Sandox mode. As soon as the sandbox is inactive, the payment module reports Payment gateway error: Payment could not be created. Please check your PayPal logs.
https://secure.helpscout.net/conversation/1713356995/42767?folderId=4656047#

**Comment by razvanaldea89** [comment]
Payment with PayPal going to be OK with the new API
