### ISSUE TITLE
Shop, Products

### ISSUE THREAD

**Issue by weblint** [WPChill/download-monitor#797]
![image](https://user-images.githubusercontent.com/16798922/144602575-2ca81a56-2271-4773-b15c-15cb1082840e.png)
If products contain an entry in the "Text excerpt" entry, the button also displays  extra tags p /p.

![image](https://user-images.githubusercontent.com/16798922/144602980-9f839be0-34c8-4912-bf22-a3fb4e7f2c9a.png)

**Comment by cristianraiber** [comment]
It looks like a wrong sanitization here

**Comment by TeoAlex** [comment]
This is a duplicate of https://github.com/WPChill/download-monitor/issues/790.
