### ISSUE TITLE
Downloads randomly stop working

### ISSUE THREAD

**Issue by scottmaniol** [WPChill/download-monitor#799]
Every now and then, for no apparent reason, a given download will stop working and will instead say "Forbidden." I have to upload the file again to get it to work. Any ideas why?

**Comment by mplusb** [comment]
Hi @scottmaniol - please send us an email to dlm@machothemes.helpscoutapp.com in order to help asap. Please include the URL of the page where we can test this behavior, and please also include your plugin version #
