### ISSUE TITLE
Changing endpoint to an existing value doesn't really work

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#801]
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/7841556/145673427-07149b45-9c08-43db-95bb-13ff12d2c46c.png">

branch I tested with - `dlm_reports`

**Comment by cristianraiber** [comment]
It still saved and the notification showed AFTER the new value was saved

**Comment by razvanaldea89** [comment]
@TeoAlex please merge this in branch 4.5.6 after the 4.5.5 release

**Comment by razvanaldea89** [comment]
Replaced the option with a transient. Also, the transient should be set and the flush should happen only if the endpoint really changed, not on every save of the Download Monitor's settings.
