### ISSUE TITLE
REST API doesn't work when using non-pretty permalinks

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/download-monitor#803]
If using non-pretty permalinks the reports REST API route doesn't work
![image](https://user-images.githubusercontent.com/19348508/145777715-410357fa-62bc-4b18-94cb-434daad4c527.png)

**Comment by razvanaldea89** [comment]
With the new fetch limited this does not work on plain permalinks

**Comment by razvanaldea89** [comment]
@TeoAlex please test this when you have time
