### ISSUE TITLE
Resume upgrader bug

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#805]
If the upgrader is interrupted, the offset is saved but when we resume the upgrader it may be possible to migrate multiple times same DB entries. Will need to delete the previous migrated entries that corresponded with the saved offset and reinitiate the migrate of the offset.

**Comment by TeoAlex** [comment]
The upgrader resumes but i have 447951 rows in wp_download_log and after the upgrade in Reports i have 449657
![image](https://user-images.githubusercontent.com/19348508/153393370-360747fd-12f6-464d-8688-725a1b3a0a77.png)
![image](https://user-images.githubusercontent.com/19348508/153393428-7916d7dd-9ee2-4f0e-9f1e-c394c264f2d6.png)

there could be a problem with sql not showing all rows?

**Comment by razvanaldea89** [comment]
Doing a `SELECT` COUNT(`ID`) FROM 'wp_download_log';` shows there are 449.657 rows, but going to phpmyadmin shows only 447370 

![image](https://user-images.githubusercontent.com/44024114/167098302-4b5054fc-fa9d-4d25-ba30-a13707ca5ea5.png)
