### ISSUE TITLE
Address code analysis warnings

### ISSUE THREAD

**Issue by pdewouters** [WPChill/download-monitor#808]
I ran this tool on the codebase, as I'm considering using the plugin.
There are a few places that have unescaped variables which need to be fixed.
https://github.com/WordPress/wporg-code-analysis

**Comment by cristianraiber** [comment]
@TeoAlex - need to push this into 4.5.3 branch as well.

**Comment by pdewouters** [comment]
thanks for addressing these :)

**Comment by cristianraiber** [comment]
@pdewouters - this will be available in our next update, scheduled for the 21st of this month.
