### ISSUE TITLE
 File/ Version Date error

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#812]
When editing an existing download, and adding a new version, the ‘date’ in the file heading (e.g. #XXXX Version X (date) – Downloaded X times) always shows the date as the current date. The ‘file’ date option in the meta box identifies the correct date that the file was added / uploaded to the download, but the title date is incorrect.

<img width="966" alt="Screenshot 2022-01-10 at 12 53 35" src="https://user-images.githubusercontent.com/26008574/148754506-2f9767e5-e57d-406f-ba94-1b70508584ac.png">

**Comment by razvanaldea89** [comment]
@TeoAlex please merge this in branch 4.5.4 after the 4.5.3 release
