### ISSUE TITLE
Downloading large files does not work in multi-threaded mode

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#816]
Downloading large (350MB) files does not work in multi-threaded mode (for example, in Download Master © westbyte). The file is downloaded to 99% and then does not go. Restart doesn’t help.
The situation is checked and on a clean test site.
Version Download Monitor – 4.4.14 (it was the same in older versions).

The client log is something like this.
The actual file is 328 MB (344,057,137 bytes).

https://wordpress.org/support/topic/downloading-large-files-does-not-work-in-multi-threaded-mode/

**Comment by TeoAlex** [comment]
Asked the issuer what server config does he have so we can test it ourselves.

**Comment by f2065** [comment]
Tried different versions of PHP - 5.6, 7.0, 7.1, 7.2, 7.4 - it doesn't change anything.
Third party WP plugins - no effect, I have a separate clean install of WordPress with Download Monitor to check.
Server - LiteSpeed, ModPagespeed.
Linux 3.10.0-962.3.2.lve1.5.49.el7.x86_64 x86_64

The problem probably does not occur with all programs or files.
There is a 100% problem when downloading zip-files using Internet Download Accelerator (by westbyte), 350 MB zip-file, downloading in 5 streams. And the file comes damaged (its analysis shows that the contents of the file are duplicated 5 times, i.e. the server gave 1 part normally, and then 2,3,4,5 parts - this is the entire content of 1 part).

I looked at the problem lines in DownloadHandler.php
Line 541:
		if ( isset( $_SERVER['HTTP_RANGE'] ) && $version->get_filesize() ) {
			// phpcs:ignore
			list( $a, $range ) = explode( "=", $_SERVER['HTTP_RANGE'], 2 );
			list( $range ) = explode( ",", $range, 2 );
			list( $range, $range_end ) = explode( "-", $range );
			$range = intval( $range );
Debugging showed that $_SERVER['HTTP_RANGE'] comes in an incomplete format, like «bytes=270983901-». And all explode() don't work, $range_end is empty. It is then filled in with
	if ( ! $range_end ) {
	$range_end = $version->get_filesize() - 1; 
And this results in the loss of 1 byte, on which the download hangs.

The second part of the problem, file corruption in readfile_chunked(),
The function is like this:
public function readfile_chunked( $file, $retbytes = true, $range = false )
I added an entry to the log for the $retbytes and $range values.
And I saw that $retbytes contains block addresses, and $range is always empty. This is a clear mistake!

Try downloading the zip-file (300-500 mb) using Internet Download Accelerator and you should be able to see this bug. The file will hang on the last byte, and then it will not be unpacked.
This is not a bug of Internet Download Accelerator, other similar programs (eg Free Download Manager by Softdeluxe) have exactly the same problem.

**Comment by TeoAlex** [comment]
I was able to reproduce the first error ( the download hanging at 99% problem ) .
The corrupted archive ( .zip file ) error could not be reproduced as the downloaded test archives are unpackable.

**Comment by f2065** [comment]
I still have a problem with corrupted files.
How can I demonstrate this?
Show any of your sites where I can download (via Download Monitor, with 99 percent fixed the problem) some zip archive larger than 50 MB?

Here is Download Monitor Version 4.5.91 with manually fixed "$range_end = $version->get_filesize();"
https://f2065.ru/en/android/android_m2_en/
Download with Internet Download Accelerator any big zip (lineage-15.1-20220311-UNOFFICIAL-eagle.zip for example) and try to unpack it. There will be a file unpack error.
And if you download it in one stream using the standard Chrome download, the archive will be normal.

**Comment by f2065** [comment]
I downloaded current version 4.5.92, the problem is solved, the files are downloaded without damage, the download does not freeze. Thanks.

**Comment by razvanaldea89** [comment]
The fix will need to take into consideration the scenario where the user changes the file directly.  @TeoAlex  see #860
