### ISSUE TITLE
Onboarding page

### ISSUE THREAD

**Issue by giucu91** [WPChill/download-monitor#820]
url: wp-admin/edit.php?post_type=dlm_download&page=dlm_onboarding

We can improve this screen.

![screencapture-test-avianstudio-wp-admin-edit-php-2022-01-21-16_15_34](https://user-images.githubusercontent.com/7580330/150541924-b8138742-bf30-450e-972e-868dc205ac5a.png)

**Comment by cdillon** [comment]
The Downloading Page description has extra `<p>` tags.
![2022-02-01_11-54-52](https://user-images.githubusercontent.com/3716267/152013838-9670ed66-3253-47f7-b985-32e1b8bd6a44.png)
.

**Comment by cristianraiber** [comment]
@cdillon - this should be fixed in another branch but can't remember exactly which one. 

cc @razvanaldea89

**Comment by razvanaldea89** [comment]
Already fixed in master branch and will be present in next update

**Comment by TeoAlex** [comment]
The escaping error fix was launched.

**Comment by razvanaldea89** [comment]
@giucu91 @cristianraiber Think it's better to remove the first paragraph, with the Welcome text, as now we have a new and improved Welcome page. Furthermore, the onboarding page will be removed in a future update and in it's place will be implemented in the new Welcome page a widget with a wizard that will guide the new user through the process of creating the required pages, required settings and a new download post. 

![image](https://user-images.githubusercontent.com/44024114/162147279-5c4b71b5-841b-4580-b380-89677cec89f8.png)

**Comment by razvanaldea89** [comment]
New looks of the onboarding page and welcome page

![image (1)](https://user-images.githubusercontent.com/44024114/162192923-483e6f3d-f434-408b-9b58-c36ad93af00f.png)
![image](https://user-images.githubusercontent.com/44024114/162192931-d4f6f712-7f7a-4046-ba84-01894274743b.png)

**Comment by cristianraiber** [comment]
👍
