### ISSUE TITLE
Show shortcode on "all posts" page

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#821]
Right now, you have to click on "edit" for a download to fetch it's shortcode

![image](https://user-images.githubusercontent.com/7841556/150940858-057d85f6-79f7-4287-8606-f76ae13a9023.png)

**Comment by razvanaldea89** [comment]
Seems this has slipped into version 4.5.5 and categories have been removed from the admin list view columns. Going to be placed back with version 4.5.6, due to be launched on 14.03.2022

**Comment by razvanaldea89** [comment]
Copy shortcode functionality has been changed, now an icon with a tooltip is displayed, and clicking the icon will copy the shortcode. 

After:
![image](https://user-images.githubusercontent.com/44024114/157642326-af868475-c780-400f-8182-4a039d7ea7ad.png)

Before:
![image](https://user-images.githubusercontent.com/44024114/157642378-54953b99-f341-4528-af57-9f768d605135.png)
