### ISSUE TITLE
Gutenberg advanced class input not used

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#822]
The plugin offers an input for adding extra classes to the block but is not used anywhere:

![image](https://user-images.githubusercontent.com/44024114/150973799-526f22e9-9048-4a6c-a7fc-2580ce973bb4.png)

**Comment by andyluak** [comment]
Because we use templates / custom templates , we have no way to programmatically add custom classes at least to custom templates and because there is quite limited capability to what we can remove from core ( Advanced Tab ) we are not able to remove the tab also.
