### ISSUE TITLE
reports date bug

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#823]
if you use WP 5.9 and go to Downloads > Reports > change the reports date:
<img width="1261" alt="Screenshot 2022-01-27 at 13 21 20" src="https://user-images.githubusercontent.com/26008574/151349207-7179825e-0222-4ab8-b33f-10ad62a0f24d.png">

It will throw an error
<img width="1277" alt="Screenshot 2022-01-27 at 13 22 07" src="https://user-images.githubusercontent.com/26008574/151349340-9967621f-df41-4c8c-8998-c18f92d3f823.png">

2 more users reported this as well

**Comment by cristianraiber** [comment]
@razvanaldea89 - can you please check and see if this happens w/ DLM 4.5.x?

**Comment by razvanaldea89** [comment]
Should not be a problem as the whole functionality has been changed

**Comment by cristianraiber** [comment]
@razvanaldea89 ease test this and reply back with your findings

**Comment by razvanaldea89** [comment]
Sorry about that, thought you were mentioning the new reports. Yes, bug seems to be happening. I'll continue the investigation and issue a commit with a fix regarding this.

**Comment by beatricelucaci** [comment]
+1
https://secure.helpscout.net/conversation/1776594200/44216?folderId=4656047

**Comment by janeblonde** [comment]
Hi Guys, If you have an update I'm happy to test on our staging server.
D

**Comment by cristianraiber** [comment]
@janeblonde - feel free to pull the `master` branch and test. That contains the fix you're looking for :) 

Also, branch v4.5.0 has the new (and upcoming) reports if you want to take a peek ;)

**Comment by janeblonde** [comment]
@cristianraiber worked a treat, thanks!

**Comment by cristianraiber** [comment]
@janeblonde - thanks for helping w/ the testing :)

**Comment by janeblonde** [comment]
@cristianraiber no trouble at all, feel free to buzz me if you need any testing in future

**Comment by cristianraiber** [comment]
@janeblonde - could you please test the 4.5.0 branch as well? <3 We have an entirely new reports feature there that's (yet) unreleased as well as a very different way of handling file downloads (using XHR instead of forcing server) 

I'm most interested in what you could find for the reports feature.

**Comment by janeblonde** [comment]
@cristianraiber  - I've uploaded to our stage and ran a general test, specifically I've tested the reports which is much cleaner than the old version which didn't fit the screen. Now the refreshed version is much better, I've tested back a few years and the results are clear, see: https://prnt.sc/26wdptz

**Comment by cristianraiber** [comment]
@janeblonde - did the upgrade procedure work flawlessly? Fid yiu encounter any data mismatch? Any issues?

The new reports functionality works on custom tables and uses the REST API. 

Could you also please send over a screenshot of the new reports area on your staging site?

**Comment by janeblonde** [comment]
@cristianraiber - this screen shot is of the reports area, did you mean something else? https://prnt.sc/26wdptz
On the staging server I uploaded the file download-monitor-4.5.zip. It installed a duplicate plugin. I disabled the original and tested.

Since then I've renamed the original folder and also renamed "download-monitor-4.5" to "download-monitor".

I have since created a new install file with just download-monitor and re-installed without a problem, here's the result: https://prnt.sc/26wfc8x

**Comment by cristianraiber** [comment]
Yeah, you got the wrong branch :D But that might be my fault. In the meantime, I renamed the 4.5.0 branch to 4.6.0. 

This branch holds the new reports feature that is very different from what you are showing in those screenshots.

**Comment by razvanaldea89** [comment]
Launched

**Comment by cristianraiber** [comment]
@janeblonde - this is a development version and not yet final. I hipe you didn't install this on your main site unless you like to live on the edge :D

**Comment by janeblonde** [comment]
Installed on live before I realised it, very glad it worked.

**Comment by cristianraiber** [comment]
🙈
