### ISSUE TITLE
Download Monitor endpoint is already in use by a page or post.

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#826]
On the Settings page I see an error message: “The Download Monitor endpoint is already in use by a page or post. Please change the endpoint to something else.”
https://wordpress.org/support/topic/download-monitor-endpoint-is-already-in-use-by-a-page-or-post/

He says:  I found a file, “download.jpg”, in my Media Library with title “download”.
This error should not appear if it is  a file with the from media library with title 'download', only if it is a page or a post

**Comment by Slapbox** [comment]
Still seeing this issue here. Have had it for years and it's not resolved for us even in `4.8.x`. We used to have a page that pointed to the endpoint name but after changing it and re-applying permalinks in Settings the issue persists.

**Comment by razvanaldea89** [comment]
Hello @Slapbox ,

Could you please give more info? Does the download work after you changed the endpoint? Is there a possibility where you can change the Download Monitor's endpoint and check if everything is working OK? 

Should have worked if you have changed the slug of the page and not only the title. Once you create a page in WordPress, you can rename the title as many times as you can but the slug remains the same, you have to manually change that too. Can you confirm you have changed the slug also?

Warmly,
Razvan

**Comment by Slapbox** [comment]
The downloads work in spite of the message. I'm hesitant to try changing the endpoint on a production machine given some difficulty keeping the plugin working as intended historically.

When I changed the page's slug, I only changed the slug, not the actual name. The page which previously used that endpoint is also only a draft (and again, downloads work even if the page does actually use the slug)
