### ISSUE TITLE
Extensions page seem distorted 

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#831]
Can't replicate on Windows OS with Firefox or Edge, problem seems to be on Mac OS with Safari.

![image](https://user-images.githubusercontent.com/44024114/152994530-91a8690c-e88a-440e-909a-2d0f4baa134c.png)

**Comment by cristianraiber** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/7841556/154227395-d3c685c2-f67a-46b1-9a9c-aff1476bc023.png)

**Comment by cristianraiber** [comment]
Tested, looks good.

**Comment by razvanaldea89** [comment]
Launched
