### ISSUE TITLE
When only 1 content locking plugin is active, the sub-nav doesn't show up. 

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#838]
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/7841556/153727043-880e6081-4eca-4b30-a9ab-215e7a1bded1.png">

**Comment by razvanaldea89** [comment]
Reverted the change, commit https://github.com/WPChill/download-monitor/commit/21394ded7266b64c0724b171b4b8e674c6510938 solved the issue as we need upsells.
