### ISSUE TITLE
Delete "redirect to file" option and associated code once we merge XHR into core

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#842]
I think this should be also removed if the XHR download method gets merged into core: 

![image](https://user-images.githubusercontent.com/7841556/154073750-2d6ad5fb-700d-4718-8861-f1ef4808f2f4.png)

**Comment by cristianraiber** [comment]
It is my understanding that by using this (less secure) method, the actual file URL is being exposed in the redirect. 

Can someone please confirm that this doesn't happen w/ the new XHR implementation of starting downloads?

**Comment by cristianraiber** [comment]
I think this should be also removed if the XHR download method gets merged into core: 

![image](https://user-images.githubusercontent.com/7841556/154073750-2d6ad5fb-700d-4718-8861-f1ef4808f2f4.png)

**Comment by razvanaldea89** [comment]
@cristianraiber this should be kept as there are users, and not a small number, that use this functionality. Redirect has been implemented in the XHR and it records the correct status. Going to close this.
