### ISSUE TITLE
add target="_blank" to shortcode

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#853]
I was wondering if there is a chance to add a target="_blank" (open in a new window) to shortcode? Or how do you advise us to do it?
https://secure.helpscout.net/conversation/1794376571/44761?folderId=4656047

**Comment by razvanaldea89** [comment]
@cristianraiber could you give more details about what you had in mind for this one? `target="_blank"` is useful on redirects, but that can be accomplished by overwriting the Download Monitor's template in a child theme.

**Comment by cristianraiber** [comment]
@razvanaldea89 - there's a helpscout ticket above. I didn't open this ticket, @beatricelucaci did.

**Comment by razvanaldea89** [comment]
@cristianraiber yes, but you said to open ticket and there's not much info in the ticket

**Comment by cristianraiber** [comment]
I think they wanted to start a download in a new window

**Comment by razvanaldea89** [comment]
Override the template and add target blank for now. Going to close this as there is another ticket opened.
