### ISSUE TITLE
Shop enabled => create a new tab

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#858]
1. Enable shop
2. main-level tab gets created
3. gets "settings" sub-tab that holds current "Shop" tab settings
4. Payment methods tab gets merged w/ Shop tab and all payment methods become sub-nav entries

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/155139892-4e0d19e5-648c-43a0-85d3-5f0ccedfedc9.png)

**Comment by cristianraiber** [comment]
Quick mock-up I did to better illustrate the concept.

**Comment by cristianraiber** [comment]
Test payment gateway should live under the "PayPal" subnav menu entry as it's related to ONLY PayPal.

**Comment by razvanaldea89** [comment]
Added possibility to sort tabs. Moves Shop pages to Shop tab > Pages
