### ISSUE TITLE
does not work when changing the file directly from ftp

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#860]
we have an issue where we've linked existing documents to the download - which uses the server path to the file and works fine. The problem is when we replaced that document file directly via FTP - the download fails with the Chrome error "Failed - Network error". If we just "Update" the download page, without making any changes to the file or page itself, then the download works as expected. If there anyway to allow the download to continue working when the file is replaced without having to "re-save" the download page?

**Comment by razvanaldea89** [comment]
Also, I think the same thing happens if the file is modified in size by some compression/optimization service/plugin ( see https://wordpress.org/support/topic/failed-network-error-5/page/2/#post-15486662  )
