### ISSUE TITLE
cannot add file

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#863]
**Describe the bug**
I wanted to add a file and I went to Downloads > Edit > Downloadable Files > Upload file > selected a PDF >  an error occurred
This is also happening if I want to add an image, an Excel or a document.
https://secure.helpscout.net/conversation/1802549587/44982?folderId=4656047

**Screenshots**
![image](https://user-images.githubusercontent.com/84579642/156521104-4c0c6e76-a8a1-4d48-a73c-b5005af30663.png)

**Comment by mplusb** [comment]
+3

**Comment by beatricelucaci** [comment]
+1
https://secure.helpscout.net/conversation/1805845904/45066?folderId=4638438

**Comment by beatricelucaci** [comment]
+1 
https://secure.helpscout.net/conversation/1808141578/45130?folderId=4638438
