### ISSUE TITLE
Change Downloads list table icons and placement

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#867]
**Is your feature request related to a problem? Please describe.**
Members => Lock - and show when a download is locked, no matter how ( email locked, members only, paid only... )
File will go underneath the Title
ID -> removed, we will have the copy shortcode functionality ( or added in the title before the name of the download )

**Comment by razvanaldea89** [comment]
@cristianraiber @giucu91 @TeoAlex @andyluak any thoughts, ideas, opinions on this one?

**Comment by cristianraiber** [comment]
I think this is a good idea.

**Comment by TeoAlex** [comment]
Did not make the "Lock" change as we need every locking plugin to add a locked status to the download and this change must be done at first in the plugins.
