### ISSUE TITLE
Add do_actions in shortcodes so we can add scripts

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/download-monitor#868]
**Is your feature request related to a problem? Please describe.**
Adding js/css scripts only on shortcode load

**Describe the solution you'd like**
Add do_action in plugin shortcodes.

**Describe alternatives you've considered**

**Additional context**

**Comment by razvanaldea89** [comment]
Added function for all shortcodes. should be in the form of `dlm_{shortcode}_shortcode_scripts`,; where `{shortcode}` stands for the shortcode used
