### ISSUE TITLE
the 'uploaded' file's #number differs from the one shown as being the code target for the download monitor

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#876]
**Describe the bug**
the 'uploaded' file's number (ID) differs from the one shown as being the code target for the download monitor
example: 
<img width="1257" alt="Screenshot 2022-03-23 at 16 18 19" src="https://user-images.githubusercontent.com/26008574/159720807-7a7cab79-c9fe-4d22-a308-85598871f738.png">

**To Reproduce**
1. add a new download
2. upload files

**Expected behavior**
it should keep the same id

**Extensions installed and activated:**
- [ ] Advanced Access Manager
- [ ] Amazon S3
- [ ] Buttons
- [ ] Captcha
- [ ] CSV Exporter
- [ ] CSV Importer
- [ ] Downloading Page
- [ ] Email lock
- [ ] Email Notifications
- [ ] Google Drive
- [ ] Gravity Forms
- [ ] Mailchimp
- [ ] Ninja Forms
- [ ] Page Addon
- [ ] Terms & Conditions
- [ ] Twitter Lock

**Additional context**

**Comment by razvanaldea89** [comment]
The ID from the right, the shortcode one, is the ID of the download and the ID from the left is the ID of the version. The only relation they have is that the download is a parent of the version. Going to close this.
