### ISSUE TITLE
loop_start and loop_end not working when shortcode is in template

### ISSUE THREAD

**Issue by nitrokevin** [WPChill/download-monitor#877]
**Describe the bug**
Adding shortcode to template, loop start / loop end don't have any effect

**To Reproduce**
`<?php 
    $resourcecategory = get_sub_field('resourcecategory');
    $slug = $resourcecategory ->slug;
   echo do_shortcode( "[downloads category='$slug' loop_start='<ul class=\'glide__slides\'>' loop_end='</ul>' template='resource']" );
				?>`

**Expected behavior**
Want to add glide__slides class to the ul

**Comment by razvanaldea89** [comment]
Please use double quotes as the parameters for `loop_start` and `loop_end` are more complex. So, your shortcode should become : 

`echo do_shortcode( "[downloads category='$slug' loop_start=\"<ul class=\'glide__slides\'>\" loop_end=\"</ul>\" template='resource']" );`
