### ISSUE TITLE
On empty lists we could use a creation form the same way WP Forms uses

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#882]
If there are not posts created we could use a creation form the way WP Forms uses, which could extend the possibilities to let the users discover our functionalities, features and addons.

![Screenshot 2022-04-05 163020](https://user-images.githubusercontent.com/44024114/161765553-d0a26950-20f8-4331-b4bf-363e45717fae.png)

**Comment by razvanaldea89** [comment]
Onboarding banner needs replacement, currently used the one from Modula

**Comment by incredibeary** [comment]
<img width="962" alt="DLM-onboarding-illustration@2x" src="https://user-images.githubusercontent.com/112502248/210517696-271b7767-a3d9-4bb6-95ff-79c4b007f740.png">

**Comment by razvanaldea89** [comment]
![image](https://user-images.githubusercontent.com/44024114/210543309-d6f5d21c-e365-4054-abc7-d8ea492e23be.png)
