### ISSUE TITLE
Critical error in admin area after upgrade to 4.5.9

### ISSUE THREAD

**Issue by globdug** [WPChill/download-monitor#883]
Hello, after upgrading to 4.5.9 I cannot access dashboard anymore.
I had to delete via ftp _download-monitor_ folder in _plugins_.

After deleting the folder, I entered correctly the dashboard, and reinstalled 4.5.8 version, everything works good. I tried to update again to 4.5.9, and again cannot access anymore the dashboard.

I also tried to upload directly the 4.5.9 version, but it doesn't work.

The error I received via mail is:
```
Dettagli dell'errore
====================
Un errore di E_ERROR è stato causato nella linea 555 del file [...]/wp-content/plugins/download-monitor/src/Admin/Settings/Page.php. Messaggio di errore: Uncaught Error: Cannot use object of type WP_Error as array in [...]/wp-content/plugins/download-monitor/src/Admin/Settings/Page.php:555
Stack trace:
#0 [...]/wp-includes/class-wp-hook.php(307): DLM_Settings_Page->robots_files_checker_field(Array)
#1 [...]/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#2 [...]/wp-content/plugins/download-monitor/src/Admin/Settings/Settings.php(475): apply_filters('dlm_settings', Array)
#3 [...]/wp-content/plugins/download-monitor/src/Admin/Settings/Settings.php(23): DLM_Admin_Settings->get_settings()
#4 [...]/wp-includes/class-wp-hook.php(307): DLM_Admin_Settings->register_settings('')
#5 [...]/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#6 [...]/wp-includes/plugin.php(474): WP_Hook->do_action
```

**Comment by razvanaldea89** [comment]
Hello @globdug ,

Thanks for the info. We'll take a look and issue an update ASAP

**Comment by razvanaldea89** [comment]
Hello @globdug ,

An update has been released and should solve the problem you are experiencing. Please let us know if this has solved you problem.

Kind Regards!
Razvan

**Comment by razvanaldea89** [comment]
Our pleasure. Have a wonderful day!

Razvan
