### ISSUE TITLE
Similar title column to products as downloads ( id and title )

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#885]

**Comment by jmslbam** [comment]
I'm gettings an error,  because of this code 
![image](https://user-images.githubusercontent.com/145887/162730346-ea40d325-b971-433b-961d-14a1febe48c5.png)

**Comment by jmslbam** [comment]
How can this code be in 4.5.91 while it's not in the "master" branch and this issue still has "needs testing" / "bug"

https://github.com/WPChill/download-monitor/blob/4.5.91/src/Admin/CustomColumns.php#L9

**Comment by razvanaldea89** [comment]
Hey @jmslbam ,

You are getting that error most likely because on your theme or some plugin the WP Core `the_title` filter is not used correctly, mainly it doesn't have 2 arguments as it says in the documentation you can read [here](https://developer.wordpress.org/reference/hooks/the_title/).

Also, this is not yet released, it is not present the 4.5.91 version of the plugin. What you are referring to is the https://github.com/WPChill/download-monitor/issues/867 issue that was included in the 4.5.7 release.

Warmly,
Razvan
