### ISSUE TITLE
No file provided notice for empty file paths

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#887]
**Is your feature request related to a problem? Please describe.**
If there are no file paths declared for a download we should display a notice for the user to see in the place where the file should be, with red color saying : `no file provided`

![CleanShot 2022-04-05 at 15 18 03@2x](https://user-images.githubusercontent.com/44024114/161776863-d3148be3-aba9-40dc-bbd5-3c0d80c842fe.jpg)

**Comment by jaxne** [comment]
We updated our plugin today and ran into permission issues. We also found adding a file from the media library did not save the path and ended up showing up like your screenshot. We ended up reverting to a backup of the site as I could not figure out the issue and the client needed to have customers access the 70 or so user documents for their products.  Today after the update we either received a "No access to this file. Return to homepage ->" message or "no file path" message on those entries we tried to update.  I tried troubleshooting to see if there was a plugin conflict use Site Health but even with just Download monitor installed only and basic WP theme Twenty Twenty Two, same issue.  We have a clone of the broken site waiting to test and see if next patch/update will resolve this before we update any of our live sites.  Glad it wasn't just us ;)

**Comment by razvanaldea89** [comment]
Hello @jaxne ,

The 4.5.9 update was released with a security fix that targets files that are out of root folder ( where WordPress is located ) or restricted files, like the `wp-config.php`, or `php.ini` an such. Files from the Media Library or uploaded directly from within editing the Download should not cause any problems and the paths should save relative to the root or, if they are remote, as external URL.

**Comment by jaxne** [comment]
Thanks @razvanaldea89  --    After we ran the update earlier today is when we had issues with all of our documents.  I created a staging site with v4.5.91 of Download Monitor installed.  Here's the support page with different user manuals. 

https://hanspremiumwater-staging.mystagingwebsite.com/support/

You'll see the link /download/####/ format we have setup on all of the user manual thumbnails. ALL of these PDFs are located in the standard WP Media Library /wp-content/uploads/_year/month/filename.ext_ path. We hadn't changed anything else earlier today.  The links are set to open the the link in a new tab and redirect to the file (vs. forcing the download).   We do not have plugins modifying the location of the uploads folder. It's the default upload location format of WP.  It is a NGINX server as we host thru Pressable.

As I mentioned, after I started testing, I tried to re-ad a Media Library file PDF to one of the download Monitor posts, but the file (path) never saved right and then wouldn't show on the All Downloads list under the title of the the download.  Not sure if that gives you enough extra information.  Here's a quick screen recording when I try to add a new Download and add a PDF from the WP Media library. You'll see that it acts like it adds it but it doesn't. Path disappears and doesn't save.
https://www.dropbox.com/s/ebjlvhzijvz29hb/HPW-Staging-MissingFile.mp4?dl=0

I do have a Pro license of Download Monitor and will submit a support ticket. Right now we're on hold to run the update until we can be sure we won't have this issue. We have 2 other sites with a similar set up.  Thx.

**Comment by razvanaldea89** [comment]
Thanks for the info. Is it possible to give us a SS with the directory of the WordPress installation? Go to dashboard > Tools > Site Health > Info > Directories and sizes. Also, if you use the `Browse for file` button to include the file you need, does it work? Could you also make a video using the `Browse for file` button? Really appreciate it.

Kind Regards!
Razvan

**Comment by razvanaldea89** [comment]
@jaxne could you tell me if your `wp-content` folder is located outside of your WordPress installation folder?

**Comment by jaxne** [comment]
@razvanaldea89  -  I just replied to Beatrice on the DLM support team.  Also just found this, could it be the Pressable configuration with that security update that was made in 4.5.91?
https://pressable.com/knowledgebase/abspath-and-pressable/#overview

**Comment by razvanaldea89** [comment]
Hey @jaxne , 

Yes, that is the scenario here. There is an update prepared ( https://github.com/WPChill/download-monitor/commit/3abb64456bdb1846b447d6eb982061da88a278a4  ) that most probably will be launched tomorrow that will address this situation and other situations where the `wp-content` directory is moved outside of the root

**Comment by jaxne** [comment]
Hi @razvanaldea89  ---  Beatrice mentioned an update was being released here very soon. Any ETA?  I have one other site on the same Pressable platform with the same issue.  Thanks!

**Comment by timbrisc** [comment]
Hello, I am having the same or a similar issue. I just upgraded to DLM to 4.5.91 and it broke downloads across our site. We also have files located outside the web root, not even within wp-content. This made the most sense for us in order to programmatically deploy new file versions and ensure the files are not accessible outside of DLM.

We have rolled back to 4.5.8 and all is well. Will our use case of files not located in the web root continue to work in future versions of DLM? Many thanks.

**Comment by razvanaldea89** [comment]
Hello,

A solution has been found  ( branch : https://github.com/WPChill/download-monitor/tree/4.5.92-release  ) and we are currently testing it. If anyone is interested and wants to test and see if it solves your problem, if you have a staging site, like @jaxne has, feel free to try it out and let us know if the problem still persists after the update or was is solved.
As an update we have implemented a new setting in dashboard > Settings > Advanced > Advanced where an admin can specify another path ( besides the ABSPATH - root -  and WP_CONTENT_DIR - usually the uploads -  ) if you want to download files from other paths.

Warmly,
Razvan
