### ISSUE TITLE
Missing files / Access denied for users who put their wp-content folder outside of the WordPress installation

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#888]
**Describe the bug**
If the user moved the `wp-content` folder outside the WordPress installation folder ( root ) the file will enter in restriction mode as the function will detect that it's not part of the root folder.

**To Reproduce**
1. Move `wp-content` folder outside the WordPress installation folder ( example here : https://totalwebsecuritypro.com/how-to-move-wp-content-folder-out-of-wordpress-directory/ )
2. Try to save or download

**Comment by razvanaldea89** [comment]
Launched in version 4.5.92

**Comment by codepuncher** [comment]
@razvanaldea89 this still seems to be broken for me; I am getting "Access denied" using this version.

I am using [Bedrock](https://github.com/roots/bedrock) if that helps to understand the structure/issue.

**Comment by razvanaldea89** [comment]
Hey @codepuncher ,

Could you please tell me where are you trying to get the downloadable files from? Is it somewhere from outside the root?

**Comment by codepuncher** [comment]
Typical WP directory structure:
```tree
site # this is the webroot, so files/directories here are publically accessible
└── wp-content/
    └── uploads/
        └── dlm_uploads/
```

Bedrock file structure:
```tree
site
└── web/ # this is the web root, so files/directories here are publically accessible
    └── app/
        └── uploads/
            └── dlm_uploads/
```

**Comment by razvanaldea89** [comment]
@codepuncher are you using this on live server or on localhost? If localhost, is the localhost on Windows machine or on something based on UNIX?

@codepuncher @nialape could you please go to dashboard > Tools > Site Health > Info > Directories & sizes and take an screenshot and post it here so we can take a look? If you are not comfortable showing them here please use the form [here](https://www.download-monitor.com/contact/), specify the tichet URL and that the screenshots are for Razvan :D and my colleagues will do the rest.

Regarding Bedrock, just tested and it might be an issue with Windows OS regarding the directory separator ( thus the questions with the localhost ), there is a fix with a newly added setting in version 4.5.92 but first I want to make sure because that modification is a major one.

Warmly,
Razvan

**Comment by nialape** [comment]
Here is attached the screenshot of my wordpress install showed on a FTP client. (The "?" mark is a link). It's  hosted on the unix server of my provider ovh.com. It's a standard install of wordpress 5.8.4. All worked fine until I install the new version of donwload monitor. I used the new option of download monitor and entered /www/wp_content/uploads/ for the path. Thanks.
![directories](https://user-images.githubusercontent.com/103521646/163115106-81ef59e9-ed80-432f-9a30-b8b9c1e07138.jpg)

**Comment by razvanaldea89** [comment]
Hello @nialape ,

Could you please explain a little so I can undestand the full functionality? I am not quite sure I understand the `link` part. So the `index.html.old.ovh` is a file and you want to download it and it doesn't download, it says Access denied?

**Comment by nialape** [comment]
Hello, sorry for my misunderstanding. I sent the standard wordpress hierarchy of my server that was catched throught a FTP client. All my downloadable files are in www/wp-content/uploads/uploads/year/month/... or dlm_uploads/year/month as you could see. Forget other part of the hierarchy. All downloadable files are jpg or pdf files. I don't have an Access denied message but a "404 error, not found" file for all files I have entered since 2015. Mainly, these pdf files are displayed in a "page" by a "pdf plugin" and with a "download_monitor" link to download it. So all the files on my server are accessible and displayed but not accessible by "download monitor"! Don't hesitate to ask me again if I didn't explain correctly.

**Comment by razvanaldea89** [comment]
Oh... If you go to dashboard > Permalinks > Click save without modifying anything does it solve your problem?

**Comment by nialape** [comment]
Yes that was it! So it's not download-monitor's problem! May be wordpress upgrade did this and don't keep previous setup. Anyway thanks a lot to solve my problem!

**Comment by razvanaldea89** [comment]
@nialape glad to be of help! 

@codepuncher any progress on your issue?

**Comment by codepuncher** [comment]
@razvanaldea89 
It's a Linux staging server, parity with the live environment.

WordPress directory location | /www/project-name-redacted/public/releases/20220412102803/web/wp
-- | --
WordPress directory size | 67.50 MB
Uploads directory location | /www/project-name-redacted/public/releases/20220412102803/web/app/uploads
Uploads directory size | 1.40 GB
Themes directory location | /www/project-name-redacted/public/releases/20220412102803/web/app/themes
Themes directory size | 28.38 MB
Plugins directory location | /www/project-name-redacted/public/releases/20220412102803/web/app/plugins
Plugins directory size | 174.37 MB
Database size | 686.66 MB
Total installation size | 2.34 GB

Note: `/www/project-name-redacted/public/releases/20220412102803/web/app/uploads` is a symlink to `~/public/shared/uploads`.

**Comment by razvanaldea89** [comment]
@codepuncher if you enter the real path to the directory containing the downloadable files in dashboard > Downloads > Settings > Advanced  > Miscellaneous > Other downloads path does it solve your problem? This should add another path to the `allowed downloadable file paths` for the directory itself and for it's children. 

 Attention, first do this only on the staging site and after a database backup as it is a major change that can not be undone easily.

**Comment by codepuncher** [comment]
@razvanaldea89 is there a PHP constant that I can use to set this? I don't have access to the web interface at the moment so I'm unable to change settings via UI. I'd prefer to define the path using PHP anyway; this way I can automate things for all projects more easily.

**Comment by cristianraiber** [comment]
@razvanaldea89 - this is actually a really good idea

**Comment by razvanaldea89** [comment]
We have not included a filter for the allowed paths for security reasons. Mainly, all these major changes regarding how we look at files and how we consider allowed paths have been a consequence of what we should and should not allow for download.  A filter for the allowed paths could be used by infected/Mal-intended plugins in the loss of the site owner.

But I'll talk to my colleagues @cristianraiber & @giucu91 about this and we'll see if there is a possibility to add such a filter.

Warmly,
Razvan.

**Comment by codepuncher** [comment]
I have added the download path to the UI setting and it has resovled the issue. Thank you.

However, it will not be ideal to use the UI for this in my scenarios; when you have many clients relying on the plugin and the path will be different per site it will be a source of frustration to keep editing via the UI.
If this could be done with a constant or filter that would be preferred. This way things can be automated and never have to insert a custom path; codebase will always contain it.

Whilst it's true that a plugin could change this, I don't think it's a likely enough scenario that would mean it's not worth adding.

Perhaps instead of a filter, a constant would be better? If I have defined mine, then no one can overwrite it; doing so will result in a PHP error and the site owner will be aware of this. A filter on the other hand can be modified multiple times.

Thanks

**Comment by codepuncher** [comment]
Hi @razvanaldea89 - can I ask why this was closed?

**Comment by razvanaldea89** [comment]
The problem that this issue was mentioning is solved, going to make another issue regarding the filter/constant you mentioned so that we can view things more clear and jump straight to the problem.

**Comment by codepuncher** [comment]
Ah, brilliant. Many thanks @razvanaldea89
