### ISSUE TITLE
 open_basedir issue

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#890]
**Describe the bug**
Hello, I’m using latest version of Download Monitor. Now if I make new download in my WP admin and I click “Publish” it show some PHP errors like Warning: file_exists(): open_basedir restriction in effect…. (see attached screenshot – https://ibb.co/K9y7BDG).

It affects only new download. The old ones on my website work correctly.
PHP version is 8.0.17.

Edit: same problem on my another website https://www.zskratka.cz/  try this: https://www.zskratka.cz/download/18423/

**Screenshots**
<img width="1399" alt="Screenshot 2022-04-07 at 12 58 54" src="https://user-images.githubusercontent.com/26008574/162174136-e9e784a2-a675-4c01-996b-478bfd55ca10.png">

**Extensions installed and activated:**
- [ ] Advanced Access Manager
- [ ] Amazon S3
- [ ] Buttons
- [ ] Captcha
- [ ] CSV Exporter
- [ ] CSV Importer
- [ ] Downloading Page
- [ ] Email lock
- [ ] Email Notifications
- [ ] Google Drive
- [ ] Gravity Forms
- [ ] Mailchimp
- [ ] Ninja Forms
- [ ] Page Addon
- [ ] Terms & Conditions
- [ ] Twitter Lock

**Additional context**
https://wordpress.org/support/topic/open_basedir-issue/

**Comment by razvanaldea89** [comment]
This seems to be a server configuration, a security measure to disallow file access, and the path to the files are not in the allowed paths defined by the server, thus triggering this error. `open_basedir` restrictions should be removed or paths should be added to the allowed paths.

**Comment by razvanaldea89** [comment]
Hey @janrichtercz, a fix will be coming with the next update which we hope will solve these problems.
