### ISSUE TITLE
Displaced page title on no-access page, when accessed directly

### ISSUE THREAD

**Issue by zitrusblau** [WPChill/download-monitor#894]
**Describe the bug**
Displaying the no access page without providing download ID parameter gives layout bugs. The output buffer is enabled before the return statement. I know this is rather unlikely but still, fixing this behaviour ist easy.

**To Reproduce**
1. Go to the page which was setup for 'no access', directly opening the URL, ie. https://local.dev/no-access without providing any URL parameter "download-id".

**Expected behavior**
Clean layout which was set in the theme with title and content shown and within the correct HTML containers. Instead, the page title is displaced and no additional (custom) page content is shown. Also, a general notice would be a better UX in case this happens.

**Screenshots**

**Extensions installed and activated:**
none

**Additional context**
The starting output buffer call should come after the return statement in inc/Shortcodes.php around lines 542-551.

**Comment by razvanaldea89** [comment]
Can't replicate or was fixed in the meantime

**Comment by zitrusblau** [comment]
Ok, then the issue is quite likely related to using sage 10 starter theme.

see #1169
