### ISSUE TITLE
DLM reports: date range select design

### ISSUE THREAD

**Issue by giucu91** [WPChill/download-monitor#897]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/7580330/163567260-33aed556-5a33-4592-bc14-03fca4345f14.png">

<img width="510" alt="image" src="https://user-images.githubusercontent.com/7580330/163567387-3051a326-9925-4080-9e5c-83dbf499d2e6.png">

We should keep the default design

**Comment by mplusb** [comment]
user feedback: add a simpler way where I can change month and year via drop-down. 

I use it several times per week and i need to go back to July 2019 to see the summ of downloads since the page exists. That takes many clicks.

**Comment by razvanaldea89** [comment]
Conflict with #736
