### ISSUE TITLE
DLM Reports - download status & IP

### ISSUE THREAD

**Issue by giucu91** [WPChill/download-monitor#898]
We should have 3 diffenret statuses : 
- downloaded
- redirected ( we don;t know for sure if it was downloaded )
- failed

**Comment by giucu91** [comment]
we should keep for now IP

**Comment by razvanaldea89** [comment]
The 3 statuses will be :

- completed ( to keep backwards compatibility with older DB and extensions )

- redirected ( we don;t know for sure if it was downloaded )

- failed
