### ISSUE TITLE
does not work with Awesome support - fatal error

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#903]
**Describe the bug**
when you activate awesome support and add a new ticket > you will see notice it causes an error in the newly added ticket
error:

Fatal error: Uncaught ArgumentCountError: Too few arguments to function DLM_Custom_Columns::prepend_id_to_title(), 1 passed in wp-includes/class-wp-hook.php on line 307 and exactly 2 expected in /wp-content/plugins/download-monitor/src/Admin/CustomColumns.php:179 Stack trace: 0 /wp-includes/class-wp-hook.php(307): DLM_Custom_Columns->prepend_id_to_title('test') 1 /wp-includes/plugin.php(189): WP_Hook->apply_filters('test', Array) 2 /wp-content/plugins/awesome-support/includes/admin/metaboxes/user-profile.php(146): apply_filters('the_title', 'test') 3 /wp-content/plugins/awesome-support/includes/admin/functions-metaboxes.php(91): include_once('/home/domeniu/...') 4 /wp-admin/includes/template.php(1395): wpas_metabox_callback(Object(WP_Post), Array) 5  in /wp-content/plugins/download-monitor/src/Admin/CustomColumns.php on line 179

**To Reproduce**
1. activate awesome support and add a new ticket > you will see notice it causes an error in the newly added ticket

**Extensions installed and activated:**
- [ ] Advanced Access Manager
- [ ] Amazon S3
- [ ] Buttons
- [ ] Captcha
- [ ] CSV Exporter
- [ ] CSV Importer
- [ ] Downloading Page
- [ ] Email lock
- [ ] Email Notifications
- [ ] Google Drive
- [ ] Gravity Forms
- [ ] Mailchimp
- [ ] Ninja Forms
- [ ] Page Addon
- [ ] Terms & Conditions
- [ ] Twitter Lock

**Additional context**
https://wordpress.org/support/topic/plugin-conflicts-42/

**Comment by razvanaldea89** [comment]
Should be fixed in latest version
