### ISSUE TITLE
number of downloads per day in the reports section

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#904]
**Is your feature request related to a problem? Please describe.**
I have Download Monitor at my website https://pistonrobot.com/ I can click on the "Reports" tab and see what is being downloaded. I have set to show me the trend (by day) for the last month. Sometimes there is a real spike one day and I am curious "So what was everyone downloading that day?" The only way I have figured out how to do this is to re-set the report to show only one day, that being the day that is showing the spike. Then I have to remember to set Download Monitor back to displaying a whole month. I would like to suggest a feature that if one was in the "Reports" section and it was displaying a range of dates with downloads by day, that one could put their mouse on the dot that shows how many downloads there were that day, and if one double clicked on that dot, then Download Monitor would display what the downloads were for that day, inside that display would be a box to click on and the display would go back to showing one month or one week or whatever had been chosen.
https://secure.helpscout.net/conversation/1856965102/46349/

**Comment by cristianraiber** [comment]
@razvanaldea89 - he's in for a ncie surprise shortly. New reports incoming ❤️

**Comment by razvanaldea89** [comment]
Going to close this, new reports are launched :D
