### ISSUE TITLE
does not work to select a download in the download gutenberg block

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#905]
**Describe the bug**
does not work to select a download in the download gutenberg block
Select a download first (Não funciona) o mesmo retorno o seguinte erro no console

wp.data.select( 'core/editor' ).getSelectedBlock is deprecated since version 5.3. Please use wp.data.select( 'core/block-editor' ).getSelectedBlock instead.

https://wordpress.org/support/topic/select-a-download-first/

<img width="1147" alt="Screenshot 2022-04-26 at 14 52 54" src="https://user-images.githubusercontent.com/26008574/165294316-ce693f4d-a9e9-4cef-a10a-006b4f3be9b3.png">

**To Reproduce**
1. Go to a page > add a download block > try to select a download
2. See error

**Extensions installed and activated:**
- [ ] Advanced Access Manager
- [ ] Amazon S3
- [ ] Buttons
- [ ] Captcha
- [ ] CSV Exporter
- [ ] CSV Importer
- [ ] Downloading Page
- [ ] Email lock
- [ ] Email Notifications
- [ ] Google Drive
- [ ] Gravity Forms
- [ ] Mailchimp
- [ ] Ninja Forms
- [ ] Page Addon
- [ ] Terms & Conditions
- [ ] Twitter Lock

**Additional context**

**Comment by razvanaldea89** [comment]
Download can be selected from the right panel, from the block settings. There wasn't a time when you could select the downloads from the block preview, at least none I can remember.
