### ISSUE TITLE
Remove all non-related actions from admin_notices on Download Monitor's 

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#910]
`remove_all_actions('admin_notices')`

Remove all actions that are not owned by Download Monitor or extensions from the plugin's pages.

**Comment by TeoAlex** [comment]
We need to change our DLM addons and add their admin notifications with prio. 8 or lower too.

**Comment by razvanaldea89** [comment]
Uncomment the line after we release our extensions with the modified priorities
