### ISSUE TITLE
display a message 'download complete'

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#911]
**Is your feature request related to a problem? Please describe.**
 the problem is that the user on the site does not receive any message when the download is complete, only the browser icon shows the download and this is sometimes not seen. We hope to see this new implementation soon.

**Describe the solution you'd like**
a way to show a message on the page when the download is complete

https://secure.helpscout.net/conversation/1864729868/46468?folderId=4638445

**Comment by razvanaldea89** [comment]
Going with XHR now shows the user the download process, with percentage and full download.
