### ISSUE TITLE
Display downloads left (Advanced Access Manager) 

### ISSUE THREAD

**Issue by jagge72** [WPChill/download-monitor#912]
Hi, 

Pls add a feature to display a users downloads left for a given period of time on the frontend 😊

Best regards

**Comment by razvanaldea89** [comment]
Locks in with https://github.com/WPChill/download-monitor/issues/1228 and DLM AAM

**Comment by jagge72** [comment]
Does this mean that you can now display downloads left per user role?

**Comment by cristianraiber** [comment]
cc @razvanaldea89

**Comment by razvanaldea89** [comment]
Not yet, I closed this because we have another ticket, https://github.com/WPChill/download-monitor/issues/1228, about an user account panel that will take into consideration downloads left and more, with integration from all Download Monitor's extensions.

Warmly,
Razvan

**Comment by jagge72** [comment]
@razvanaldea89 Well, I see...What I am looking for is quite simply a way to display downloads left like this (credits meaning downloads), and maybe even a way to set how many "credits" a download costs. 

<img width="312" alt="Skærmbillede 2023-03-13 kl  13 13 51" src="https://user-images.githubusercontent.com/42859324/224698738-f7ce0148-0d2b-4d1d-9030-531d93f5d140.png">

**Comment by jagge72** [comment]
If you add this I will surely purchase your plugin again. Also please look into adding a popup template if a user is not permitted to download a file, instead of having to use a redirect. Asked about this over a year ago, where you said that you would look into it 🥹 @cristianraiber  @razvanaldea89

**Comment by jagge72** [comment]
@razvanaldea89 Ahh, awesome! Now I only need that shortcode to display a users downloads left for the given time, and this will be amazing. I also noticed that a competitor of yours already has this. But really want to stick with you though 😅:

https://prnt.sc/2yDK3NGHqmfK

**Comment by jagge72** [comment]
Any update on this? @cristianraiber @razvanaldea89
