### ISSUE TITLE
On Pantheon hosted environments redirect to file doesn't work

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#914]
**Describe the bug**
The uploaded files real path is in the `/files/` directory, outside of the WP installation directory. The uploads directory points to `wp-content/uploads` but that is just a shortcut to the `/files/` directory mentioned before. When trying to redirect, after adding the `/files` directory to the allowed paths the redirect will take the visitor to `domain.com/year/month/file.ext` and not `domain.com/wp-content/uploads/year/month/file.ext`.

**Comment by TeoAlex** [comment]
https://github.com/WPChill/download-monitor/commit/7114c32ecd9eca7e84d0313b3d2094a8c2d4775f
