### ISSUE TITLE
Re-work the files area

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#917]
![CleanShot 2022-05-05 at 13 48 15](https://user-images.githubusercontent.com/7841556/166926402-19bcee29-e201-4172-aae4-542767dccb98.jpg)

**Comment by cristianraiber** [comment]
We will use the same concept of sidebar + "main settings area" as we do for Modula

![CleanShot 2022-05-05 at 13 47 08](https://user-images.githubusercontent.com/7841556/166926066-a3a99231-bff6-4fc0-ba59-60b0eeacdd86.jpg)

**Comment by cristianraiber** [comment]
- [ ] Metabox title changed from `Downloadable Files/Versions` to `File(s)`
- [ ] By default, the active section will be "Local files"
- [ ] All extensions used here, like Google Drive or Amazon S3 will add a "pro" badge (like we also do for Modula)
- [ ] Upload your files turns into a drag & drop

**Comment by cristianraiber** [comment]
- [ ] Metabox title changed from `Downloadable Files/Versions` to `File(s)`
- [ ] By default, the active section will be "Local files"
- [ ] All extensions used here, like Google Drive or Amazon S3 will add a "pro" badge (like we also do for Modula)
- [ ] Upload your files turns into a drag & drop
- [ ] Although in the screenshot #3 there is a trashcan, we will not be replacing the "remove button"
- [ ] Next to the remove button, there will be an "edit" icon. When clicked on it, the user will be able to edit: file version, see file path
- [ ] Expand & "collapse all" action links will be removed
- [ ] We will show a file preview, if available. For file types where no preview is available, like PDFs or ZIPs, we can just use an icon
- [ ] Number of downloads and file date will no longer be editable. When clicking on "edit" on a download, user will be able to see these values, but not edit them.

**Comment by razvanaldea89** [comment]
Files( Versions ) area has been re-worked. @cristianraiber do you want to implement something from here to the new Versions UI ?
