### ISSUE TITLE
Integration of 3th party payment gateway is currently impossible without a hack

### ISSUE THREAD

**Issue by GodModus** [WPChill/download-monitor#922]
**Bug Description**
Download Monitor makes it almost impossible to extend the available payment methods. The template `'templates/shop/checkout/payment.php' (see snippet #1)` responsible for outputting the payment methods lacks context which is necessary for my callback to know which payment method is being iterated over. Without this context a hack was required in order to circumvent the issue.

SNIPPET #1
` <?php
    // SOURCE: download-monitor//templates/shop/checkout/payment.php @ line 17
    //

    foreach ( $payment_gateways as $gateway ) {
    download_monitor()->service( ‘template_handler’ )->get_template_part( ‘shop/checkout/payment-gateway’, ”, ”, array(
    ‘cart’ => $cart,
    ‘gateway’ => $gateway,
    ‘default_gateway’ => $default_gateway
    ) );
    }
    ?> `
 
Only the first and last arguments are passed to get_template_part(…). The second argument ($name) - an empty string - is the issue here. This argument provides context - the name of the current payment gateway - to `apply_filters( 'dlm_get_template_part', $template, $slug, $name )` which a callback can use to determine to filter the default payment template file. Without knowing which payment gateway is about to be rendered this hook is useless for adding new payment extensions. Obviously the callback should only alter the template for its respective payment gateway. In the current version there is no way for my callback to make any distinction between the gateways being iterated over since the arguments  `$template, $slug` of the hook 'dlm_get_template_part' are always the same: 
$template = "[PATH]/wp-content/plugins/download-monitor//templates/shop/checkout/payment-gateway.php"
$slug = "shop/checkout/payment-gateway"

**SOLUTION**
The only way around this issue was to create a copy of `download-monitor//templates/shop/checkout/payment.php `, modify the arguments to get_template_part( ...) and used a callback to load mine file instead. This is considered a sloppy Hack that can easily break the site if the core plugin changes. So the only REAL solution is for you guys to make the simple adjustment. The code in `download-monitor//templates/shop/checkout/payment.php @ line 17` should be:

```
download_monitor()->service( ‘template_handler’ )->get_template_part( ‘shop/checkout/payment-gateway’, 
     $gateway->get_id() , 
      ”,
      array(
        ‘cart’ => $cart,
        ‘gateway’ => $gateway,
        ‘default_gateway’ => $default_gateway
    ) );
```

**Comment by razvanaldea89** [comment]
Hey @GodModus ,

Most probably the modification will be launched in DLM 4.5.96, so after the next release ( which is scheduled for this week or on Monday, 25th July ).

**Comment by TeoAlex** [comment]
Added a 4th parameter to the filter that contains the $cart, $gateway and $default_gateway in the case mentioned above.
Users can now determine witch gateway is going to be rendered.

**Comment by razvanaldea89** [comment]
This needs to be included in the 4.6.0 branch

**Comment by razvanaldea89** [comment]
Will be launched on Tuesday, 16th August

**Comment by GodModus** [comment]
Just want your feedback on something I've been  thinking about. Since this issue has probably existed from the inception of the plugin, isnt it telling that mostly likely not many people are building payment integrations since only till now it has come to your attention.
