### ISSUE TITLE
 Using cloudflare’s forwarded IP if it exists in header

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#923]
**Is your feature request related to a problem? Please describe.**
The IP Address in download logs shows the IP Address of cloudflare if cloudflare proxy is enabled. This doesn’t happen in WooCommerce.

**Describe the solution you'd like**
A simple check for cloudflare’s forwarded IP would be suffice, as CF forwards user ip as HTTP_CF_CONNECTING_IP.

```
if (isset($_SERVER["HTTP_CF_CONNECTING_IP"])) {
  $_SERVER['REMOTE_ADDR'] = $_SERVER["HTTP_CF_CONNECTING_IP"];
}
```
Please if possible add this feature in a future update.

**Additional context**
https://wordpress.org/support/topic/using-cloudflares-forwarded-ip-if-it-exists-in-header/

**Comment by ph33nx** [comment]
I can confirm that the fix is working. Thanks.
