### ISSUE TITLE
Update required extensions versions

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#926]
DLM 4.6.0 needs at least: 
- DLM Amazon S3 4.0.6

**Comment by cristianraiber** [comment]
@razvanaldea89 - should be handled through Wisdom

**Comment by razvanaldea89** [comment]
@cristianraiber was referring to the one set [here](https://github.com/WPChill/download-monitor/blob/4.6.0/src/Product/ProductManager.php#L35), where we define the requirements that are shown in the plugins page.

![image](https://user-images.githubusercontent.com/44024114/167816094-2a5017c7-349d-4c4a-936c-b9cdd474a74c.png)
