### ISSUE TITLE
4.6.0 does not appear to work with external links

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#960]
**Describe the bug**
if you add an external link in a download it gives an error: Download is not allowed for this file type.
in 4.5.93 works fine

**To Reproduce**
1. Go to a download > file url > add an external link, user used https://www.mediafire.com/file/dtilaudnl82zbc8/india+tv+by+Indian+Dish+Network.m3u/file

2. try to download
3. See error

**Extensions installed and activated:**
- [ ] Advanced Access Manager
- [ ] Amazon S3
- [ ] Buttons
- [ ] Captcha
- [ ] CSV Exporter
- [ ] CSV Importer
- [ ] Downloading Page
- [ ] Email lock
- [ ] Email Notifications
- [ ] Google Drive
- [ ] Gravity Forms
- [ ] Mailchimp
- [ ] Ninja Forms
- [ ] Page Addon
- [ ] Terms & Conditions
- [ ] Twitter Lock

**Additional context**
https://secure.helpscout.net/conversation/1897348175/47123?folderId=4638443

**Comment by razvanaldea89** [comment]
@mplusb do you remember if it was with redirect or download? 4.5.93 doesn't download the file. In case was redirect, new 4.6.0 works OK so this can be closed.

**Comment by mplusb** [comment]
confirm it works now
