### ISSUE TITLE
Download Monitor to display according to the user language

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#961]
**Describe the bug**
since many versions I see the Download Monitor admin dashboard menu based on the website language, not the user language. In my case, the website is in Japanese but my user interface is in English, and I see all the Download Monitor menus in Japanese. This change happened sometime last year, can you please fix it? Language should check the user settings, not the website settings (all my other plugins work correctly, and my colleagues see different languages based on their account language). 

**To Reproduce**
1. Go to Settings > General > set the site language to Spanish for example
2. Go to the user profile > select the language to English
3. See issue - it still displays the download monitor settings in Spanish

**Expected behavior**
Download Monitor to change according to the user language

**Additional context**
https://secure.helpscout.net/conversation/1899544652/47168?folderId=4638445

**Comment by razvanaldea89** [comment]
Seems to be OK, changed site lang to Deutsch and profile lang to English and vice-versa and it works as expected.

**Comment by mplusb** [comment]
+1 issue happened again to an user and myself

**Comment by mplusb** [comment]
to replicate, after you change the site's language > download and install WordPress Japanese translations (dashboard > Updates)

**Comment by mplusb** [comment]
<img width="1080" alt="Screenshot 2022-12-07 at 13 13 16" src="https://user-images.githubusercontent.com/26008574/206164759-833ead18-fd78-4f5f-9999-b4c3aed9fcb8.png">
