### ISSUE TITLE
Redirect to file doesn't work with Bedrock

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/download-monitor#973]
Redirect to file doesn't work with [Bedrock](https://roots.io/bedrock/) . The user is redirected to `domain.com/wp/uploads/yyyy/dd/file.ext `instead of `domain.com/app/uploads/yyyy/dd/file.ext`

https://github.com/WPChill/download-monitor/blob/4.5.93/src/DownloadHandler.php#L511

**Comment by razvanaldea89** [comment]
@TeoAlex can you please re-test this?
