### ISSUE TITLE
Remove double usage of parse_file_path();

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/download-monitor#983]
We have 2 functions calling parse_file_path() function:

https://github.com/WPChill/download-monitor/blob/4.5.95/src/DownloadHandler.php#L687
https://github.com/WPChill/download-monitor/blob/4.5.95/src/DownloadHandler.php#L413

We should remove the call from here https://github.com/WPChill/download-monitor/blob/4.5.95/src/DownloadHandler.php#L687 and use standard PHP filesize() function.

**Comment by razvanaldea89** [comment]
Also has minor check fix here https://github.com/WPChill/download-monitor/commit/ab6589bedda8b7c129af3d82cb0a54d64e4eab9b
