### ISSUE TITLE
Overwrite existing file in the dlm_uploads?

### ISSUE THREAD

**Issue by perplexityjeff** [WPChill/download-monitor#985]
Hi,

It seems that if we overwrite a file that exists in the dlm_uploads the changes do not get placed on the website? If we overwrite the file on the dlm_uploads and just press Update on the specific download in the Download Monitor plugin the changes are on the website. 

Is this some kind of cache? For our use case of the plugin we would like to modify the file and see the effect on the website and still have the security and ease of use of the plugin.

Thanks in advance.

**Comment by cristianraiber** [comment]
@perplexityjeff - that's an interesting use-case

**Comment by perplexityjeff** [comment]
I expected this to caching but if it is an enhancement then of course I would like to see this as it makes making modifications for us a lot easier. 

Thank you!

**Comment by adrianf0** [comment]
@perplexityjeff @cristianraiber Is the problem resolved? Is there any cache involved? Is there a way to refresh this cache? Is there any other way to overwrite a file than through admin dashboard and which could be scripted?

**Comment by razvanaldea89** [comment]
@perplexityjeff could you please let us know what modifications are not seen on the website?

**Comment by perplexityjeff** [comment]
Hi @razvanaldea89, when we update the file using for example an FTP client to overwrite the file that is uploaded to the dlm_uploads folder then the updated file cannot be downloaded by the plugin unless I go to the Download Monitor overview find the download and press 'update'. 

In our case we would like to perform updates of the files on the website automatically from another source. So in our case it would be great if we could modify the file using an FTP client and still have the same protective measures that the plugin offers.

**Comment by razvanaldea89** [comment]
Thanks for the info @perplexityjeff . Could you please tell me what version of the plugin you are using?

**Comment by perplexityjeff** [comment]
I am currently running version 4.6.1 @razvanaldea89

**Comment by razvanaldea89** [comment]
Strange, this issue should have been fixed in version 4.5.9 of the plugin and another enhancement in version 4.9.5. Could you please describe your steps on how to achieve this issue? Both me and a colleague tried to replicate this issue but could not do it.

Warmly,
Razvan

**Comment by perplexityjeff** [comment]
Hi @razvanaldea89, Sorry for the late update. I just tested it and it seems to work when the replace the file using an FTP solution. 

I believe you can close this issue.

**Comment by razvanaldea89** [comment]
Awesome news! Thank you for the feedback.

Have a wonderful day!
Razvan
