### ISSUE TITLE
Shortcode order by description

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#988]
**Describe the bug**
I used the shortcodes (https://www.download-monitor.com/kb/shortcode-downloads/) to list my downloads from a category … everything works fine, but I’ve a problem with orderby="title".

My titles are like:
This is a nice Filename since 01.07.2022
This is a nice Filename since 27.06.2022
This is a nice Filename since 03.03.2021
…

If the downloads ordered by title the order is not correct because of the date at the end. The result is:
This is a nice Filename since 27.06.2022
This is a nice Filename since 03.03.2021
This is a nice Filename since 01.07.2022

Then I thought maybe I could sort by the short description.

Is this possible? Than I could enter there something like this: 22-07-01

This is my shortcode
[downloads featured="false" category="grundversorgung" tag="preisblatt" template="default" loop_start="" loop_end="" before="" after="" order="DESC" orderby="title"]

https://wordpress.org/support/topic/shortcode-order-by-description/

**Comment by razvanaldea89** [comment]
Description is meant to hold much more information, and sorting by it is doable but not recommended. What it should work is sorting by title in a natural way ( `strnatcmp` ). For the moment we'll leave the sorting to be handled by WordPress' default way and will close this. If there are complains from more users we'll re-open.
