### ISSUE TITLE
Do DIRECTORY_SEPARATOR replacement for file_path, correct_path and allowed_paths

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/download-monitor#991]
**Is your feature request related to a problem? Please describe.**
Make sure all the paths have `/` as separator, being independent of the system on which the plugin is installed.

**Comment by razvanaldea89** [comment]
@TeoAlex please test this on Windows when you have time
@giucu91 / @cristianraiber please test this on macOS when you have time

**Comment by razvanaldea89** [comment]
How to test :
1. Create normal download and test the download process.
2. Create download from defined path ( Settings > Advanced > Miscellaneous > Other downloads path ) and test the download process
3. Remove the defined path and test to see if the file still downloads

**Comment by TeoAlex** [comment]
No problems on windows + flywheel
