### ISSUE TITLE
Download Link not working due to incorrect file size

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#994]
**Describe the bug**
Recently we have released our own CDN – SiteGround CDN service which is being used by a lot of our clients already.
We have received several reports from our clients for incompatibility between the Download Monitor plugin and our CDN. In particular the reported issue is with the download URLs and specifically with the file size returned by the plugin.
When the download URL is hit, the user receives an error:

"This site can't be reached
The web page at https://website.com/download/11111/ might be temporarily down or it may have moved permanently to a new web address.ERR_HTTP2_PROTOCOL_ERROR"
Our team investigated the case in detail and found it is related to the way the Download Monitor plugin calculates the download file size. The plugin adds 1 byte to the original file size while calculating it here: https://plugins.trac.wordpress.org/browser/download-monitor/trunk/src/DownloadHandler.php#L406. The CDN request to the file fails due to the incorrect file size.

We have already found there are old reports for the issue and noticed it is present with other platforms as well. Unfortunately no fix is being released yet.

We do want our clients to continue to use both our CDN and your plugin. So our developers have a suggestion to fix the issue which you can check bellow:

if ( ! $range_end || $range_end > $version->get_filesize() ) {
 $range_end = $version->get_filesize() - 1;
 } else {
 $range_end = intval( $range_end );
 }
//$new_length = $range_end - $range;
 $new_length = ($range_end - $range) + 1;
 header( $_SERVER['SERVER_PROTOCOL']. " 206 Partial Content" );
 header( "Content-Length: $new_length" );
 header( "Content-Range: bytes {$range}-{$range_end}/{$version->get_filesize()}" );
} else {
 $range = false;
 }

https://wordpress.org/support/topic/download-link-not-working-due-to-incorrect-file-size/

**Comment by razvanaldea89** [comment]
This needs to be included in the 4.6.0 branch

**Comment by razvanaldea89** [comment]
Will be  launched on Tuesday, 16th August
