### ISSUE TITLE
Error – File Type is Not Allowed

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#995]
**Describe the bug**
Have unset some mime types on my site.

When attempting to add the disallowed file types to the media library, the system generates “Sorry, you are not allowed to upload this file type.” error.

When attempting to add the disallowed file types to the upload file area on download monitor “add download” page, nothing happens – no attempt to upload the file, no error message.

Is it possible to add the system “Sorry, you are not allowed to upload this file type.” error to your pages as well?

https://wordpress.org/support/topic/error-file-type-is-not-allowed/

**Comment by razvanaldea89** [comment]
![image](https://user-images.githubusercontent.com/44024114/181790851-5bcf8281-2493-47f1-9d3f-d0e18d6795e7.png)

**Comment by razvanaldea89** [comment]
Commits from 4.6.0 branch have been included
